/** The pure parts of withAppIntents.js (Swift source, .strings files, Info.plist); dependency-free so jest can load them. */

const LANGS = ["en", "zh-Hans"];
const TOKEN = "${applicationName}";

const pascal = (id) => id.charAt(0).toUpperCase() + id.slice(1);
const structOf = (entry) => `Open${pascal(entry.id)}Intent`;
const quoted = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

function lookup(messages, key) {
  const value = key.split(".").reduce((node, part) => (node && typeof node === "object" ? node[part] : undefined), messages);
  if (typeof value !== "string" || value === "") throw new Error(`withAppIntents: no message "${key}".`);
  return value;
}

/** "Open To do" / "打开待办": the intent's title, from the tab's own word. `messages` is { en, "zh-Hans" }. */
function titleOf(entry, lang, messages) {
  const label = lookup(messages[lang], entry.label);
  return lang === "en" ? `Open ${label}` : `打开${label}`;
}

/** Every phrase carries the app name token exactly once (Xcode's extractor rejects one that does not); languages pair up. */
function checkEntries(entries) {
  for (const entry of entries) {
    for (const lang of LANGS) {
      const phrases = entry.phrases?.[lang];
      if (!phrases || phrases.length === 0) throw new Error(`withAppIntents: "${entry.id}" has no ${lang} phrase.`);
      for (const phrase of phrases) {
        if (phrase.split(TOKEN).length !== 2) throw new Error(`withAppIntents: phrase "${phrase}" must contain ${TOKEN} exactly once.`);
      }
    }
    if (entry.phrases.en.length !== entry.phrases["zh-Hans"].length) throw new Error(`withAppIntents: "${entry.id}" needs as many zh-Hans phrases as en ones.`);
  }
}

/**
 * ShortcutIntents.swift. Each intent opens its deep link in the app (`openAppWhenRun`), so the JS
 * side routes it exactly as it routes a tapped launcher shortcut. Phrases here are the English ones;
 * other languages come from AppShortcuts.strings, keyed by these same texts.
 */
function swiftSource({ scheme, provider, entries }, messages) {
  checkEntries(entries);
  const intents = entries
    .map(
      (e) => `@available(iOS 16.0, *)
struct ${structOf(e)}: AppIntent {
  static let title: LocalizedStringResource = ${quoted(titleOf(e, "en", messages))}
  static let openAppWhenRun: Bool = true

  @MainActor
  func perform() async throws -> some IntentResult {
    if let url = URL(string: ${quoted(`${scheme}://${e.path}`)}) {
      await UIApplication.shared.open(url)
    }
    return .result()
  }
}`
    )
    .join("\n\n");
  const shortcuts = entries
    .map((e) => {
      const phrases = e.phrases.en.map((p) => quoted(p).replace(TOKEN, "\\(.applicationName)")).join(", ");
      return `    AppShortcut(
      intent: ${structOf(e)}(),
      phrases: [${phrases}],
      shortTitle: ${quoted(titleOf(e, "en", messages))},
      systemImageName: ${quoted(e.symbol)}
    )`;
    })
    .join("\n");
  return `// Generated by mobile/plugins/withAppIntents.js -- do not edit; edit voiceEntries.js.
// Opens a page and nothing more: no intent here approves, rejects or submits.
import AppIntents
import UIKit

${intents}

@available(iOS 16.0, *)
struct ${provider}: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
${shortcuts}
  }
}
`;
}

/** <lang>.lproj/AppShortcuts.strings: the English phrase (as in the Swift) -> that language's phrase. */
function appShortcutsStrings({ entries }, lang) {
  checkEntries(entries);
  const lines = [];
  for (const e of entries) e.phrases.en.forEach((phrase, i) => lines.push(`${quoted(phrase)} = ${quoted(e.phrases[lang][i])};`));
  return lines.join("\n") + "\n";
}

/** <lang>.lproj/Localizable.strings: the intents' titles (the English title is the key). */
function localizableStrings({ entries }, lang, messages) {
  return entries.map((e) => `${quoted(titleOf(e, "en", messages))} = ${quoted(titleOf(e, lang, messages))};`).join("\n") + "\n";
}

/** Info.plist: the languages the strings exist in, and the names Siri also accepts for ${applicationName}. */
function applyInfoPlist(plist, { alternativeNames }) {
  plist.CFBundleLocalizations = [...new Set([...(plist.CFBundleLocalizations ?? []), ...LANGS])];
  plist.INAlternativeAppNames = alternativeNames.map((name) => ({ INAlternativeAppName: name }));
  return plist;
}

module.exports = { LANGS, TOKEN, appShortcutsStrings, applyInfoPlist, checkEntries, localizableStrings, lookup, structOf, swiftSource, titleOf };
