# Generated by Django 5.2.17 on 2026-09-29 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soul_accounts", "0004_soulaccount_welcomed_civilizations"),
        ("soul_assist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assistconversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assist_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assistconversation",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assist_conversations",
                to="soul_accounts.soulaccount",
            ),
        ),
        migrations.AlterField(
            model_name="assistconversation",
            name="screen",
            field=models.CharField(
                choices=[
                    ("applications", "applications"),
                    ("sentence", "sentence"),
                    ("life", "life"),
                    ("letters", "letters"),
                    ("circle", "circle"),
                    ("settings", "settings"),
                    ("other", "other"),
                    ("actors", "actors"),
                    ("admin", "admin"),
                    ("audit", "audit"),
                    ("corpus", "corpus"),
                    ("cross-judgments", "cross-judgments"),
                    ("dashboard", "dashboard"),
                    ("death-sync", "death-sync"),
                    ("dispatch", "dispatch"),
                    ("disposition", "disposition"),
                    ("judgment", "judgment"),
                    ("ledger", "ledger"),
                    ("menus", "menus"),
                    ("moderation", "moderation"),
                    ("notifications", "notifications"),
                    ("organizations", "organizations"),
                    ("permissions", "permissions"),
                    ("profile", "profile"),
                    ("realms", "realms"),
                    ("rebirth-applications", "rebirth-applications"),
                    ("recycle-bin", "recycle-bin"),
                    ("scheduler", "scheduler"),
                    ("sentence-requests", "sentence-requests"),
                    ("social", "social"),
                    ("soul-credentials", "soul-credentials"),
                    ("soul-inbox", "soul-inbox"),
                    ("souls", "souls"),
                    ("tenants", "tenants"),
                    ("users", "users"),
                    ("welcome", "welcome"),
                    ("workflow", "workflow"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="assistconversation",
            index=models.Index(
                fields=["user", "screen", "-last_active_at"],
                name="soul_assist_user_id_a076a0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account__isnull", False), ("user__isnull", True)),
                    models.Q(("account__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="assist_conversation_one_owner",
            ),
        ),
    ]
