# Generated by Django 5.2.17 on 2026-09-29 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.death_sync.fields


class Migration(migrations.Migration):

    dependencies = [
        ("soul_accounts", "0004_soulaccount_welcomed_civilizations"),
        ("soul_assist", "0002_officer_conversations"),
        ("tenants", "0013_egy_hall_name_section_ten"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistEvalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("soul", "soul"), ("officer", "officer")],
                        max_length=10,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("zh-Hans", "zh-Hans"), ("en", "en")],
                        default="zh-Hans",
                        max_length=10,
                    ),
                ),
                (
                    "screen",
                    models.CharField(
                        choices=[
                            ("applications", "applications"),
                            ("sentence", "sentence"),
                            ("life", "life"),
                            ("letters", "letters"),
                            ("circle", "circle"),
                            ("settings", "settings"),
                            ("other", "other"),
                            ("actors", "actors"),
                            ("admin", "admin"),
                            ("audit", "audit"),
                            ("corpus", "corpus"),
                            ("cross-judgments", "cross-judgments"),
                            ("dashboard", "dashboard"),
                            ("death-sync", "death-sync"),
                            ("dispatch", "dispatch"),
                            ("disposition", "disposition"),
                            ("judgment", "judgment"),
                            ("ledger", "ledger"),
                            ("menus", "menus"),
                            ("moderation", "moderation"),
                            ("notifications", "notifications"),
                            ("organizations", "organizations"),
                            ("permissions", "permissions"),
                            ("profile", "profile"),
                            ("realms", "realms"),
                            ("rebirth-applications", "rebirth-applications"),
                            ("recycle-bin", "recycle-bin"),
                            ("scheduler", "scheduler"),
                            ("sentence-requests", "sentence-requests"),
                            ("social", "social"),
                            ("soul-credentials", "soul-credentials"),
                            ("soul-inbox", "soul-inbox"),
                            ("souls", "souls"),
                            ("tenants", "tenants"),
                            ("users", "users"),
                            ("welcome", "welcome"),
                            ("workflow", "workflow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                ("expected_tools", models.JSONField(blank=True, default=list)),
                ("must_include", models.JSONField(blank=True, default=list)),
                ("must_not_include", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["side", "id"],
            },
        ),
        migrations.AddField(
            model_name="assistconversation",
            name="is_eval",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AssistConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values", models.JSONField(blank=True, default=dict)),
                (
                    "api_key",
                    apps.death_sync.fields.EncryptedCharField(
                        blank=True, default="", max_length=1000
                    ),
                ),
                ("api_key_set_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eval_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eval_soul_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="soul_accounts.soulaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssistEvalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("done", "done"),
                            ("stopped_at_cap", "stopped_at_cap"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("candidates", models.JSONField(default=list)),
                ("case_ids", models.JSONField(default=list)),
                ("estimated_cost", models.FloatField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("done", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=list)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistEvalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate", models.PositiveSmallIntegerField()),
                ("question", models.CharField(max_length=1000)),
                (
                    "side",
                    models.CharField(
                        choices=[("soul", "soul"), ("officer", "officer")],
                        max_length=10,
                    ),
                ),
                ("tools_called", models.JSONField(default=list)),
                ("answer", models.TextField(blank=True, default="")),
                ("error", models.CharField(blank=True, default="", max_length=40)),
                ("tools_ok", models.BooleanField(default=False)),
                ("included", models.JSONField(default=dict)),
                ("excluded", models.JSONField(default=dict)),
                ("passed", models.BooleanField(default=False)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("tokens", models.JSONField(default=dict)),
                ("cost", models.FloatField(null=True)),
                (
                    "case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="soul_assist.assistevalcase",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="soul_assist.assistevalrun",
                    ),
                ),
            ],
            options={
                "ordering": ["candidate", "id"],
            },
        ),
        migrations.CreateModel(
            name="AssistUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("soul", "soul"), ("officer", "officer")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "ok"),
                            ("empty", "empty"),
                            ("unavailable", "unavailable"),
                            ("busy", "busy"),
                            ("rate_limited", "rate_limited"),
                            ("not_configured", "not_configured"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=200)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("is_eval", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
