# Generated by Django 5.2.17 on 2026-09-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soul_assist', '0004_draft_eval_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistconfig',
            name='cap_alert_sent_for',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='assistconfig',
            name='cap_closed_for',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
