# Generated by Django 5.2.17 on 2026-09-29 17:20

import pgvector.django.vector
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    """只在 PostgreSQL 上建(SQLite 上 `embedding` 存文本)。回滚不删扩展:Django 的 CreateExtension
    回滚时不分数据库地去查 `pg_extension`(SQLite 上报错),而留着一个没人用的扩展无害。"""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):

    dependencies = [
        ('soul_assist', '0005_cap_alert_and_reopen'),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, migrations.RunPython.noop),
        migrations.AddField(
            model_name='assistconfig',
            name='vectors_error',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='assistconfig',
            name='vectors_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistconfig',
            name='vectors_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistconfig',
            name='vectors_synced_model',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='assistevalcase',
            name='expected_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assistevalresult',
            name='retrieval',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='assistevalresult',
            name='retrieval_hit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assistevalresult',
            name='retrieved',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assistusage',
            name='retrieval',
            field=models.CharField(blank=True, choices=[('vector', 'vector'), ('fallback', 'fallback'), ('fallback_low_similarity', 'fallback_low_similarity')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='HelpChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=10)),
                ('audience', models.CharField(max_length=10)),
                ('screens', models.JSONField(default=list)),
                ('civilizations', models.JSONField(default=list)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=200)),
                ('dims', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField()),
                ('embedded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['locale', 'audience', 'model', 'dims'], name='soul_assist_locale_73511e_idx')],
                'constraints': [models.UniqueConstraint(fields=('locale', 'entry_id'), name='help_chunk_one_per_entry')],
            },
        ),
    ]
