# Generated by Django 5.2.17 on 2026-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soul_assist', '0006_rag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistconversation',
            name='screen',
            field=models.CharField(choices=[('applications', 'applications'), ('sentence', 'sentence'), ('life', 'life'), ('letters', 'letters'), ('circle', 'circle'), ('settings', 'settings'), ('other', 'other'), ('about', 'about'), ('actors', 'actors'), ('admin', 'admin'), ('audit', 'audit'), ('corpus', 'corpus'), ('cross-judgments', 'cross-judgments'), ('dashboard', 'dashboard'), ('death-sync', 'death-sync'), ('dispatch', 'dispatch'), ('disposition', 'disposition'), ('judgment', 'judgment'), ('ledger', 'ledger'), ('menus', 'menus'), ('moderation', 'moderation'), ('notifications', 'notifications'), ('organizations', 'organizations'), ('permissions', 'permissions'), ('profile', 'profile'), ('realms', 'realms'), ('rebirth-applications', 'rebirth-applications'), ('recycle-bin', 'recycle-bin'), ('scheduler', 'scheduler'), ('sentence-requests', 'sentence-requests'), ('social', 'social'), ('soul-credentials', 'soul-credentials'), ('soul-inbox', 'soul-inbox'), ('souls', 'souls'), ('tenants', 'tenants'), ('users', 'users'), ('welcome', 'welcome'), ('workflow', 'workflow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assistevalcase',
            name='screen',
            field=models.CharField(choices=[('applications', 'applications'), ('sentence', 'sentence'), ('life', 'life'), ('letters', 'letters'), ('circle', 'circle'), ('settings', 'settings'), ('other', 'other'), ('about', 'about'), ('actors', 'actors'), ('admin', 'admin'), ('audit', 'audit'), ('corpus', 'corpus'), ('cross-judgments', 'cross-judgments'), ('dashboard', 'dashboard'), ('death-sync', 'death-sync'), ('dispatch', 'dispatch'), ('disposition', 'disposition'), ('judgment', 'judgment'), ('ledger', 'ledger'), ('menus', 'menus'), ('moderation', 'moderation'), ('notifications', 'notifications'), ('organizations', 'organizations'), ('permissions', 'permissions'), ('profile', 'profile'), ('realms', 'realms'), ('rebirth-applications', 'rebirth-applications'), ('recycle-bin', 'recycle-bin'), ('scheduler', 'scheduler'), ('sentence-requests', 'sentence-requests'), ('social', 'social'), ('soul-credentials', 'soul-credentials'), ('soul-inbox', 'soul-inbox'), ('souls', 'souls'), ('tenants', 'tenants'), ('users', 'users'), ('welcome', 'welcome'), ('workflow', 'workflow')], max_length=20),
        ),
    ]
