# Generated by Django 5.2.17 on 2026-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soul_assist', '0007_about_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistmessage',
            name='interruption',
            field=models.CharField(blank=True, choices=[('stopped', 'stopped'), ('interrupted', 'interrupted')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='assistusage',
            name='fallback_reason',
            field=models.CharField(blank=True, choices=[('connection', 'connection'), ('timeout', 'timeout'), ('rate_limited', 'rate_limited'), ('server_error', 'server_error'), ('quota', 'quota'), ('circuit_open', 'circuit_open')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='assistusage',
            name='provider_role',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('backup', 'backup')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='assistusage',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('empty', 'empty'), ('unavailable', 'unavailable'), ('busy', 'busy'), ('rate_limited', 'rate_limited'), ('not_configured', 'not_configured'), ('stopped', 'stopped'), ('interrupted', 'interrupted'), ('failed_over', 'failed_over')], max_length=20),
        ),
    ]
