# Generated by Django 5.2.14 on 2026-05-08 07:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgment', '0001_initial'),
        ('realms', '0001_initial'),
        ('souls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_reset', models.CharField(choices=[('MENGPO', '孟婆汤 (Mengpo Soup)'), ('LETIES', '忘川 (Lethe)'), ('SPELL', 'Spell Recitation'), ('NONE', 'No Reset')], default='NONE', max_length=20)),
                ('is_eternal', models.BooleanField(default=False)),
                ('sentence_years', models.IntegerField(blank=True, help_text='Sentence duration in years (null = eternal)', null=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_realm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositions', to='realms.realm')),
                ('judgment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposition', to='judgment.judgment')),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='souls.soul')),
            ],
            options={
                'verbose_name': 'Disposition',
                'verbose_name_plural': 'Dispositions',
                'ordering': ['-created_at'],
            },
        ),
    ]
