# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0003_disposition_indexes'),
        ('judgment', '0005_add_approval_workflow_models'),
        ('realms', '0004_realm_tenant'),
        ('souls', '0009_add_approval_workflow_models'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disposition',
            name='idx_disposition_tenant_executed',
        ),
        migrations.RemoveIndex(
            model_name='disposition',
            name='idx_disposition_soul_created',
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['tenant', 'created_at'], name='disposition_tenant__b73d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['soul'], name='disposition_soul_id_34cdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['is_executed'], name='disposition_is_exec_631d18_idx'),
        ),
    ]
