# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0006_disposition_delete_reason_disposition_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='disposition',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
