# Generated by Django 5.2.16 on 2026-08-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposition", "0009_lethe_storage_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposition",
            name="sentence_years",
            field=models.IntegerField(
                blank=True,
                help_text="Sentence duration in years; null = no term recorded (see is_eternal)",
                null=True,
            ),
        ),
    ]
