# Generated by Django 5.2.16 on 2026-08-31 06:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0011_disposition_term_start'),
        ('judgment', '0020_remove_judgmentcitation_unique_citation_judgment_statute_and_more'),
        ('realms', '0018_split_greek_from_european'),
        ('souls', '0032_soulrecord_civilization_help_text'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='sentence_years',
            field=models.IntegerField(blank=True, help_text='Sentence duration in years; null = no term recorded (see is_eternal)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(('sentence_years__isnull', True), ('sentence_years__gte', 0), _connector='OR'), name='disposition_sentence_years_not_negative'),
        ),
    ]
