# Generated by Django 5.2.17 on 2026-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposition", "0013_disposition_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="disposition",
            name="sentence_node_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
