# Generated by Django 5.2.17 on 2026-09-24 15:08
"""处置期满:`expired_at` 与「期满必已执行」约束。

纯加列,存量行全为 null(= 未期满);第一次每日检查(或
`manage.py expire_dispositions`)会把刑期已走完的存量处置补上。
约束对存量行成立:所有行 `expired_at` 都是 null。
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposition", "0014_disposition_sentence_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="disposition",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="disposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expired_at__isnull", True), ("is_executed", True), _connector="OR"
                ),
                name="disposition_expired_only_if_executed",
            ),
        ),
    ]
