# Generated by Django 5.2.14 on 2026-05-08 07:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soul',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('civilization', models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat')], default='CHINESE', max_length=20)),
                ('current_state', models.CharField(choices=[('ALIVE', 'Alive'), ('JUDGING', 'Under Judgment'), ('DISPOSED', 'Disposed'), ('REINCARNATING', 'Reincarnating'), ('LOST', 'Lost/Suspended')], default='ALIVE', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('origin_location', models.CharField(blank=True, max_length=255)),
                ('birth_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('merit_score', models.IntegerField(default=0)),
                ('demerit_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soul',
                'verbose_name_plural': 'Souls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoulRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('MERIT', 'Merit'), ('DEMERIT', 'Demerit'), ('JUDGMENT', 'Judgment Evidence'), ('DISPOSITION', 'Disposition Record')], max_length=20)),
                ('civilization', models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat')], default='CHINESE', max_length=20)),
                ('description', models.TextField()),
                ('weight', models.IntegerField(default=1, help_text='Significance weight (1-100). Affects karma calculation.')),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='souls.soul')),
            ],
            options={
                'verbose_name': 'Soul Record',
                'verbose_name_plural': 'Soul Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
