# Generated by Django 5.2.14 on 2026-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulrecord',
            name='category',
            field=models.CharField(choices=[('CHARITY', 'Charity / Generosity'), ('COMPASSION', 'Compassion / Kindness'), ('HONESTY', 'Honesty / Integrity'), ('COURAGE', 'Courage / Bravery'), ('WISDOM', 'Wisdom / Knowledge'), ('PIETY', 'Piety / Devotion'), ('CRUELTY', 'Cruelty / Violence'), ('DECEPTION', 'Deception / Lying'), ('COWARDICE', 'Cowardice'), ('GREED', 'Greed / Avarice'), ('BLASPHEMY', 'Blasphemy / Impiety'), ('MURDER', 'Murder / Killing'), ('OTHER', 'Other')], default='OTHER', help_text='Standardized category for this record', max_length=20),
        ),
        migrations.AddField(
            model_name='soulrecord',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date the event occurred (for time-decay calculation)', null=True),
        ),
        migrations.AddField(
            model_name='soulrecord',
            name='is_milestone',
            field=models.BooleanField(default=False, help_text='If true, weight is doubled (major life event)'),
        ),
    ]
