# Generated by Django 5.2.14 on 2026-05-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0003_soul_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soul',
            name='civilization',
        ),
    ]
