# Generated by Django 5.2.14 on 2026-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0004_remove_soul_civilization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soul',
            index=models.Index(
                fields=['tenant', 'current_state'],
                name='idx_soul_tenant_state',
            ),
        ),
        migrations.AddIndex(
            model_name='soul',
            index=models.Index(
                fields=['tenant', 'name'],
                name='idx_soul_tenant_name',
            ),
        ),
    ]
