# Generated by Django 5.2.14 on 2026-05-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0005_add_tenant_indexes'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='soul',
            name='idx_soul_tenant_state',
        ),
        migrations.RemoveIndex(
            model_name='soul',
            name='idx_soul_tenant_name',
        ),
        migrations.AddField(
            model_name='soulrecord',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soul_records', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='soulrecord',
            name='civilization',
            field=models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat')], default='CHINESE', help_text="Derived from soul's tenant (kept for query convenience)", max_length=20),
        ),
    ]
