# Generated by Django 5.2.14 on 2026-05-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0008_soulrecord_tenant_and_indexes'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='soul',
            name='idx_soul_tenant_state',
        ),
        migrations.RemoveIndex(
            model_name='soul',
            name='idx_soul_tenant_created',
        ),
        migrations.RemoveIndex(
            model_name='soul',
            name='idx_soul_tenant_merit',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='idx_soulrec_soul_recorded',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='idx_soulrec_tenant_type',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='idx_sr_tenant_soul',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='idx_sr_soul_type',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='idx_sr_tenant_date',
        ),
        migrations.AlterField(
            model_name='soulrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soul_records', to='tenants.tenant'),
        ),
    ]
