# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0009_add_approval_workflow_models'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soul',
            index=models.Index(fields=['tenant', 'current_state'], name='souls_soul_tenant__8de199_idx'),
        ),
        migrations.AddIndex(
            model_name='soul',
            index=models.Index(fields=['current_state'], name='souls_soul_current_a9f47a_idx'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['soul', 'record_type'], name='souls_soulr_soul_id_922eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['soul', 'category'], name='souls_soulr_soul_id_4df3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['tenant', 'recorded_at'], name='souls_soulr_tenant__429fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['record_type'], name='souls_soulr_record__aa5d06_idx'),
        ),
    ]
