# Generated by Django 5.2.14 on 2026-05-10 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0011_soul_create_time_soul_create_user_soul_update_time_and_more'),
        ('tenants', '0004_notification_delete_reason_notification_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soul',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soul',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soul',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soul',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='soul',
            name='sort_code',
            field=models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists'),
        ),
        migrations.AddField(
            model_name='soul',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['tenant', 'record_type', 'recorded_at'], name='souls_soulr_tenant__602c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['tenant', 'category', 'recorded_at'], name='souls_soulr_tenant__257fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['is_milestone'], name='souls_soulr_is_mile_1f964c_idx'),
        ),
        # UniqueConstraint on identity_id removed - field does not exist on Soul model
    ]
