# Generated by Django 5.2.14 on 2026-05-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0012_soul_delete_reason_soul_deleted_at_soul_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='souls_soulr_soul_id_922eb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='souls_soulr_soul_id_4df3ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='souls_soulr_tenant__429fb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='souls_soulr_record__aa5d06_idx',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='souls_soulr_tenant__602c7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='souls_soulr_tenant__257fe6_idx',
        ),
        migrations.RemoveIndex(
            model_name='soulrecord',
            name='souls_soulr_is_mile_1f964c_idx',
        ),
    ]
