# Generated by Django 5.2.14 on 2026-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0013_remove_soulrecord_souls_soulr_soul_id_922eb1_idx_and_more'),
        ('tenants', '0006_notification_idx_notif_recip_read'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['soul', 'record_type'], name='idx_soulrecord_soul_type'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['soul', 'recorded_at'], name='idx_soulrecord_soul_date'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['tenant', 'recorded_at'], name='idx_soulrecord_tenant_date'),
        ),
    ]
