# Generated by Django 5.2.14 on 2026-05-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0014_soulrecord_idx_soulrecord_soul_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soul',
            options={'ordering': ['-create_time'], 'verbose_name': 'Soul', 'verbose_name_plural': 'Souls'},
        ),
        migrations.RemoveField(
            model_name='soul',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soul',
            name='updated_at',
        ),
    ]
