# Generated by Django 5.2.14 on 2026-06-02 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0016_soulrecord_create_time_soulrecord_create_user_and_more'),
        ('tenants', '0006_notification_idx_notif_recip_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['record_type'], name='idx_soulrecord_type'),
        ),
        migrations.AddIndex(
            model_name='soulrecord',
            index=models.Index(fields=['civilization'], name='idx_soulrecord_civ'),
        ),
    ]
