# Generated by Django 5.2.16 on 2026-08-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0021_remove_legacy_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soul',
            name='current_state',
            field=models.CharField(choices=[('ALIVE', 'Alive'), ('JUDGING', 'Under Judgment'), ('DISPOSED', 'Disposed'), ('REINCARNATING', 'Reincarnating'), ('SETTLED', 'Settled (Final)'), ('LOST', 'Lost/Suspended')], default='ALIVE', max_length=20),
        ),
    ]
