# Generated by Django 5.2.16 on 2026-08-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0023_settle_terminal_cosmology_souls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="soulrecord",
            name="date_warning_ack_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of (event_date, soul.death_date) at acknowledgment time — see apps.souls.dates.date_warning_fingerprint. If either date has since changed, this no longer matches the live fingerprint: the acknowledgment stops applying and the warning reappears. Not cleared automatically — see the acknowledge endpoint's docstring for why.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="date_warning_acknowledged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the event_after_death warning was acknowledged.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="date_warning_acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who acknowledged this record's event_after_death warning, if anyone. Always set from the acknowledging request's authenticated user, never from client-supplied data.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_soul_record_date_warnings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
