# Generated by Django 5.2.16 on 2026-08-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0025_soul_archive_reason_soul_archived_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soulrecord",
            name="is_milestone",
            field=models.BooleanField(
                default=False,
                help_text="Marks a turning point in the life. Display only — the lifecycle timeline stars and tints it. It does NOT change the deed's weight.",
            ),
        ),
    ]
