# Generated by Django 5.2.16 on 2026-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0026_alter_soulrecord_is_milestone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soulrecord",
            name="civilization",
            field=models.CharField(
                choices=[
                    ("CHINESE", "Chinese Diyu"),
                    ("EUROPEAN", "European Heaven/Hell"),
                    ("EGYPTIAN", "Egyptian Duat"),
                    ("GREEK", "Greek Underworld"),
                ],
                default="CHINESE",
                help_text="Derived from soul's tenant (kept for query convenience)",
                max_length=20,
            ),
        ),
    ]
