"""The two inputs 零積不抵整發 needs, added under the names that named them.

《太微仙君功過格·凡例》's second sentence — 「零積之十功不能折一次之十過也」 —
is the half of the 凡例 that `apps/ledger/fungibility.py` implements the first
half of and could not implement at all. Its `GRANULARITY_MISSING_INPUTS` names
exactly two columns as what a `SoulRecord` would have to carry first, and these
are those two, under those names.

ADDITIVE AND NULLABLE, WITH NO BACKFILL. Every existing row gets `""` and
`NULL`, which the offset rule reads as granularity-unknown and nets exactly as
it did before this migration. That is not caution, it is the finding: the same
module refused four proxies for granularity — record counts, `is_milestone`, a
tag backfilled onto the 73 transcribed segments, and the corpus's own silence —
each with evidence. A data migration inventing values here would be the fifth,
and it would be the worst of them because it would be invisible afterwards.

Reversible, and the reverse is honest: dropping the columns loses whatever an
operator entered, which is what dropping a column means. Nothing else depends
on them — `offset_within_classes` treats an absent value and an absent column
identically, so a reversed database gets the pre-migration reading rather than
an error.
"""
# Generated by Django 5.2.16 on 2026-08-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0027_alter_soulrecord_civilization"),
    ]

    operations = [
        migrations.AddField(
            model_name="soulrecord",
            name="occurrence_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many separate occasions this row's weight covers. NOT a row count: one row may document a year of alms or three rows one killing. 1 means 一次 — earned or incurred at a stroke. Null means unknown, which makes this record granularity-blind.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="statute_clause",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which scoring clause this deed was scored under, as '<Statute.code>:<clause condition_zh>' — e.g. '救濟門#7:賑濟窮民百錢'. Blank means unknown, which makes this record granularity-blind.",
                max_length=200,
            ),
        ),
    ]
