"""Sin KIND, so Dante's Hell can stop being sorted by quantity.

`_route_european` picked a circle from a culpa total. Its own docstring §3 said
why that was a stopgap and could not be replaced: Virgil states the basis at
Inf. XI.79-84 as Aristotle's tripartition, and nothing in this system recorded a
kind. `tests/test_european_hell_basis.py` pinned the contradiction that produced
— violence and fraud of equal weight landing in the same circle, and a petty
fraud sorted into Limbo, which is not a punishment at all.

THREE COLUMNS, AND ONLY ONE OF THEM IS ON A DEED.

`SoulRecord.inferno_article` cites the seeded `EU-INF-*` corpus rather than
naming a category. That corpus is 26 articles — nine circles and seventeen
subdivisions — each carrying its circle, its kind (girone/bolgia/zona), its
canto range and the Aristotelian heading Virgil gives it. Citing
`EU-INF-C9-Z1` says "Caina", which IS "treachery to kin", so the four zones of
Cocytus arrive as citations rather than as a trust-relationship taxonomy
somebody drafted. docs/lore-verification/README.md §1 calls completing the
missing categories "the one repair that is certainly wrong"; a citation cannot
make that mistake, because an article either exists or the write is refused.

`Soul.baptism` and `Soul.denied_immortality` exist because two circles are not
about anything a soul DID, and the corpus says so itself by carrying
`aristotle: None` for both. Limbo holds virtuous pagans and the unbaptised;
heresy is a belief. On a record they would let two deeds of one soul disagree
about whether that soul was baptised.

NO BACKFILL, and the defaults are the honest ones. Every existing record is
unclassified, every existing soul is UNRECORDED and null. Inferring baptism from
a death date would be inventing a baptismal record from a calendar, and
inferring a circle from a `RecordCategory` member would be the mapping this
whole corpus exists to avoid — that vocabulary is Chinese, mapped onto 功過格
gates, with no member for five of the nine circles.

Reversible. Dropping the columns loses whatever an operator recorded and returns
the router to the culpa ladder, which is what it did before.
"""
# Generated by Django 5.2.16 on 2026-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0028_add_soul_record_granularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="baptism",
            field=models.CharField(
                choices=[
                    ("UNRECORDED", "未记录"),
                    ("BAPTISED", "已受洗"),
                    ("UNBAPTISED", "未受洗"),
                    ("BEFORE_CHRIST", "生于基督之前"),
                ],
                default="UNRECORDED",
                help_text="Whether this soul was baptised. Limbo (Inf. IV) is the only circle this reaches, and it is not a punishment — Virgil is there. UNRECORDED means nobody asked, which is every row written before this column existed.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="soul",
            name="denied_immortality",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether this soul held, in life, that the spirit dies with the body (Inf. X.13-15) — the specific claim Dante's sixth circle punishes. NOT a general heresy flag, and not blasphemy, which is Inf. XIV. Null means unrecorded.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="inferno_article",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which Inferno article this deed belongs under, as a Statute code in the EU-INF-* corpus — e.g. 'EU-INF-C7-G1' (seventh circle, first girone) or 'EU-INF-C9-Z1' (Caina). Blank means unclassified, which leaves the European router on its culpa ladder for this deed.",
                max_length=32,
            ),
        ),
    ]
