# Generated by Django 5.2.16 on 2026-08-30 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0029_add_inferno_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soulrecord',
            name='weight',
            field=models.IntegerField(default=1, help_text='Significance weight (1-100). Affects karma calculation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
