# Generated by Django 5.2.16 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0031_backfill_soulrecord_civilization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soulrecord',
            name='civilization',
            field=models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat'), ('GREEK', 'Greek Underworld')], default='CHINESE', help_text="Derived from the soul's tenant on save (kept for query convenience). Not authoritative: routing and the ledger read `soul.civilization`, the property. This column exists so a report can filter records without joining Soul.", max_length=20),
        ),
    ]
