# Generated by Django 5.2.16 on 2026-08-31 06:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souls', '0032_soulrecord_civilization_help_text'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='soul',
            name='demerit_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='soul',
            name='merit_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='soul',
            constraint=models.CheckConstraint(condition=models.Q(('merit_score__gte', 0)), name='soul_merit_score_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='soul',
            constraint=models.CheckConstraint(condition=models.Q(('demerit_score__gte', 0)), name='soul_demerit_score_not_negative'),
        ),
    ]
