# Generated by Django 5.2.16 on 2026-09-12 14:44, then given a backfill.
#
# The ledger is per life from here on: SoulRecord.cycle says which life a deed
# belongs to and Soul.inherited_merit/demerit is what the previous life handed
# down, so a recalculation is `inherited + this life's records` instead of
# `every record the soul ever had` -- which is how a rebirth's 20% carry-over
# used to be overwritten by the first deed written after it (BD-04).
#
# BACKFILL: every existing record goes to the life its soul is in NOW
# (reincarnations.count()), and inherited_* stays 0 for everyone.
#
# Not "everything to life 0". A soul that has already been reborn would then
# have all of its records in a life that is not its current one, and the next
# recalculation would set its score to 0 + nothing. Not a split by timestamp
# either: reincarnated_at vs recorded_at could sort the rows, but the inherited
# base for each life would still be unknowable and the scores would change on
# migration day in ways nobody asked for.
#
# Assigning to the current life is the one choice under which
# `recalculate_soul_ledger` produces, for every soul, exactly the number it
# produced the day before: 0 + (all records) == (all records). Which lives the
# old rows really belonged to is information the schema never recorded; this
# migration does not invent it, it preserves today's totals and fixes what
# happens from the next rebirth on.
#
# ORM only, so it runs the same on SQLite and PostgreSQL. `_base_manager`
# rather than `objects`: soft-deleted souls and records are stamped too, so a
# restore from the recycle bin does not bring back a row filed under life 0
# of a soul in life 3.

import django.core.validators
from django.db import migrations, models
from django.db.models import Count


def stamp_existing_records_with_the_current_life(apps, schema_editor):
    Soul = apps.get_model("souls", "Soul")
    SoulRecord = apps.get_model("souls", "SoulRecord")
    reborn = (
        Soul._base_manager.annotate(n=Count("reincarnations")).filter(n__gt=0)
        .values_list("pk", "n")
    )
    for soul_pk, n in reborn:
        SoulRecord._base_manager.filter(soul_id=soul_pk).update(cycle=n)


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0033_arithmetic_fields_get_bounds"),
        # The backfill counts `reincarnations`; the reverse relation only
        # exists in the migration state once that app's models are in it.
        ("reincarnation", "0013_arithmetic_fields_get_bounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="inherited_demerit",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="soul",
            name="inherited_merit",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="cycle",
            field=models.PositiveIntegerField(default=0, help_text="Life index this record belongs to; 0 is the first life."),
        ),
        migrations.RunPython(
            stamp_existing_records_with_the_current_life,
            # Dropping the column loses the stamp; there is nothing to undo.
            migrations.RunPython.noop,
        ),
    ]
