# Generated by Django 5.2.17 on 2026-09-16 19:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0034_ledger_is_per_life"),
        ("tenants", "0010_drop_dead_notification_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="soul",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[1-9]\\d{6,14}$", "手机号须为 7-15 位数字,可带 + 前缀"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="soul",
            name="soul_code",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="灵魂编号:灵魂端登录名,首次开通账号时分配,之后不变。",
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="soulrecord",
            index=models.Index(
                fields=["soul", "cycle"], name="idx_soulrecord_soul_cycle"
            ),
        ),
    ]
