# Generated by Django 5.2.17 on 2026-10-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0033_case_number_unique_statute_effective_required"),
        ("souls", "0036_soul_home_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="soulrecord",
            name="evidence_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free text about the source, e.g. which witness or which register.",
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="evidence_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGISTRY", "Registry"),
                    ("WITNESS", "Witness"),
                    ("SELF_ACCOUNT", "Self account"),
                    ("OTHER", "Other"),
                ],
                default="",
                help_text="Where this record came from; blank = unrecorded.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="life_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHILDHOOD", "Childhood"),
                    ("YOUTH", "Youth"),
                    ("ADULTHOOD", "Adulthood"),
                    ("OLD_AGE", "Old age"),
                ],
                default="",
                help_text="Which stage of the life the deed falls in; blank = unrecorded.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="statute",
            field=models.ForeignKey(
                blank=True,
                help_text="Article this deed is filed under. Must share the soul's civilization.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="soul_records",
                to="judgment.statute",
            ),
        ),
        migrations.AddField(
            model_name="soulrecord",
            name="statute_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="The cited article as it read when cited: statute_id, code, revision, effective_from, title/text per locale, source, hash, at. Taken by save(); never updated when the article changes.",
                null=True,
            ),
        ),
    ]
