# Generated by Django 5.2.17 on 2026-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0038_soul_import_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="needs_ledger_recalculation",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
