# Generated by Django 5.2.16 on 2026-08-29 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_comment_delete_cascade_id_follow_delete_cascade_id_and_more'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow_relationship',
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_per_post',
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_per_comment',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('follower', 'following'), name='unique_follow_relationship'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('post__isnull', False)), fields=('user', 'post'), name='unique_reaction_per_post'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False), ('is_deleted', False)), fields=('user', 'comment'), name='unique_reaction_per_comment'),
        ),
    ]
