# Generated by Django 5.2.17 on 2026-09-14 01:28
"""Drop `UserProfile.avatar_url` — avatars are uploaded to this site only.

The column held free-text links to other hosts. Production CSP is
`img-src 'self' data:`, so none of them ever rendered there; the avatar is now
`User.avatar`, written by `POST /api/v1/social/profiles/me/avatar/`.

The values are discarded, not converted: fetching arbitrary URLs server-side
during a migration would be an SSRF-shaped download of whatever users typed.
Discarded LOUDLY — the first operation prints how many non-empty values are
about to go, so the number is in the deploy log rather than nowhere. Count them
before migrating a database whose data matters:

    UserProfile.objects.exclude(avatar_url="").count()

Reverse re-adds the column empty; the links do not come back.
"""

from django.db import migrations


def report_discarded_links(apps, schema_editor):
    UserProfile = apps.get_model("social", "UserProfile")
    n = UserProfile.objects.exclude(avatar_url="").count()
    if n:
        print(f"\n  social.0005: discarding {n} external avatar_url value(s); users re-upload.")


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_follow_unique_follow_relationship_and_more'),
    ]

    operations = [
        migrations.RunPython(report_discarded_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
    ]
