# Generated by Django 5.2.17 on 2026-09-18 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_userprofile_avatar_url'),
        ('tenants', '0010_drop_dead_notification_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('PENDING', 'Pending review'), ('HIDDEN', 'Hidden')], db_index=True, default='PUBLISHED', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('PENDING', 'Pending review'), ('HIDDEN', 'Hidden')], db_index=True, default='PUBLISHED', max_length=10),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment'), ('USER', 'User')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.CharField(blank=True, choices=[('HIDE', 'Hide content'), ('DELETE', 'Delete content'), ('MUTE', 'Mute author'), ('DISMISS', 'Dismiss')], default='', max_length=10)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.post')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_reports_against', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-last_reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('ABUSE', 'Abuse'), ('SEXUAL', 'Sexual content'), ('ILLEGAL', 'Illegal or harmful'), ('OTHER', 'Other')], max_length=10)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='social.report')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_report_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_sensitive_words', to='tenants.tenant')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='SocialMute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('until', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_mutes', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'status', 'last_reported_at'], name='social_repo_tenant__595486_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN'), ('target_type', 'POST')), fields=('post',), name='social_report_one_open_per_post'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN'), ('target_type', 'COMMENT')), fields=('comment',), name='social_report_one_open_per_comment'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN'), ('target_type', 'USER')), fields=('target_user',), name='social_report_one_open_per_user'),
        ),
        migrations.AddIndex(
            model_name='reportentry',
            index=models.Index(fields=['reporter', 'created_at'], name='social_repo_reporte_f465ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportentry',
            constraint=models.UniqueConstraint(fields=('report', 'reporter'), name='social_report_entry_once_per_reporter'),
        ),
        migrations.AddConstraint(
            model_name='sensitiveword',
            constraint=models.UniqueConstraint(fields=('tenant', 'word'), name='social_sensitive_word_unique_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='socialmute',
            index=models.Index(fields=['user', 'until'], name='social_soci_user_id_798c56_idx'),
        ),
    ]
