# Generated by Django 5.2.17 on 2026-09-24 14:49
#
# 朋友圈审核三区的后端(feat/moderation-backend)。只有 AddField / CreateModel,
# Django 自动可逆(`migrate social 0006` 即回退),不读不写任何既有行:
#
# * SensitiveWord.action 默认 REVIEW —— 迁移前每个词都是「命中进待审」,行为不变;
# * SensitiveWord.category 默认 "" —— 未分类,由官员补;
# * Post / Comment 的 moderated_by / moderated_at 可空、moderation_reason 默认 "";
#   迁移前已隐藏的行这三项为空,「已处理」列表照样列出它们(处理人 / 时间显示为空);
# * SensitiveWordDailyHit 是新表,空的:近 30 天命中从迁移那一刻开始计。

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_soul_circle_moderation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="moderation_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="moderation_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="sensitiveword",
            name="action",
            field=models.CharField(
                choices=[
                    ("REVIEW", "Send to review"),
                    ("HIDE", "Hide"),
                    ("MASK", "Mask with ***"),
                ],
                default="REVIEW",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sensitiveword",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVACY", "Privacy"),
                    ("ABUSE", "Abuse"),
                    ("INDUCEMENT", "Boundary-crossing inducement"),
                    ("CONFIDENTIAL", "Confidential"),
                    ("OFFICIAL_DEFAMATION", "Defaming officials"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SensitiveWordDailyHit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_hits",
                        to="social.sensitiveword",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("word", "day"),
                        name="social_sensitive_word_hit_one_row_per_day",
                    )
                ],
            },
        ),
    ]
