# Generated by Django 5.2.17 on 2026-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_moderation_word_action_and_handled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HIDE", "Hide content"),
                    ("DELETE", "Delete content"),
                    ("MUTE", "Mute author"),
                    ("DISMISS", "Dismiss"),
                    ("WARN", "Warn author"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
