# Generated by Django 5.2.17 on 2026-09-16 19:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.death_sync.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("souls", "0035_soul_code_and_contacts"),
        ("workflow", "0017_rebirth_application_case_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoulAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cycle",
                    models.PositiveIntegerField(
                        help_text="这个账号属于第几世;0 是第一世。"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("DEATH_SYNC", "死亡同步自动开通"),
                            ("OFFICER", "官员手动开通"),
                            ("BACKFILL", "存量补齐"),
                        ],
                        max_length=20,
                    ),
                ),
                ("must_change_password", models.BooleanField(default=True)),
                (
                    "initial_password_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_account",
                        to="soul_accounts.soulaccount",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="souls.soul",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soul_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["soul", "cycle"],
            },
        ),
        migrations.CreateModel(
            name="RebirthApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cycle", models.PositiveIntegerField()),
                (
                    "desired_form",
                    models.CharField(
                        choices=[
                            ("DIVINE", "Deva (Heaven Path)"),
                            ("HUMAN", "Human (Human Path)"),
                            ("ASURA", "Asura (Demigod Path)"),
                            ("ANIMAL", "Animal (Beast Path)"),
                            ("HUNGRY_GHOST", "Hungry Ghost"),
                            ("HELL_BEING", "Hell Being"),
                            ("OTHER", "Other (Unclassified)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statement",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                (
                    "appeal_statement",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDER_REVIEW", "审批中"),
                            ("REJECTED", "已驳回"),
                            ("APPEALING", "申诉中"),
                            ("APPEAL_REJECTED", "申诉被驳回"),
                            ("APPROVED", "已批准"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cross_civilization", models.BooleanField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appeal_workflow",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebirth_appeal",
                        to="workflow.approvalworkflow",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebirth_applications",
                        to="souls.soul",
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebirth_application",
                        to="workflow.approvalworkflow",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebirth_applications",
                        to="soul_accounts.soulaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InitialCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="EMAIL / SMS;空表示没有可用渠道",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "待发送"),
                            ("SENT", "已发送"),
                            ("PENDING", "待交付"),
                            ("REVEALED", "已查看"),
                            ("DELIVERED", "已线下交付"),
                            ("VOID", "已作废"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "secret",
                    apps.death_sync.fields.EncryptedCharField(
                        blank=True, default="", max_length=512
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revealed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_credentials",
                        to="souls.soul",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="soul_accounts.soulaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="soulaccount",
            constraint=models.UniqueConstraint(
                fields=("soul", "cycle"), name="soul_account_one_per_life"
            ),
        ),
        migrations.AddConstraint(
            model_name="soulaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retired_at__isnull", True)),
                fields=("soul",),
                name="soul_account_one_current",
            ),
        ),
        migrations.AddIndex(
            model_name="rebirthapplication",
            index=models.Index(
                fields=["soul", "cycle"], name="soul_accoun_soul_id_7382bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rebirthapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["UNDER_REVIEW", "APPEALING"])),
                fields=("soul",),
                name="rebirth_application_one_open_per_soul",
            ),
        ),
        migrations.AddIndex(
            model_name="initialcredential",
            index=models.Index(
                fields=["status", "created_at"], name="soul_accoun_status_15a22e_idx"
            ),
        ),
    ]
