# Generated by Django 5.2.17 on 2026-09-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soul_accounts', '0003_sync_contact_email_to_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulaccount',
            name='welcomed_civilizations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
