# Generated by Django 5.2.17 on 2026-10-08 03:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soul_accounts", "0004_soulaccount_welcomed_civilizations"),
        ("souls", "0036_soul_home_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CooldownShorteningRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cycle", models.PositiveIntegerField()),
                ("reason", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待决定"),
                            ("APPROVED", "已批准"),
                            ("REJECTED", "已驳回"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "approved_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="批准后,自决定时刻起还要等的天数。",
                        null=True,
                    ),
                ),
                (
                    "decision_note",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cooldown_shortenings",
                        to="soul_accounts.soulaccount",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        help_text="其终局驳回引起这段冷却的那份申请。",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cooldown_shortening",
                        to="soul_accounts.rebirthapplication",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooldown_shortenings",
                        to="souls.soul",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("soul",),
                        name="cooldown_shortening_one_pending_per_soul",
                    )
                ],
            },
        ),
    ]
