# Generated by Django 5.2.17 on 2026-10-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soul_accounts", "0005_cooldown_shortening"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooldownshorteningrequest",
            name="desired_remaining_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="灵魂希望批准后还剩几天(0 = 立即结束);可选,仅供官员参考。",
                null=True,
            ),
        ),
    ]
