# Generated by Django 5.2.14 on 2026-05-13 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('WORKFLOW_ASSIGNED', 'Workflow Assigned'), ('JUDGMENT_COMPLETED', 'Judgment Completed'), ('SYSTEM', 'System Notification'), ('APPEAL_REQUIRED', 'Appeal Required'), ('REINCARNATION_COMPLETE', 'Reincarnation Complete'), ('KARMIC_UPDATE', 'Karmic Update'), ('ROLE_ASSIGNED', 'Role Assigned')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_resource', models.CharField(blank=True, help_text="e.g., 'workflow', 'judgment', 'soul'", max_length=50, null=True)),
                ('related_id', models.CharField(blank=True, help_text='UUID of related resource', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_ce6926_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_6987c7_idx')],
            },
        ),
    ]
