# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotification_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usernotification',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
