# Generated by Django 5.2.16 on 2026-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_usernotification_delete_cascade_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("WORKFLOW_ASSIGNED", "Workflow Assigned"),
                    ("JUDGMENT_COMPLETED", "Judgment Completed"),
                    ("SYSTEM", "System Notification"),
                    ("APPEAL_REQUIRED", "Appeal Required"),
                    ("REINCARNATION_COMPLETE", "Reincarnation Complete"),
                    ("KARMIC_UPDATE", "Karmic Update"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("DISPATCH_PROPOSED", "Dispatch Proposed"),
                    ("DISPATCH_APPROVED", "Dispatch Approved"),
                    ("DISPATCH_REJECTED", "Dispatch Rejected"),
                    ("CROSS_JUDGMENT_INVITED", "Cross-Tenant Judgment Invitation"),
                    ("JUDGMENT_CONCLUDED", "Judgment Concluded"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
    ]
