# Generated by Django 5.2.17 on 2026-09-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('WORKFLOW_ASSIGNED', 'Workflow Assigned'), ('JUDGMENT_COMPLETED', 'Judgment Completed'), ('SYSTEM', 'System Notification'), ('APPEAL_REQUIRED', 'Appeal Required'), ('REINCARNATION_COMPLETE', 'Reincarnation Complete'), ('KARMIC_UPDATE', 'Karmic Update'), ('ROLE_ASSIGNED', 'Role Assigned'), ('DISPATCH_PROPOSED', 'Dispatch Proposed'), ('DISPATCH_APPROVED', 'Dispatch Approved'), ('DISPATCH_REJECTED', 'Dispatch Rejected'), ('CROSS_JUDGMENT_INVITED', 'Cross-Tenant Judgment Invitation'), ('JUDGMENT_CONCLUDED', 'Judgment Concluded'), ('DISPATCH_RETURN_BLOCKED', 'Dispatch Return Blocked')], default='SYSTEM', max_length=30),
        ),
    ]
