# Generated by Django 5.2.17 on 2026-09-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_usernotification_params_return_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("WORKFLOW_ASSIGNED", "Workflow Assigned"),
                    ("JUDGMENT_COMPLETED", "Judgment Completed"),
                    ("SYSTEM", "System Notification"),
                    ("APPEAL_REQUIRED", "Appeal Required"),
                    ("REINCARNATION_COMPLETE", "Reincarnation Complete"),
                    ("KARMIC_UPDATE", "Karmic Update"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("DISPATCH_PROPOSED", "Dispatch Proposed"),
                    ("DISPATCH_APPROVED", "Dispatch Approved"),
                    ("DISPATCH_REJECTED", "Dispatch Rejected"),
                    ("CROSS_JUDGMENT_INVITED", "Cross-Tenant Judgment Invitation"),
                    ("JUDGMENT_CONCLUDED", "Judgment Concluded"),
                    ("DISPATCH_RETURN_BLOCKED", "Dispatch Return Blocked"),
                    ("SENTENCE_NODE_ACTIVE", "Sentence Node Active"),
                    ("SENTENCE_NODE_DONE", "Sentence Node Done"),
                    ("SENTENCE_NODE_WAITING", "Sentence Node Waiting"),
                    ("SENTENCE_NODE_REFUSED", "Sentence Node Refused"),
                    ("SENTENCE_PLAN_COMPLETED", "Sentence Plan Completed"),
                    ("CROSS_SENTENCE_SUBMITTED", "Cross Sentence Submitted"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
    ]
