# Generated by Django 5.2.14 on 2026-06-03 05:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgment', '0008_judgment_delete_reason_judgment_deleted_at_and_more'),
        ('souls', '0017_soulrecord_idx_soulrecord_type_and_more'),
        ('tenants', '0006_notification_idx_notif_recip_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiKey',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Municipal Hospital Death Registry'", max_length=200)),
                ('system_type', models.CharField(choices=[('GOVERNMENT', 'Government Civil Registry'), ('HOSPITAL', 'Hospital Death Certificate System'), ('POLICE', 'Police Household Registration'), ('MESSAGE_BUS', 'Message Bus Integration'), ('CUSTOM', 'Custom Integration')], max_length=30)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw API key', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 chars of key for display/identification', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_hour', models.IntegerField(default=1000)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed source IPs. Empty = allow all.')),
                ('allowed_sources', models.JSONField(blank=True, default=list, help_text='Source identifiers this key may use')),
                ('can_register_death', models.BooleanField(default=True)),
                ('can_query_status', models.BooleanField(default=True)),
                ('can_manage_webhooks', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.BigIntegerField(default=0)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_api_keys', to='tenants.tenant')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External API Key',
                'verbose_name_plural': 'External API Keys',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DeathRegistrationRequest',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Client-provided idempotency key (unique per source system)', max_length=200)),
                ('source_system', models.CharField(help_text='Identifier of the source system', max_length=50)),
                ('source_reference_id', models.CharField(blank=True, help_text='Reference ID from source system', max_length=200)),
                ('source_payload', models.JSONField(help_text='Original request payload')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('ACCEPTED', 'Accepted - Processing'), ('PROCESSED', 'Processed Successfully'), ('FAILED', 'Processing Failed'), ('DUPLICATE', 'Duplicate - Already Processed'), ('PARTIAL', 'Partially Processed (batch)')], default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('webhook_delivered', models.BooleanField(default=False)),
                ('source_ip', models.GenericIPAddressField(null=True)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_duration_ms', models.IntegerField(null=True)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('judgment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_registrations', to='judgment.judgment')),
                ('soul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_registrations', to='souls.soul')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_registrations', to='tenants.tenant')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='death_sync.externalapikey')),
            ],
            options={
                'verbose_name': 'Death Registration Request',
                'verbose_name_plural': 'Death Registration Requests',
                'ordering': ['-request_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Webhook callback URL (must be HTTPS in production)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('events', models.JSONField(default=list, help_text='Event types to subscribe to. Empty = all events.')),
                ('signing_secret', models.CharField(help_text='HMAC-SHA256 signing secret for payload verification', max_length=64)),
                ('max_retries', models.IntegerField(default=5)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='death_sync.externalapikey')),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_configs', to='tenants.tenant')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'verbose_name_plural': 'Webhook Configs',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('attempt', models.IntegerField(default=1)),
                ('http_status_code', models.IntegerField(null=True)),
                ('request_body', models.JSONField(default=dict)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='death_sync.deathregistrationrequest')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='death_sync.webhookconfig')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Log',
                'verbose_name_plural': 'Webhook Delivery Logs',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='externalapikey',
            index=models.Index(fields=['tenant', 'is_active'], name='death_sync__tenant__b53d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='externalapikey',
            index=models.Index(fields=['key_hash'], name='death_sync__key_has_91da3f_idx'),
        ),
        migrations.AddIndex(
            model_name='deathregistrationrequest',
            index=models.Index(fields=['tenant', 'status'], name='death_sync__tenant__c94cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='deathregistrationrequest',
            index=models.Index(fields=['source_system', 'idempotency_key'], name='death_sync__source__e7e0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='deathregistrationrequest',
            index=models.Index(fields=['status', 'request_timestamp'], name='death_sync__status_1c85fa_idx'),
        ),
        migrations.AddIndex(
            model_name='deathregistrationrequest',
            index=models.Index(fields=['soul'], name='death_sync__soul_id_e20aad_idx'),
        ),
        migrations.AddConstraint(
            model_name='deathregistrationrequest',
            constraint=models.UniqueConstraint(fields=('source_system', 'idempotency_key'), name='uniq_death_reg_idempotency'),
        ),
        migrations.AddIndex(
            model_name='webhookconfig',
            index=models.Index(fields=['tenant', 'is_active'], name='death_sync__tenant__ce6543_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['webhook', 'status'], name='death_sync__webhook_5379ac_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['registration'], name='death_sync__registr_01fc59_idx'),
        ),
    ]
