# Generated by Django 5.2.14 on 2026-06-04 04:44

import apps.death_sync.encrypted_json
import apps.death_sync.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathregistrationrequest',
            name='source_payload',
            field=apps.death_sync.encrypted_json.EncryptedJSONField(help_text='Original request payload (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='signing_secret',
            field=apps.death_sync.fields.EncryptedCharField(help_text='HMAC-SHA256 signing secret for payload verification', max_length=500),
        ),
    ]
