# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_sync', '0002_alter_deathregistrationrequest_source_payload_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deathregistrationrequest',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externalapikey',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='webhookconfig',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='webhookdeliverylog',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
