# Generated by Django 5.2.16 on 2026-08-29 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death_sync', '0004_deathregistrationrequest_delete_cascade_id_and_more'),
        ('judgment', '0019_alter_statute_source'),
        ('souls', '0029_add_inferno_classification'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deathregistrationrequest',
            name='uniq_death_reg_idempotency',
        ),
        migrations.AddConstraint(
            model_name='deathregistrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('source_system', 'idempotency_key'), name='uniq_death_reg_idempotency'),
        ),
    ]
