# Generated by Django 5.2.16 on 2026-09-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_sync', '0005_remove_deathregistrationrequest_uniq_death_reg_idempotency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathregistrationrequest',
            name='webhook_delivered',
        ),
        migrations.DeleteModel(
            name='WebhookDeliveryLog',
        ),
    ]
