# Generated by Django 5.2.17 on 2026-10-09 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("death_sync", "0006_remove_orphan_webhook_delivery_pipeline"),
        ("judgment", "0033_case_number_unique_statute_effective_required"),
        ("souls", "0038_soul_import_batch"),
        ("tenants", "0015_tenant_dispatch_enabled_default_true"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deathregistrationrequest",
            name="uniq_death_reg_idempotency",
        ),
        migrations.RemoveIndex(
            model_name="deathregistrationrequest",
            name="death_sync__source__e7e0b0_idx",
        ),
        migrations.AddIndex(
            model_name="deathregistrationrequest",
            index=models.Index(
                fields=["tenant", "source_system", "idempotency_key"],
                name="death_sync__tenant__01480a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="deathregistrationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("tenant", "source_system", "idempotency_key"),
                name="uniq_death_reg_idempotency",
            ),
        ),
    ]
