# Generated by Django 5.2.14 on 2026-05-14 11:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0006_actor_delete_reason_actor_deleted_at_and_more'),
        ('souls', '0013_remove_soulrecord_souls_soulr_soul_id_922eb1_idx_and_more'),
        ('tenants', '0005_remove_notification_tenants_not_recipie_d638ec_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossTenantJudgment',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PROPOSED', '提议中'), ('ACTIVE', '进行中'), ('CONCLUDED', '已结束'), ('CANCELLED', '已取消')], default='PROPOSED', max_length=20)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('conclusion_type', models.CharField(blank=True, help_text='PASS or FAIL', max_length=20, null=True)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('initiating_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_judgments', to='tenants.tenant')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_tenant_judgments', to='tenants.tenant')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross-Tenant Judgment',
                'verbose_name_plural': 'Cross-Tenant Judgments',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CrossTenantJudgmentParticipant',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADVISOR', '顾问'), ('CO_JUDGE', '联合审判官'), ('CHAIRMAN', '主持')], default='ADVISOR', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('judgment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dispatch.crosstenantjudgment')),
                ('participant_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgment_participations', to='actors.actor')),
                ('participant_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgment_participations', to='tenants.tenant')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Judgment Participant',
                'verbose_name_plural': 'Judgment Participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROPOSED', '待审批'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('EXECUTED', '已执行'), ('CANCELLED', '已取消')], default='PROPOSED', max_length=20)),
                ('reason', models.TextField()),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_records', to=settings.AUTH_USER_MODEL)),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='souls.soul')),
                ('source_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records_sent', to='tenants.tenant')),
                ('target_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records_received', to='tenants.tenant')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='tenants.tenant')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch Record',
                'verbose_name_plural': 'Dispatch Records',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crosstenantjudgment',
            index=models.Index(fields=['initiating_tenant', 'status'], name='dispatch_cr_initiat_fb638e_idx'),
        ),
        migrations.AddIndex(
            model_name='crosstenantjudgment',
            index=models.Index(fields=['status'], name='dispatch_cr_status_2d57c1_idx'),
        ),
        migrations.AddIndex(
            model_name='crosstenantjudgmentparticipant',
            index=models.Index(fields=['judgment', 'participant_tenant'], name='dispatch_cr_judgmen_3c06fc_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchrecord',
            index=models.Index(fields=['source_tenant', 'status'], name='dispatch_di_source__c11c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchrecord',
            index=models.Index(fields=['target_tenant', 'status'], name='dispatch_di_target__490952_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchrecord',
            index=models.Index(fields=['soul'], name='dispatch_di_soul_id_0318a2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchrecord',
            index=models.Index(fields=['status'], name='dispatch_di_status_a3b604_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('soul',), name='unique_active_dispatch'),
        ),
    ]
