# Generated by Django 5.2.14 on 2026-05-14 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        ('souls', '0013_remove_soulrecord_souls_soulr_soul_id_922eb1_idx_and_more'),
        ('tenants', '0005_remove_notification_tenants_not_recipie_d638ec_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispatchrecord',
            name='unique_active_dispatch',
        ),
        migrations.AddConstraint(
            model_name='dispatchrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['PROPOSED', 'APPROVED'])), fields=('soul',), name='unique_active_dispatch'),
        ),
    ]
