# Generated by Django 5.2.14 on 2026-05-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_remove_dispatchrecord_unique_active_dispatch_and_more'),
        ('tenants', '0005_remove_notification_tenants_not_recipie_d638ec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosstenantjudgmentparticipant',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgment_participants', to='tenants.tenant'),
        ),
    ]
