# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_crosstenantjudgmentparticipant_tenant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crosstenantjudgment',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='crosstenantjudgmentparticipant',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dispatchrecord',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
