# Generated by Django 5.2.17 on 2026-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_crosstenantjudgment_delete_cascade_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='status',
            field=models.CharField(choices=[('PROPOSED', '待审批'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('EXECUTED', '已执行'), ('RETURNED', '已回归'), ('CANCELLED', '已取消')], default='PROPOSED', max_length=20),
        ),
    ]
