# Generated by Django 5.2.17 on 2026-09-18 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0012_retire_the_pantheon_the_corpus_does_not_name"),
        ("dispatch", "0006_dispatchrecord_returned"),
        ("judgment", "0022_judgment_kind_amends_plan_id"),
        ("tenants", "0010_drop_dead_notification_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crosstenantjudgment",
            name="judgment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cross_judgment",
                to="judgment.judgment",
            ),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="node_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="sentence_is_eternal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="sentence_memory_reset",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="sentence_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="sentence_realm_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="sentence_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="sentence_submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sentences_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crosstenantjudgmentparticipant",
            name="sentence_years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="crosstenantjudgmentparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), ("node_order__isnull", False)
                ),
                fields=("judgment", "node_order"),
                name="unique_cross_judgment_node_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="crosstenantjudgmentparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sentence_years__isnull", True),
                    ("sentence_years__gte", 0),
                    _connector="OR",
                ),
                name="cross_participant_sentence_years_not_negative",
            ),
        ),
    ]
