# Generated by Django 5.2.17 on 2026-09-25 02:45

import django.db.models.deletion
from django.db import migrations, models


def _drop_drafts(apps, schema_editor):
    """Reverse only. Before this migration a dispatch cannot be a draft: the
    status has no DRAFT member and `soul` / `target_tenant` are NOT NULL, so
    the AlterFields below cannot be reversed while a draft with an empty soul
    or target exists. Nor can a draft be carried back as anything else — as
    CANCELLED it would appear in both tenants' lists as a proposal that was
    made and withdrawn, which it never was. Drafts (discarded ones in the
    recycle bin included) are removed; every other row is untouched.
    """
    record = apps.get_model("dispatch", "DispatchRecord")
    record._base_manager.filter(status="DRAFT").delete()


class Migration(migrations.Migration):
    # Schema only going forward: existing rows keep their status and get
    # target_realm = NULL. No data is written.

    dependencies = [
        ("dispatch", "0007_cross_judgment_sentence_nodes"),
        ("realms", "0019_realm_topology_and_soul_path"),
        ("souls", "0036_soul_home_tenant"),
        ("tenants", "0012_default_hall_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchrecord",
            name="target_realm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatch_records",
                to="realms.realm",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchrecord",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="dispatchrecord",
            name="soul",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatch_records",
                to="souls.soul",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "草稿"),
                    ("PROPOSED", "待审批"),
                    ("APPROVED", "已批准"),
                    ("REJECTED", "已拒绝"),
                    ("EXECUTED", "已执行"),
                    ("RETURNED", "已回归"),
                    ("CANCELLED", "已取消"),
                ],
                default="PROPOSED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispatchrecord",
            name="target_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatch_records_received",
                to="tenants.tenant",
            ),
        ),
        # Last, so that on reverse it runs first — before the columns go back
        # to NOT NULL. See _drop_drafts.
        migrations.RunPython(migrations.RunPython.noop, _drop_drafts),
    ]
