# Generated by Django 5.2.14 on 2026-05-08 07:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('souls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('civilization', models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat')], max_length=20)),
                ('court', models.CharField(blank=True, help_text='Court name, e.g. 第一殿', max_length=255)),
                ('evidence_json', models.JSONField(default=dict)),
                ('confession', models.TextField(blank=True)),
                ('verdict', models.CharField(blank=True, choices=[('PASSED', 'Passed / Saved'), ('FAILED', 'Failed / Condemned'), ('PURGATORY', 'Purgatory / Intermediate'), ('RETRY', 'Retry / Appeal')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgments_conducted', to='actors.actor')),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='souls.soul')),
            ],
            options={
                'verbose_name': 'Judgment',
                'verbose_name_plural': 'Judgments',
                'ordering': ['-created_at'],
            },
        ),
    ]
