# Generated by Django 5.2.14 on 2026-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='judgment_method',
            field=models.CharField(choices=[('STANDARD', 'Standard Trial (Chinese/European)'), ('HEART_WEIGHING', 'Heart Weighing (Egyptian)'), ('DIABOLICAL_TRIAL', 'Diabolical Trial (European Hell)')], default='STANDARD', help_text='Method of judgment (affects disposition routing)', max_length=30),
        ),
    ]
