# Generated by Django 5.2.14 on 2026-05-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0002_judgment_judgment_method'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='tenants.tenant'),
        ),
    ]
