# Generated by Django 5.2.14 on 2026-05-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0004_judgment_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='judgment',
            name='idx_judgment_tenant_verdict',
        ),
        migrations.RemoveIndex(
            model_name='judgment',
            name='idx_judgment_soul_created',
        ),
    ]
