# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_actor_actors_acto_civiliz_1ecd7c_idx_and_more'),
        ('judgment', '0005_add_approval_workflow_models'),
        ('souls', '0009_add_approval_workflow_models'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='judgment',
            index=models.Index(fields=['soul', 'verdict'], name='judgment_ju_soul_id_7d4127_idx'),
        ),
        migrations.AddIndex(
            model_name='judgment',
            index=models.Index(fields=['tenant', 'created_at'], name='judgment_ju_tenant__26ded2_idx'),
        ),
        migrations.AddIndex(
            model_name='judgment',
            index=models.Index(fields=['verdict'], name='judgment_ju_verdict_7f446d_idx'),
        ),
        migrations.AddIndex(
            model_name='judgment',
            index=models.Index(fields=['is_final'], name='judgment_ju_is_fina_a2c30d_idx'),
        ),
    ]
