# Generated by Django 5.2.16 on 2026-08-14 11:53

import uuid

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0008_actor_delete_cascade_id"),
        ("judgment", "0010_judgment_archive_reason_judgment_archived_at_and_more"),
        ("tenants", "0008_notification_delete_cascade_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Statute",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=500)),
                (
                    "delete_cascade_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0, editable=False)),
                (
                    "sort_code",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Sort order for admin lists"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "civilization",
                    models.CharField(
                        choices=[
                            ("CHINESE", "Chinese Diyu"),
                            ("EUROPEAN", "European Heaven/Hell"),
                            ("EGYPTIAN", "Egyptian Duat"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "corpus",
                    models.CharField(
                        choices=[
                            ("HELL_LAW", "冥律 — Hell Law (Chinese)"),
                            (
                                "NEGATIVE_CONFESSION",
                                "Declaration of Innocence (Egyptian)",
                            ),
                            ("DEADLY_SIN", "Seven Deadly Sins (European)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable citation key, e.g. CN-HL-O01 / EG-NC-07 / EU-DS-03",
                        max_length=40,
                    ),
                ),
                ("ordinal", models.IntegerField(default=0)),
                (
                    "polarity",
                    models.CharField(
                        choices=[
                            ("OFFENCE", "Offence — counts against the soul"),
                            ("MERIT", "Merit — counts for the soul"),
                            ("DENIAL", "Denial the deceased must sustain"),
                        ],
                        default="OFFENCE",
                        max_length=10,
                    ),
                ),
                ("title_zh", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255)),
                ("title_egy", models.CharField(blank=True, max_length=255)),
                ("text_zh", models.TextField(blank=True)),
                ("text_en", models.TextField(blank=True)),
                ("text_egy", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=500)),
                ("source_notes", models.JSONField(blank=True, default=list)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("source_actor_field", models.CharField(blank=True, max_length=50)),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Derivation source; the article body is read from this row.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_statutes",
                        to="actors.actor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statutes",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Statute",
                "verbose_name_plural": "Statutes",
                "ordering": ["civilization", "corpus", "ordinal", "code"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="JudgmentCitation",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=500)),
                (
                    "delete_cascade_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0, editable=False)),
                (
                    "sort_code",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Sort order for admin lists"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="How this article applies to this case."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="judgment.judgment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judgment_citations",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citations",
                        to="judgment.statute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Judgment citation",
                "verbose_name_plural": "Judgment citations",
                "ordering": ["statute__corpus", "statute__ordinal", "created_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="statute",
            index=models.Index(
                fields=["tenant", "corpus"], name="judgment_st_tenant__d7f8c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statute",
            index=models.Index(
                fields=["civilization", "corpus", "ordinal"],
                name="judgment_st_civiliz_dfb16d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="statute",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_statute_tenant_code"
            ),
        ),
        migrations.AddIndex(
            model_name="judgmentcitation",
            index=models.Index(
                fields=["judgment"], name="judgment_ju_judgmen_8b2ab8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgmentcitation",
            index=models.Index(
                fields=["tenant", "created_at"], name="judgment_ju_tenant__309435_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="judgmentcitation",
            constraint=models.UniqueConstraint(
                fields=("judgment", "statute"), name="unique_citation_judgment_statute"
            ),
        ),
    ]
