# Generated by Django 5.2.16 on 2026-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0013_gongguoge_corpus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgment",
            name="civilization",
            field=models.CharField(
                choices=[
                    ("CHINESE", "Chinese Diyu"),
                    ("EUROPEAN", "European Heaven/Hell"),
                    ("EGYPTIAN", "Egyptian Duat"),
                    ("GREEK", "Greek Underworld"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statute",
            name="civilization",
            field=models.CharField(
                choices=[
                    ("CHINESE", "Chinese Diyu"),
                    ("EUROPEAN", "European Heaven/Hell"),
                    ("EGYPTIAN", "Egyptian Duat"),
                    ("GREEK", "Greek Underworld"),
                ],
                max_length=20,
            ),
        ),
    ]
