"""`STANDARD` said "(Chinese/European)" while handing itself to Greek souls.

A choices label, so this alters no data and no column — but the label is what a
serializer sends and a form renders, and it named two of the three civilizations
that actually take this method.

`Soul.die()`'s `method_map` had three members and a `.get(..., STANDARD)`
fallback, so every Greek soul has been recorded with a judgment method whose own
name excludes it since GREEK was added. The map now lists all four explicitly;
that changes no behaviour, only whether the value was decided.

STANDARD is the right method: Gorgias 524a is a trial. Three judges hear the
case at the fork and Minos decides when the other two are in doubt — a
proceeding, not a weighing (HEART_WEIGHING) and not a disputation
(DIABOLICAL_TRIAL).
"""
# Generated by Django 5.2.16 on 2026-08-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0015_inferno_corpus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgment",
            name="judgment_method",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard Trial (Chinese/European/Greek)"),
                    ("HEART_WEIGHING", "Heart Weighing (Egyptian)"),
                    ("DIABOLICAL_TRIAL", "Diabolical Trial (European Hell)"),
                ],
                default="STANDARD",
                help_text="Method of judgment (affects disposition routing)",
                max_length=30,
            ),
        ),
    ]
