# Generated by Django 5.2.16 on 2026-08-25 08:43
"""GREEK gets two corpora, and Statute gets a polarity that is neither side.

`corpus` gains GORGIAS and REPUBLIC_ER; `polarity` gains PROCEDURE. Both are
`choices` edits — no column changes width, no row is touched, and reversing
this migration restores the previous choice lists.

WHY IT IS TWO CORPORA AND NOT ONE. Gorgias and Republic X are both Plato and
both the judgement of the dead, and they describe different afterlives: one
stamps a soul and ends, the other sentences it to a thousand-year circuit and
sends it back to be born. Merged they would assert a terminal sentence and a
return at once. See StatuteCorpus, which makes the argument in full, and
statutes_republic.py, which makes it against the European precedent that
established the rule.

WHY PROCEDURE HAD TO EXIST. OFFENCE, MERIT and DENIAL all answer "which way
does citing this cut". Twenty of the twenty-two Greek articles answer neither,
because neither Platonic myth contains a code of offences — they contain a
court. "The judge too shall be naked, that is to say, dead" is a rule the bench
is bound by and a claim about no soul at all.

REVERSIBILITY IS REAL BUT NOT FREE, and it is the same caveat StatuteCorpus
records for the withdrawn HELL_LAW rows. Reversing this restores the old choice
lists; it does not delete the 22 seeded Greek rows, and a stored value that has
left the enum no longer renders, no longer validates and no longer reverses. If
these corpora are ever withdrawn, withdraw the ROWS in their own data migration
first — the way judgment/0012 retired the fabricated 冥律 articles — and leave
the enum members standing.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0016_widen_standard_trial_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statute",
            name="corpus",
            field=models.CharField(
                choices=[
                    ("HELL_LAW", "冥律 — Hell Law (Chinese)"),
                    ("GONGGUOGE", "功過格 — Ledger of Merit and Demerit (Chinese)"),
                    ("NEGATIVE_CONFESSION", "Declaration of Innocence (Egyptian)"),
                    ("DEADLY_SIN", "Seven Deadly Sins (European)"),
                    ("INFERNO", "Inferno — the Circles of Dante's Hell (European)"),
                    ("GORGIAS", "Gorgias — the Judgement of the Dead (Greek)"),
                    ("REPUBLIC_ER", "Republic X — the Myth of Er (Greek)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="statute",
            name="polarity",
            field=models.CharField(
                choices=[
                    ("OFFENCE", "Offence — counts against the soul"),
                    ("MERIT", "Merit — counts for the soul"),
                    ("DENIAL", "Denial the deceased must sustain"),
                    ("PROCEDURE", "Rule of the court — neither for nor against"),
                ],
                default="OFFENCE",
                max_length=10,
            ),
        ),
    ]
