# Generated by Django 5.2.16 on 2026-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0018_split_bugui_gate_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statute",
            name="source",
            field=models.TextField(blank=True),
        ),
    ]
