# Generated by Django 5.2.16 on 2026-08-29 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0011_remove_actor_unique_actor_tenant_civ_name_and_more'),
        ('judgment', '0019_alter_statute_source'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='judgmentcitation',
            name='unique_citation_judgment_statute',
        ),
        migrations.RemoveConstraint(
            model_name='statute',
            name='unique_statute_tenant_code',
        ),
        migrations.AddConstraint(
            model_name='judgmentcitation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('judgment', 'statute'), name='unique_citation_judgment_statute'),
        ),
        migrations.AddConstraint(
            model_name='statute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'code'), name='unique_statute_tenant_code'),
        ),
    ]
