# Generated by Django 5.2.17 on 2026-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0021_judgment_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="amends_plan_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ORIGINAL", "原审判"),
                    ("AMENDMENT", "加项 / 减项审判"),
                    ("REOPEN", "重开审判"),
                ],
                default="ORIGINAL",
                max_length=10,
            ),
        ),
    ]
