# Generated by Django 5.2.17 on 2026-09-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0022_judgment_kind_amends_plan_id"),
        ("realms", "0018_split_greek_from_european"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="realm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="judgments",
                to="realms.realm",
            ),
        ),
    ]
