# Generated by Django 5.2.17 on 2026-09-24 15:07

import uuid

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0024_backfill_judgment_realm"),
        ("souls", "0036_soul_home_tenant"),
        ("tenants", "0012_default_hall_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="draft_saved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="draft_verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSED", "Passed / Saved"),
                    ("FAILED", "Failed / Condemned"),
                    ("PURGATORY", "Purgatory / Intermediate"),
                    ("RETRY", "Retry / Appeal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="draft_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="EvidenceAdmission",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=500)),
                (
                    "delete_cascade_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0, editable=False)),
                (
                    "sort_code",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Sort order for admin lists"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("admitted", models.BooleanField(default=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Why the record is not admitted. Required when admitted is false.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_admissions",
                        to="judgment.judgment",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="admissions",
                        to="souls.soulrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_admissions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence admission",
                "verbose_name_plural": "Evidence admissions",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["judgment", "admitted"],
                        name="judgment_ev_judgmen_29b36c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="judgment_ev_tenant__733430_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("judgment", "record"),
                        name="unique_admission_judgment_record",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("admitted", True),
                            models.Q(("reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="admission_refusal_has_reason",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
