# Generated by Django 5.2.17 on 2026-09-24 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0012_retire_the_pantheon_the_corpus_does_not_name"),
        ("judgment", "0025_evidence_admission_and_verdict_draft"),
        ("souls", "0036_soul_home_tenant"),
        ("tenants", "0012_default_hall_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_judgments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="defer_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="judgment",
            name="deferred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="deferred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deferred_judgments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["tenant", "deferred_at", "claimed_by"],
                name="judgment_ju_tenant__751c3c_idx",
            ),
        ),
    ]
