# Generated by Django 5.2.17 on 2026-09-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0027_judgment_concluded_balance"),
        ("realms", "0021_egy_names_section_nine"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="draft_destination_realm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="realms.realm",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="draft_eternal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="judgment",
            name="draft_term_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
