# Generated by Django 5.2.17 on 2026-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0027_judgment_concluded_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgmentcitation",
            name="snapshot_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgmentcitation",
            name="snapshot_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="judgmentcitation",
            name="snapshot_kind",
            field=models.CharField(
                blank=True,
                choices=[("CONCLUDED", "Concluded"), ("BACKFILLED", "Backfilled")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="judgmentcitation",
            name="snapshot_source",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="judgmentcitation",
            name="snapshot_text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgmentcitation",
            name="snapshot_title",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
