# Generated by Django 5.2.17 on 2026-10-09 02:12

import uuid

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgment", "0033_case_number_unique_statute_effective_required"),
        ("tenants", "0015_tenant_dispatch_enabled_default_true"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgmentComment",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=500)),
                (
                    "delete_cascade_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0, editable=False)),
                (
                    "sort_code",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Sort order for admin lists"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="judgment_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="judgment.judgment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judgment_comments",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Judgment comment",
                "verbose_name_plural": "Judgment comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["judgment", "created_at"],
                        name="judgment_ju_judgmen_c62104_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="judgment_ju_tenant__3a98b4_idx",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
