# Generated by Django 5.2.14 on 2026-05-15 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('name', models.CharField(help_text='组织名称：如 第一殿、冥王厅', max_length=100)),
                ('code', models.CharField(help_text='唯一编码：如 DIYU_01、HEAVEN_01', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('CHINESE', '中国地府'), ('EUROPEAN', '欧洲天堂地狱'), ('EGYPTIAN', '埃及冥界')], help_text='所属文明体系', max_length=20)),
                ('level', models.IntegerField(default=0, help_text='层级深度：0=根组织')),
                ('sort', models.IntegerField(default=0, help_text='同级别排序')),
                ('ext', models.JSONField(blank=True, default=dict, help_text='扩展信息JSON')),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='父组织（平行部门）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='org.organization')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['category', 'level', 'sort'],
                'indexes': [models.Index(fields=['category'], name='organizatio_categor_d78e01_idx'), models.Index(fields=['parent', 'sort'], name='organizatio_parent__2b58b4_idx')],
            },
        ),
    ]
