# Generated by Django 5.2.16 on 2026-08-05 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_alter_organization_managers"),
        ("tenants", "0007_alter_notification_managers_alter_tenant_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="所属租户，由 category 通过 CIV_TO_TENANT 回填",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["tenant", "category"], name="organizatio_tenant__a46314_idx"
            ),
        ),
    ]
