# Generated by Django 5.2.16 on 2026-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0005_organization_delete_cascade_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="category",
            field=models.CharField(
                choices=[
                    ("CHINESE", "中国地府"),
                    ("EUROPEAN", "欧洲天堂地狱"),
                    ("EGYPTIAN", "埃及冥界"),
                    ("GREEK", "希腊冥界"),
                ],
                help_text="所属文明体系",
                max_length=20,
            ),
        ),
    ]
