# Generated by Django 5.2.17 on 2026-09-18 13:08

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("souls", "0036_soul_home_tenant"),
        ("tenants", "0010_drop_dead_notification_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentencePlan",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=500)),
                (
                    "delete_cascade_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0, editable=False)),
                (
                    "sort_code",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Sort order for admin lists"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cycle", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "执行中"),
                            ("RETRIAL", "重审中"),
                            ("HELD", "永久刑期挂起"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已撤销"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "origin_judgment_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("cross_judgment_id", models.UUIDField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_plans",
                        to="souls.soul",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_plans",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentence plan",
                "verbose_name_plural": "Sentence plans",
                "ordering": ["-create_time"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SentenceNode",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=500)),
                (
                    "delete_cascade_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0, editable=False)),
                (
                    "sort_code",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Sort order for admin lists"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("tenant_code", models.CharField(max_length=50)),
                ("is_home", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "未开始"),
                            ("DISPATCHING", "调拨中"),
                            ("ACTIVE", "受刑中"),
                            ("WAITING", "刑满暂留"),
                            ("COMPLETED", "已完成"),
                            ("ETERNAL", "永久刑期"),
                            ("ABORTED", "手动结束"),
                            ("REMOVED", "已减项"),
                            ("CANCELLED", "随计划撤销"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("realm_code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "sentence_years",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_eternal", models.BooleanField(default=False)),
                (
                    "memory_reset",
                    models.CharField(
                        choices=[
                            ("MENGPO", "孟婆汤 (Mengpo Soup)"),
                            ("LETHE", "忘川 (Lethe)"),
                            ("SPELL", "Spell Recitation"),
                            ("NONE", "No Reset"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "disposition_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("dispatch_record_id", models.UUIDField(blank=True, null=True)),
                ("added_by_judgment_id", models.UUIDField(blank=True, null=True)),
                ("added_by_request_id", models.UUIDField(blank=True, null=True)),
                ("removed_by_request_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="sentence_plan.sentenceplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentence node",
                "verbose_name_plural": "Sentence nodes",
                "ordering": ["plan", "order"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SentencePlanRequest",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=500)),
                (
                    "delete_cascade_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0, editable=False)),
                (
                    "sort_code",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Sort order for admin lists"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_tenant_code", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[("AMEND", "加项 / 减项"), ("REOPEN", "重开审判")],
                        max_length=10,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待原审判官决定"),
                            ("ACCEPTED", "已批准"),
                            ("REJECTED", "已驳回"),
                            ("WITHDRAWN", "已撤回"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("requested_by_judgment_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("decision_reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sentence_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="sentence_plan.sentenceplan",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentence plan request",
                "verbose_name_plural": "Sentence plan requests",
                "ordering": ["-create_time"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="sentenceplan",
            index=models.Index(
                fields=["soul", "cycle"], name="sentence_pl_soul_id_efb4e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentenceplan",
            index=models.Index(
                fields=["tenant", "status"], name="sentence_pl_tenant__04c061_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sentenceplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), ("status__in", ["ACTIVE", "RETRIAL", "HELD"])
                ),
                fields=("soul",),
                name="unique_in_progress_sentence_plan",
            ),
        ),
        migrations.AddIndex(
            model_name="sentencenode",
            index=models.Index(
                fields=["tenant_code", "status"], name="sentence_pl_tenant__ecd1dd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sentencenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False),
                    models.Q(("status__in", ["REMOVED", "CANCELLED"]), _negated=True),
                ),
                fields=("plan", "order"),
                name="unique_live_sentence_node_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="sentencenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False),
                    ("status__in", ["DISPATCHING", "ACTIVE", "WAITING"]),
                ),
                fields=("plan",),
                name="unique_occupying_sentence_node",
            ),
        ),
        migrations.AddConstraint(
            model_name="sentencenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("is_home", True)),
                fields=("plan",),
                name="unique_home_sentence_node",
            ),
        ),
        migrations.AddConstraint(
            model_name="sentencenode",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_home", False), ("order", 1), _connector="OR"),
                name="home_sentence_node_is_first",
            ),
        ),
        migrations.AddConstraint(
            model_name="sentencenode",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 1)),
                name="sentence_node_order_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sentencenode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sentence_years__isnull", True),
                    ("sentence_years__gte", 0),
                    _connector="OR",
                ),
                name="sentence_node_years_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sentenceplanrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("status", "PENDING")),
                fields=("plan",),
                name="unique_pending_sentence_request",
            ),
        ),
    ]
