# Generated by Django 5.2.17 on 2026-09-19 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence_plan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sentencenode",
            name="unique_home_sentence_node",
        ),
        migrations.RemoveConstraint(
            model_name="sentencenode",
            name="home_sentence_node_is_first",
        ),
        migrations.AddConstraint(
            model_name="sentencenode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("order", 1), _negated=True),
                    ("is_home", True),
                    _connector="OR",
                ),
                name="first_sentence_node_is_home",
            ),
        ),
    ]
