"""Pinned inventory of every foreign key that touches tenancy (guard G1 in
docs/ARCHITECTURE-tenant-sharding.md section 4.1). Read by
`tests/test_fk_inventory_across_tenants.py`, which derives the same table from
Django's model metadata and fails on any difference.

Key:   "app.Model.field->app.Target"  (a ManyToMany is listed the same way)
Value: (category, one-line reason)

Categories, all derived from the model graph, never declared here:

  tenantcol   FK to Tenant. A model with one is "tenant-scoped".
  user-other  FK to User that is not one of the three AuditUserFields columns.
  S->S        tenant-scoped -> tenant-scoped (neither side is Tenant / User).
              These are the edges that COULD join rows of two tenants: the
              database never checks that both rows carry the same tenant.
  S->U        tenant-scoped -> a model with no tenant column of its own.
  U->S        a model with no tenant column -> a tenant-scoped parent
              (its tenant is whatever the parent's is).
  U->U        neither side has a tenant column.
  m2m         many-to-many.

The three `AuditUserFields` columns (create_user / update_user / deleted_by)
are the same edge on 40 models and are pinned as a model list instead of 120
rows: `AUDIT_USER_MODELS`.

When this fails, a new FK appeared (or an old one went). Add or delete the row
WITH a reason. If the new edge joins two tenants' rows or points at User or
Tenant from a model that would move to another database, read section 3.4 first:
a cross-database foreign key does not exist.
"""

EDGES = {
    'actors.Actor.realm->realms.Realm': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'authentication.User.actor->actors.Actor': ('S->S', "an officer's actor persona; same hall by convention"),
    'authentication.User.organization->org.Organization': ('S->S', 'same hall by convention (Organization is per hall)'),
    'chat.Conversation.initiator->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'chat.Conversation.soul_a->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'chat.Conversation.soul_b->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'death_sync.DeathRegistrationRequest.api_key->death_sync.ExternalApiKey': ('S->S', 'same hall (the key names the tenant the request is stamped with)'),
    'death_sync.DeathRegistrationRequest.judgment->judgment.Judgment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'death_sync.DeathRegistrationRequest.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'death_sync.WebhookConfig.api_key->death_sync.ExternalApiKey': ('S->S', 'same hall (the key names the tenant of the webhook)'),
    'dispatch.CrossTenantJudgment.judgment->judgment.Judgment': ('S->S', "the initiating hall's own judgment"),
    'dispatch.CrossTenantJudgmentParticipant.judgment->dispatch.CrossTenantJudgment': ('S->S', 'crosses by design: the participant row names the invited tenant, the joint judgment the initiating one'),
    'dispatch.CrossTenantJudgmentParticipant.participant_actor->actors.Actor': ('S->S', "crosses by design: an actor of the invited hall sits on the initiating hall's bench"),
    'dispatch.DispatchRecord.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'dispatch.DispatchRecord.target_realm->realms.Realm': ('S->S', 'crosses by design: a realm of the target hall, on a record owned by the source hall'),
    'disposition.Disposition.destination_realm->realms.Realm': ('S->S', 'same hall by convention (resolve_placement filters tenant_id)'),
    'disposition.Disposition.judgment->judgment.Judgment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'disposition.Disposition.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'events.EventWebhookDelivery.webhook->death_sync.WebhookConfig': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'events.SoulEvent.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'judgment.EvidenceAdmission.judgment->judgment.Judgment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'judgment.EvidenceAdmission.record->souls.SoulRecord': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'judgment.Judgment.draft_destination_realm->realms.Realm': ('S->S', 'same hall by convention (resolve_placement filters tenant_id)'),
    'judgment.Judgment.judge->actors.Actor': ('S->S', "the sitting judge's actor; same hall by convention"),
    'judgment.Judgment.realm->realms.Realm': ('S->S', 'same hall by convention'),
    'judgment.Judgment.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'judgment.JudgmentComment.judgment->judgment.Judgment': ('S->S', 'same hall by convention; the comment copies the judgment tenant at creation'),
    'judgment.JudgmentCitation.judgment->judgment.Judgment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'judgment.JudgmentCitation.statute->judgment.Statute': ('S->S', 'same hall: StatuteCitationService.resolve refuses a statute of another tenant or civilization'),
    'judgment.Statute.source_actor->actors.Actor': ('S->S', 'same hall by convention'),
    'org.Organization.parent->org.Organization': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'realms.Realm.parent_realm->realms.Realm': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'realms.SoulPathEntry.realm->realms.Realm': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'realms.SoulPathEntry.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'reincarnation.Reincarnation.disposition->disposition.Disposition': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'reincarnation.Reincarnation.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'scheduler.TaskRun.job->scheduler.ScheduledJob': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'sentence_plan.SentencePlan.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'social.Comment.parent->social.Comment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'social.Comment.post->social.Post': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'social.Reaction.comment->social.Comment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'social.Reaction.post->social.Post': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'social.Report.comment->social.Comment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'social.Report.post->social.Post': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'souls.SoulRecord.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'souls.SoulRecord.statute->judgment.Statute': ('S->S', 'citation of a corpus statute; statute codes are global in practice (EU-INF-*), unique only per (tenant, code)'),
    'workflow.ApprovalWorkflow.coordinating_realm->realms.Realm': ('S->S', 'same hall by convention'),
    'workflow.ApprovalWorkflow.judgment->judgment.Judgment': ('S->S', 'same hall by convention; nothing in the database checks that the two rows share a tenant'),
    'workflow.ApprovalWorkflow.original_workflow->workflow.ApprovalWorkflow': ('S->S', 'self reference (appeal); same hall'),
    'workflow.ApprovalWorkflow.soul->souls.Soul': ('S->S', 'may cross: residence moves soul.tenant while this row keeps the tenant it was written under'),
    'authentication.User.rbac_role->perm.Role': ('S->U', 'global role table (Role has no tenant column)'),
    'chat.Conversation.account_a->soul_accounts.SoulAccount': ('S->U', 'soul-account side of a direct room; account has no tenant column (via soul.home_tenant)'),
    'chat.Conversation.account_b->soul_accounts.SoulAccount': ('S->U', 'soul-account side of a direct room; account has no tenant column (via soul.home_tenant)'),
    'scheduler.ScheduledJob.periodic_task->django_celery_beat.PeriodicTask': ('S->U', 'django-celery-beat row (global table)'),
    'workflow.ApprovalWorkflow.current_node->workflow.ApprovalNode': ('S->U', 'node of this workflow; the node has no tenant column, it is owned through its workflow'),
    'workflow.ApprovalWorkflow.template_version->workflow.WorkflowTemplateVersion': ('S->U', 'version of the template this workflow ran; owned through the template'),
    'workflow.WorkflowTemplate.published_version->workflow.WorkflowTemplateVersion': ('S->U', 'owned through the template'),
    'chat.ChatIdentity.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'chat.ChatImage.conversation->chat.Conversation': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'chat.InboxOfficerState.conversation->chat.Conversation': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'perm.Role.organization->org.Organization': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'sentence_plan.SentenceNode.plan->sentence_plan.SentencePlan': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'sentence_plan.SentencePlanRequest.plan->sentence_plan.SentencePlan': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'social.PostMedia.post->social.Post': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'social.ReportEntry.report->social.Report': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'social.SensitiveWordDailyHit.word->social.SensitiveWord': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_accounts.CooldownShorteningRequest.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_accounts.InitialCredential.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_accounts.RebirthApplication.appeal_workflow->workflow.ApprovalWorkflow': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_accounts.RebirthApplication.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_accounts.RebirthApplication.workflow->workflow.ApprovalWorkflow': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_accounts.SoulAccount.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_push.PushDelivery.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_push.PushDevice.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'soul_push.PushPreference.soul->souls.Soul': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'workflow.ApprovalNode.approver_actor->actors.Actor': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'workflow.ApprovalNode.realm->realms.Realm': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'workflow.ApprovalNode.workflow->workflow.ApprovalWorkflow': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'workflow.WorkflowTemplateVersion.template->workflow.WorkflowTemplate': ('U->S', "owned through the parent row (no tenant column of its own; the parent's tenant is the owner)"),
    'authentication.MfaRecoveryCode.mfa->authentication.OfficerMfa': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'chat.ChatIdentity.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'chat.ChatImage.uploader->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'menus.Menu.parent->menus.Menu': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'menus.MenuButton.menu->menus.Menu': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'notifications.NotificationEmail.notification->notifications.UserNotification': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'perm.FieldPermission.role->perm.Role': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'perm.Role.parent->perm.Role': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'perm.RolePermission.data_scope->perm.DataScope': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'perm.RolePermission.permission->perm.Permission': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'perm.RolePermission.role->perm.Role': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'perm.RowLevelDataScope.role->perm.Role': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_accounts.CooldownShorteningRequest.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_accounts.CooldownShorteningRequest.application->soul_accounts.RebirthApplication': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_accounts.InitialCredential.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_accounts.RebirthApplication.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_accounts.SoulAccount.previous_account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_assist.AssistConfig.eval_soul_account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_assist.AssistConversation.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_assist.AssistEvalResult.case->soul_assist.AssistEvalCase': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_assist.AssistEvalResult.run->soul_assist.AssistEvalRun': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_assist.AssistMessage.conversation->soul_assist.AssistConversation': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_push.PushDelivery.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_push.PushDelivery.device->soul_push.PushDevice': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_push.PushDevice.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'soul_push.PushPreference.account->soul_accounts.SoulAccount': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'workflow.ApprovalNode.on_fail->workflow.ApprovalNode': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'workflow.ApprovalNode.on_pass->workflow.ApprovalNode': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'workflow.ApprovalNode.reject_to->workflow.ApprovalNode': ('U->U', 'stays inside one global/child table family (no tenant column on either side)'),
    'authentication.User.groups->auth.Group': ('m2m', 'Django auth permissions plumbing (global tables)'),
    'authentication.User.user_permissions->auth.Permission': ('m2m', 'Django auth permissions plumbing (global tables)'),
    'actors.Actor.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'audit.AuditLog.tenant->tenants.Tenant': ('tenantcol', 'PROTECT: a hall with audit history cannot be deleted'),
    'authentication.User.tenant->tenants.Tenant': ('tenantcol', "the officer's hall; nullable (ADMIN and some accounts have none)"),
    'chat.Conversation.tenant->tenants.Tenant': ('tenantcol', 'PROTECT: hall of an officer inbox conversation'),
    'chat.InboxReplyTemplate.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'death_sync.DeathRegistrationRequest.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'death_sync.ExternalApiKey.tenant->tenants.Tenant': ('tenantcol', 'an API key belongs to one hall; death sync derives the tenant from it (no JWT)'),
    'death_sync.WebhookConfig.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'dispatch.CrossTenantJudgment.initiating_tenant->tenants.Tenant': ('tenantcol', 'the hall that convened the joint bench'),
    'dispatch.CrossTenantJudgment.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'dispatch.CrossTenantJudgmentParticipant.participant_tenant->tenants.Tenant': ('tenantcol', 'the invited hall: a second tenant on one bench'),
    'dispatch.CrossTenantJudgmentParticipant.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'dispatch.DispatchRecord.source_tenant->tenants.Tenant': ('tenantcol', 'the hall the soul leaves; the one write that names two tenants'),
    'dispatch.DispatchRecord.target_tenant->tenants.Tenant': ('tenantcol', 'the hall that receives the soul'),
    'dispatch.DispatchRecord.tenant->tenants.Tenant': ('tenantcol', 'owner of the record (the proposing hall)'),
    'disposition.Disposition.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'events.EventWebhookDelivery.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'events.SoulEvent.tenant->tenants.Tenant': ('tenantcol', 'PROTECT: a hall with event history cannot be deleted'),
    'judgment.EvidenceAdmission.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'judgment.Judgment.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'judgment.JudgmentComment.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'judgment.JudgmentCitation.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'judgment.Statute.tenant->tenants.Tenant': ('tenantcol', 'corpus statutes are per hall; code unique per (tenant, code)'),
    'ledger.BalanceSnapshot.tenant->tenants.Tenant': ('tenantcol', 'per-hall monthly snapshot'),
    'ledger.SoulCensusSnapshot.tenant->tenants.Tenant': ('tenantcol', 'per-hall daily census'),
    'org.Organization.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'realms.Realm.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'realms.SoulPathEntry.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'reincarnation.Reincarnation.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'scheduler.ScheduledJob.tenant->tenants.Tenant': ('tenantcol', 'per-hall schedule'),
    'scheduler.TaskRun.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'sentence_plan.SentencePlan.tenant->tenants.Tenant': ('tenantcol', "the soul's home hall (the plan belongs to the origin, not to the residence)"),
    'social.Comment.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'social.Follow.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'social.Post.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'social.Reaction.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'social.Report.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'social.SensitiveWord.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'social.SocialMute.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'soul_assist.AssistUsage.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'souls.Soul.home_tenant->tenants.Tenant': ('tenantcol', 'origin hall, set while the soul resides elsewhere'),
    'souls.Soul.tenant->tenants.Tenant': ('tenantcol', 'residence: where the soul is now; changes on dispatch (doc 1.3 items 1, 2)'),
    'souls.SoulRecord.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'workflow.ApprovalWorkflow.tenant->tenants.Tenant': ('tenantcol', 'ownership column: the row belongs to this tenant'),
    'workflow.WorkflowTemplate.tenant->tenants.Tenant': ('tenantcol', 'templates are per hall'),
    'judgment.JudgmentComment.author->authentication.User': ('user-other', 'global identity: who wrote the comment'),
    'audit.AuditLog.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'authentication.LoginLog.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'authentication.MfaRememberedDevice.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'authentication.OfficerMfa.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'chat.Conversation.assignee->authentication.User': ('user-other', 'global identity: officer the conversation is assigned to'),
    'chat.InboxOfficerState.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'chat.InboxReplyTemplate.created_by->authentication.User': ('user-other', 'global identity: creator'),
    'dispatch.CrossTenantJudgmentParticipant.sentence_submitted_by->authentication.User': ('user-other', 'global identity: officer who filled the sentence node'),
    'dispatch.DispatchRecord.dispatched_by->authentication.User': ('user-other', 'global identity: officer who proposed the dispatch'),
    'disposition.Disposition.archived_by->authentication.User': ('user-other', 'global identity: officer who archived it'),
    'judgment.Judgment.archived_by->authentication.User': ('user-other', 'global identity: officer who archived it'),
    'judgment.Judgment.claimed_by->authentication.User': ('user-other', 'global identity: officer who claimed the case'),
    'judgment.Judgment.deferred_by->authentication.User': ('user-other', 'global identity: officer who deferred it'),
    'notifications.UserNotification.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'officer_app.OfficerPushDevice.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'scheduler.TaskRun.triggered_by->authentication.User': ('user-other', 'global identity: who triggered the run'),
    'sentence_plan.SentencePlanRequest.decided_by->authentication.User': ('user-other', 'global identity: officer who decided the request'),
    'social.Comment.author->authentication.User': ('user-other', 'global identity: who wrote it'),
    'social.Comment.moderated_by->authentication.User': ('user-other', 'global identity: officer who moderated it'),
    'social.Follow.follower->authentication.User': ('user-other', 'global identity: following side'),
    'social.Follow.following->authentication.User': ('user-other', 'global identity: followed side'),
    'social.Post.author->authentication.User': ('user-other', 'global identity: who wrote it'),
    'social.Post.moderated_by->authentication.User': ('user-other', 'global identity: officer who moderated it'),
    'social.PostMedia.deleted_by->authentication.User': ('user-other', 'global identity: who deleted the file'),
    'social.PostMedia.uploader->authentication.User': ('user-other', 'global identity: who uploaded the file'),
    'social.Reaction.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'social.Report.resolved_by->authentication.User': ('user-other', 'global identity: officer who resolved the report'),
    'social.Report.target_user->authentication.User': ('user-other', 'global identity: reported account'),
    'social.ReportEntry.reporter->authentication.User': ('user-other', 'global identity: who reported'),
    'social.SensitiveWord.created_by->authentication.User': ('user-other', 'global identity: creator'),
    'social.SocialMute.created_by->authentication.User': ('user-other', 'global identity: creator'),
    'social.SocialMute.lifted_by->authentication.User': ('user-other', 'global identity: officer who lifted the mute'),
    'social.SocialMute.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'social.UserProfile.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'soul_accounts.CooldownShorteningRequest.decided_by->authentication.User': ('user-other', 'global identity: officer who decided the request'),
    'soul_accounts.InitialCredential.delivered_by->authentication.User': ('user-other', 'global identity: officer who delivered the credential'),
    'soul_accounts.InitialCredential.revealed_by->authentication.User': ('user-other', 'global identity: officer who revealed the initial credential'),
    'soul_accounts.SoulAccount.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'soul_assist.AssistConfig.eval_officer->authentication.User': ('user-other', 'global identity: evaluation officer identity'),
    'soul_assist.AssistConversation.deleted_by->authentication.User': ('user-other', 'global identity: who deleted the file'),
    'soul_assist.AssistConversation.user->authentication.User': ('user-other', 'global identity: the owning account'),
    'soul_assist.AssistEvalRun.created_by->authentication.User': ('user-other', 'global identity: creator'),
    'souls.Soul.archived_by->authentication.User': ('user-other', 'global identity: officer who archived it'),
    'souls.SoulRecord.date_warning_acknowledged_by->authentication.User': ('user-other', 'global identity: officer who acknowledged the date warning'),
    'workflow.ApprovalNode.approver->authentication.User': ('user-other', 'global identity: officer assigned to the approval node'),
    'workflow.WorkflowTemplateVersion.published_by->authentication.User': ('user-other', 'global identity: officer who published it'),
    'workflow.WorkflowTemplateVersion.saved_by->authentication.User': ('user-other', 'global identity: officer who saved the draft'),
}

AUDIT_USER_MODELS = [
    'actors.Actor',
    'audit.AuditLog',
    'authentication.LoginLog',
    'authentication.User',
    'death_sync.DeathRegistrationRequest',
    'death_sync.ExternalApiKey',
    'death_sync.WebhookConfig',
    'dispatch.CrossTenantJudgment',
    'dispatch.CrossTenantJudgmentParticipant',
    'dispatch.DispatchRecord',
    'disposition.Disposition',
    'events.EventWebhookDelivery',
    'events.SoulEvent',
    'judgment.EvidenceAdmission',
    'judgment.Judgment',
    'judgment.JudgmentCitation',
    'judgment.JudgmentComment',
    'judgment.Statute',
    'menus.Menu',
    'menus.MenuButton',
    'notifications.UserNotification',
    'org.Organization',
    'perm.DataScope',
    'perm.Permission',
    'perm.Role',
    'perm.RolePermission',
    'realms.Realm',
    'reincarnation.Reincarnation',
    'sentence_plan.SentenceNode',
    'sentence_plan.SentencePlan',
    'sentence_plan.SentencePlanRequest',
    'social.Comment',
    'social.Follow',
    'social.Post',
    'social.Reaction',
    'souls.Soul',
    'souls.SoulRecord',
    'tenants.Tenant',
    'workflow.ApprovalNode',
    'workflow.ApprovalWorkflow',
    'workflow.WorkflowTemplate',
]
