"""Every unique key in the schema (column, UniqueConstraint, unique_together)
and what kind it is -- guard G5 in docs/ARCHITECTURE-tenant-sharding.md 4.1.
Read by `tests/test_global_uniqueness_inventory.py`, which derives the same
table from the models.

Key:   "app.Model:column_or_constraint_name"
Value: (kind, one-line reason)

  GLOBAL_VALUE  unique over the whole database -- what a per-tenant database
                split would silently weaken. 20 today; each has a guarantee
                (a UNIQUE index, plus a generator for soul_code / case_number).
  PER_PARENT    unique within one parent row; a placement rule for sharding.
  PER_TENANT    tenant is part of the key; NOT global.

Dropping a GLOBAL_VALUE key must fail the test that reads this file; add one
only together with a plan for how it stays unique across databases.
"""

UNIQUE_KEYS = {
    'authentication.MfaRememberedDevice:token_hash': ('GLOBAL_VALUE', 'hash of the remembered-device cookie token'),
    'authentication.User:unique_user_email_among_live_rows': ('GLOBAL_VALUE', 'officer e-mail, case-insensitive, live rows only; deactivating frees the address'),
    'authentication.User:username': ('GLOBAL_VALUE', 'login name of every officer / soul account; one namespace over all halls'),
    'chat.ChatIdentity:localpart': ('GLOBAL_VALUE', 'Matrix localpart, one namespace over all halls (chat is cross-hall)'),
    'chat.ChatIdentity:matrix_user_id': ('GLOBAL_VALUE', 'Matrix user id, one namespace over all halls'),
    'chat.Conversation:room_id': ('GLOBAL_VALUE', 'Matrix room id'),
    'death_sync.DeathRegistrationRequest:uniq_death_reg_idempotency': ('GLOBAL_VALUE', '(source_system, idempotency_key) over ALL tenants: two halls sending the same explicit X-Idempotency-Key collide (see report)'),
    'death_sync.ExternalApiKey:key_hash': ('GLOBAL_VALUE', 'hash of an API key; the key alone selects the tenant on the machine-to-machine path'),
    'judgment.Judgment:case_number': ('GLOBAL_VALUE', 'printed case number; generated from JudgmentCaseCounter keyed by <prefix>-<year>, so two halls sharing a prefix cannot repeat a number'),
    'officer_app.OfficerPushDevice:token': ('GLOBAL_VALUE', 'push token of an officer device'),
    'org.Organization:code': ('GLOBAL_VALUE', 'organization code'),
    'perm.DataScope:code': ('GLOBAL_VALUE', 'data-scope code, global RBAC table'),
    'perm.Permission:unique_permission_codename_alive': ('GLOBAL_VALUE', 'permission codename, global RBAC table'),
    'perm.Role:unique_role_name_alive': ('GLOBAL_VALUE', 'role name, global RBAC table'),
    'realms.Realm:realm_code': ('GLOBAL_VALUE', 'realm code; looked up across tenants by dispatch, sentence plans and the ledger'),
    'scheduler.TaskRun:celery_task_id': ('GLOBAL_VALUE', 'Celery task id'),
    'soul_assist.HelpChunk:help_chunk_one_per_entry': ('GLOBAL_VALUE', '(locale, entry_id) of the help corpus; global content'),
    'soul_push.PushDevice:token': ('GLOBAL_VALUE', 'push token of a soul device'),
    'souls.Soul:soul_code': ('GLOBAL_VALUE', 'soul login name and the key of cross-hall private chat lookup (/me/chat/lookup/); generated by soul_accounts.services._ensure_soul_code with collision retry'),
    'tenants.Tenant:code': ('GLOBAL_VALUE', 'tenant code; the key the JWT, the death-sync API key and every *_for_tenant task resolve a tenant by'),
    'authentication.OfficerMfa:user': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'chat.ChatIdentity:account': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'chat.Conversation:chat_one_open_direct_room_per_pair': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'chat.InboxOfficerState:chat_one_inbox_state_per_officer': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'dispatch.CrossTenantJudgment:judgment': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'dispatch.CrossTenantJudgmentParticipant:unique_cross_judgment_node_order': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'dispatch.DispatchRecord:unique_active_dispatch': ('PER_PARENT', 'one live PROPOSED/APPROVED dispatch per soul, spanning source and target tenant'),
    'disposition.Disposition:judgment': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'judgment.EvidenceAdmission:unique_admission_judgment_record': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'judgment.JudgmentCitation:unique_citation_judgment_statute': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'menus.MenuButton:unique_menubutton_menu_code': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'notifications.NotificationEmail:notification': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'perm.FieldPermission:unique_together(role,model_name,field_name)': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'perm.RolePermission:unique_rolepermission_role_permission': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'realms.SoulPathEntry:soulpath_one_open_entry_per_soul': ('PER_PARENT', 'one open path station per soul, whichever tenant it is in'),
    'realms.SoulPathEntry:soulpath_unique_sequence': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'scheduler.ScheduledJob:periodic_task': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'sentence_plan.SentenceNode:unique_live_sentence_node_order': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'sentence_plan.SentenceNode:unique_occupying_sentence_node': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'sentence_plan.SentencePlan:unique_in_progress_sentence_plan': ('PER_PARENT', 'one in-progress plan per soul (plan belongs to the home tenant, the soul may reside elsewhere)'),
    'sentence_plan.SentencePlanRequest:unique_pending_sentence_request': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.Follow:unique_follow_relationship': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.Reaction:unique_reaction_per_comment': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.Reaction:unique_reaction_per_post': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.Report:social_report_one_open_per_comment': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.Report:social_report_one_open_per_post': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.Report:social_report_one_open_per_user': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.ReportEntry:social_report_entry_once_per_reporter': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.SensitiveWordDailyHit:social_sensitive_word_hit_one_row_per_day': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'social.UserProfile:user': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.CooldownShorteningRequest:application': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.CooldownShorteningRequest:cooldown_shortening_one_pending_per_soul': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.RebirthApplication:appeal_workflow': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.RebirthApplication:rebirth_application_one_open_per_soul': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.RebirthApplication:workflow': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.SoulAccount:previous_account': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.SoulAccount:soul_account_one_current': ('PER_PARENT', 'one current account per soul'),
    'soul_accounts.SoulAccount:soul_account_one_per_life': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_accounts.SoulAccount:user': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_push.PushDelivery:push_delivery_once_per_device': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_push.PushDelivery:push_delivery_once_without_device': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'soul_push.PushPreference:account': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'workflow.ApprovalWorkflow:judgment': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'workflow.WorkflowTemplateVersion:uniq_wf_tmpl_one_draft': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'workflow.WorkflowTemplateVersion:uniq_wf_tmpl_one_published': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'workflow.WorkflowTemplateVersion:uniq_wf_tmpl_version_number': ('PER_PARENT', "unique inside one parent row; holds across tenants only because the parent's pk is global and the rows live with the parent"),
    'actors.Actor:unique_actor_tenant_civ_name': ('PER_TENANT', 'unique per tenant only (tenant is in the key); NOT global'),
    'chat.Conversation:chat_one_open_inbox_per_soul_and_hall': ('PER_TENANT', 'unique per tenant only (tenant is in the key); NOT global'),
    'judgment.Statute:unique_statute_tenant_code': ('PER_TENANT', 'statute code is unique PER TENANT only, yet some code lookups ignore the tenant (see tenancy_unscoped_sites CODE rows)'),
    'ledger.BalanceSnapshot:uniq_balance_snapshot_tenant_month': ('PER_TENANT', 'unique per tenant only (tenant is in the key); NOT global'),
    'ledger.SoulCensusSnapshot:uniq_census_snapshot_tenant_day': ('PER_TENANT', 'unique per tenant only (tenant is in the key); NOT global'),
    'social.SensitiveWord:social_sensitive_word_unique_per_tenant': ('PER_TENANT', 'unique per tenant only (tenant is in the key); NOT global'),
}
