"""Declared uses of unscoped managers outside tests (guard G2 in
docs/ARCHITECTURE-tenant-sharding.md section 4.1). Read by
`tests/test_unscoped_query_sites_are_declared.py`.

Why: `TenantManager` filters soft deletes only, so `Model.objects` is already
unscoped by tenant. What the viewset contract test cannot see is service,
Celery and signal code that reaches past the manager entirely. This file lists
every such site the AST scanner finds, with the reason it is safe today; after
a database split each of them needs a routing decision.

Entry: (file under backend/, enclosing "Class.function", expression, count, tag, reason)
  expression  `X.all_objects`, `X._base_manager`, `X._default_manager`, `Tenant.objects`
  count       how many times that expression occurs in that function

Tags (what keeps the site from leaking across tenants today):
  LOCK      lock / re-read of ONE row by pk that the caller already reached through a
            scoped path; `all_objects` only skips the soft-delete filter
  PK        lookup keyed by a pk / FK of an already scoped row
  FILTERED  carries its own tenant filter, or is wrapped in scope_to_tenant
  CODE      lookup by a code, then checked / relied on to be unique
  GLOBAL    model has no tenant column
  FANOUT    the Tenant table itself: fan-out, or resolving one tenant by code / id
  CROSS     deliberately crosses tenants (dispatch, residence, ADMIN, joint bench)
  CLI       management command / maintenance sweep with no request or tenant

To declare a NEW site you must add its row here, with a reason that says why it
cannot return or change another tenant's rows -- or, if it can, that it is meant to.
A row whose site no longer exists must be deleted.
"""

TAGS = {"LOCK", "PK", "FILTERED", "CODE", "GLOBAL", "FANOUT", "CROSS", "CLI"}

SITES = [
    ('apps/actors/management/commands/consolidate_eu_pantheon.py', 'Command.handle', 'Actor.all_objects', 1, 'CLI', 'operator cleanup command, filtered by the two tenant codes it merges'),
    ('apps/actors/management/commands/fix_actor_civilization.py', 'Command.handle', 'Actor.all_objects', 1, 'CLI', 'operator repair command; probes for a soft-deleted twin by name+civilization'),
    ('apps/actors/mythology/seeding.py', 'MythologySeeder._link_realm_parents', 'Realm.all_objects', 1, 'CLI', 'mythology seed command: idempotent upsert by civilization/code; tenant passed explicitly on create'),
    ('apps/actors/mythology/seeding.py', 'MythologySeeder._seed_actors', 'Realm.all_objects', 1, 'CLI', 'mythology seed command: idempotent upsert by civilization/code; tenant passed explicitly on create'),
    ('apps/actors/mythology/seeding.py', 'MythologySeeder._seed_assessors', 'Realm.all_objects', 1, 'CLI', 'mythology seed command: idempotent upsert by civilization/code; tenant passed explicitly on create'),
    ('apps/actors/mythology/seeding.py', 'MythologySeeder._seed_derived_statutes', 'Actor.all_objects', 1, 'CLI', 'mythology seed command: idempotent upsert by civilization/code; tenant passed explicitly on create'),
    ('apps/actors/mythology/seeding.py', 'MythologySeeder._seed_tenant', 'Tenant.objects', 2, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/actors/mythology/seeding.py', 'MythologySeeder._upsert', 'model.all_objects', 2, 'CLI', 'mythology seed command: idempotent upsert by civilization/code; tenant passed explicitly on create'),
    ('apps/audit/views.py', 'AuditLogFilter.filter_tenant', 'Tenant.objects', 1, 'FANOUT', 'resolves one hall by its globally unique code, for the global admin only; a hall-bound user is answered from their own tenant (403 for any other code)'),
    ('apps/audit/retention.py', 'prune_logs', 'AuditLog.all_objects', 1, 'FILTERED', 'retention sweep: every query carries tenant=<the task\'s tenant> (None = the NULL-tenant rows); all_objects only includes soft-deleted rows'),
    ('apps/audit/retention.py', 'prune_logs', 'LoginLog.all_objects', 2, 'FILTERED', 'retention sweep: LoginLog has no tenant column, so it filters by user__tenant (or, for tenant=None, by no user / tenant-less user)'),
    ('apps/audit/tasks.py', 'prune_logs_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant'),
    ('apps/audit/signals.py', '_on_pre_save', 'sender._base_manager', 1, 'PK', 'pre-save snapshot of the same row by pk, for the audit diff'),
    ('apps/authentication/views.py', 'UserViewSet.get_queryset', 'Tenant.objects', 1, 'GLOBAL', "reads every tenant's MFA-required-roles setting to build one OR filter; the resulting User queryset is then scoped by the caller as usual"),
    ('apps/authentication/views.py', 'civilizations_view', 'Tenant.objects', 1, 'GLOBAL', 'public list of active civilizations at login; exposes tenant codes only, no tenant rows'),
    ('apps/chat/inbox.py', 'counts', 'Tenant.objects', 1, 'FANOUT', 'hall labels for tenants that already own conversations in the (already scoped) inbox queryset'),
    ('apps/core/recycle_bin.py', '_unfiltered_manager', 'model._base_manager', 1, 'PK', 'helper returning the unfiltered manager for the recycle bin; callers scope (apps/core/recycle_bin_views.py)'),
    ('apps/core/ws_tenant.py', 'TenantMiddleware._resolve_tenant', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/death_sync/management/commands/create_api_key.py', 'Command.handle', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/death_sync/tasks.py', 'cleanup_old_requests', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/death_sync/tasks.py', 'cleanup_old_requests_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/dispatch/models.py', 'CrossTenantJudgment.transition_to', 'CrossTenantJudgment._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/dispatch/models.py', 'DispatchRecord.transition_to', 'DispatchRecord._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/dispatch/serializers.py', 'CrossTenantJudgmentSerializer', 'Judgment.all_objects', 1, 'PK', "PrimaryKeyRelatedField queryset; validate_judgment (below) refuses a judgment outside the caller's tenant"),
    ('apps/dispatch/serializers.py', 'CrossTenantJudgmentSerializer.validate_judgment', 'CrossTenantJudgment._base_manager', 1, 'PK', 'OneToOne uniqueness probe by judgment, soft-deleted rows included on purpose; tenant of the judgment was just checked'),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService._check_node_order', 'CrossTenantJudgment._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.check_bench_sentences', 'Realm.all_objects', 1, 'CODE', 'realm_code is globally unique (Realm.realm_code); only civilization is read'),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.conclude', 'CrossTenantJudgment._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.reorder_nodes', 'CrossTenantJudgment._base_manager', 1, 'CROSS', "locks the joint judgment, then re-numbers seats by pk taken from that judgment's own participants"),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.reorder_nodes', 'CrossTenantJudgmentParticipant.all_objects', 1, 'CROSS', "locks the joint judgment, then re-numbers seats by pk taken from that judgment's own participants"),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.seatable_actors', 'Actor.all_objects', 1, 'FILTERED', 'explicit tenant=tenant filter'),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.submit_sentence', 'CrossTenantJudgment._base_manager', 1, 'CROSS', "cross-tenant bench: locks the joint judgment and the participant's own seat; realm looked up by globally unique realm_code and its civilization checked against the seat's tenant; Judgment read for a soul name only"),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.submit_sentence', 'CrossTenantJudgmentParticipant.all_objects', 1, 'CROSS', "cross-tenant bench: locks the joint judgment and the participant's own seat; realm looked up by globally unique realm_code and its civilization checked against the seat's tenant; Judgment read for a soul name only"),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.submit_sentence', 'Judgment.all_objects', 1, 'CROSS', "cross-tenant bench: locks the joint judgment and the participant's own seat; realm looked up by globally unique realm_code and its civilization checked against the seat's tenant; Judgment read for a soul name only"),
    ('apps/dispatch/services.py', 'CrossTenantJudgmentService.submit_sentence', 'Realm.all_objects', 1, 'CROSS', "cross-tenant bench: locks the joint judgment and the participant's own seat; realm looked up by globally unique realm_code and its civilization checked against the seat's tenant; Judgment read for a soul name only"),
    ('apps/dispatch/services.py', 'DispatchService._check_proposable', 'DispatchRecord._base_manager', 1, 'PK', 'existence check by soul for an active dispatch; the soul was already scoped by the caller'),
    ('apps/dispatch/services.py', 'DispatchService._lock_soul', 'Soul.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/dispatch/services.py', 'DispatchService.eligible_realms', 'Realm.all_objects', 2, 'FILTERED', 'explicit tenant_id=target_tenant.pk filter (and .none() when the civilization is unknown)'),
    ('apps/dispatch/services.py', 'DispatchService.end_residence', 'DispatchRecord._base_manager', 1, 'CROSS', "residence end: locks the soul, then the executed dispatch to that soul's current (residence) tenant"),
    ('apps/dispatch/services.py', 'DispatchService.end_residence', 'Soul.all_objects', 1, 'CROSS', "residence end: locks the soul, then the executed dispatch to that soul's current (residence) tenant"),
    ('apps/dispatch/services.py', 'DispatchService.execute', 'Soul.all_objects', 1, 'LOCK', 'locks the soul by pk and re-checks soul.tenant_id == source_tenant_id under the lock (residence is one transaction over two tenants, doc 1.3 item 1)'),
    ('apps/dispatch/services.py', 'DispatchService.record_blocked_return', 'DispatchRecord._base_manager', 1, 'CROSS', 'residence: reentrant soul lock, the executed dispatch of that soul, and a dedupe probe of its SoulEvents by soul+payload'),
    ('apps/dispatch/services.py', 'DispatchService.record_blocked_return', 'Soul.all_objects', 1, 'CROSS', 'residence: reentrant soul lock, the executed dispatch of that soul, and a dedupe probe of its SoulEvents by soul+payload'),
    ('apps/dispatch/services.py', 'DispatchService.record_blocked_return', 'SoulEvent.all_objects', 1, 'CROSS', 'residence: reentrant soul lock, the executed dispatch of that soul, and a dedupe probe of its SoulEvents by soul+payload'),
    ('apps/dispatch/services.py', 'DispatchService.save_draft', 'DispatchRecord._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/dispatch/views.py', 'CrossTenantJudgmentViewSet.get_queryset', 'CrossTenantJudgment._base_manager', 1, 'FILTERED', 'unfiltered base manager, then explicit Q on initiating/participant tenant for non-ADMIN callers'),
    ('apps/dispatch/views.py', 'CrossTenantJudgmentViewSet.participate', 'Actor.all_objects', 1, 'CROSS', 'actor looked up by pk; add_participant then requires the actor to be seatable for the invited tenant'),
    ('apps/dispatch/views.py', 'CrossTenantJudgmentViewSet.participate', 'Tenant.objects', 2, 'CROSS', 'actor looked up by pk; add_participant then requires the actor to be seatable for the invited tenant'),
    ('apps/dispatch/views.py', 'CrossTenantJudgmentViewSet.seatable_actors', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/dispatch/views.py', 'DispatchRecordViewSet.get_queryset', 'DispatchRecord._base_manager', 1, 'FILTERED', 'unfiltered base manager, then explicit Q(source_tenant)|Q(target_tenant) for non-ADMIN callers'),
    ('apps/dispatch/views.py', 'DispatchRecordViewSet.history', 'DispatchRecord._base_manager', 1, 'FILTERED', 'explicit source_tenant=tenant'),
    ('apps/dispatch/views.py', 'DispatchRecordViewSet.proposed', 'DispatchRecord._base_manager', 1, 'FILTERED', 'explicit target_tenant=tenant'),
    ('apps/dispatch/views.py', 'DispatchRecordViewSet.realm_options', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/disposition/destination.py', '_tenant_realms', 'Realm.all_objects', 1, 'FILTERED', 'explicit tenant_id=judgment.tenant_id'),
    ('apps/disposition/destination.py', 'realm_held', 'SoulPathEntry.all_objects', 1, 'PK', 'counts open path entries of one realm by realm_id'),
    ('apps/disposition/destination.py', 'resolve_placement', 'Realm.all_objects', 1, 'FILTERED', "explicit tenant_id=judgment.tenant_id; another tenant's realm answers like a missing one"),
    ('apps/disposition/management/commands/expire_dispositions.py', 'Command.handle', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/disposition/services.py', 'DispositionService._deepest_cited_circle', 'Statute.all_objects', 1, 'FILTERED', 'Statute looked up by code AND the soul tenant_id (Statute.code is unique per (tenant, code))'),
    ('apps/disposition/services.py', 'DispositionService._execute_during_residence', 'Soul.all_objects', 1, 'LOCK', 'soul lock during residence; re-checks disposition.tenant_id == locked.tenant_id under the lock'),
    ('apps/disposition/services.py', 'DispositionService._execute_plan_node', 'Soul.all_objects', 1, 'LOCK', 'soul lock; re-checks disposition.tenant_id == locked.tenant_id under the lock'),
    ('apps/disposition/tasks.py', 'expire_due_dispositions', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/disposition/tasks.py', 'expire_due_dispositions_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/events/handlers/audit_handler.py', 'AuditHandler.handle', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/events/handlers/webhook_handler.py', 'WebhookHandler._record_deliveries', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/judgment/claims.py', '_lock', 'Judgment.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/judgment/claims.py', '_lock_many', 'Judgment.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/judgment/models.py', 'Statute._bump_revision_if_text_changed', 'Statute.all_objects', 1, 'PK', 'reads the stored copy of the row being saved, by pk'),
    ('apps/judgment/models.py', 'open_judgments', 'Judgment.all_objects', 1, 'PK', 'open judgments of one soul; soul is already in scope'),
    ('apps/judgment/services.py', 'EvidenceAdmissionService.rule', 'Judgment.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/judgment/services.py', 'JudgmentDraftService.save', 'Judgment.all_objects', 3, 'LOCK', 'optimistic-concurrency read/update of one judgment by pk'),
    ('apps/judgment/services.py', 'JudgmentDraftService.touch_after_plain_update', 'Judgment.all_objects', 1, 'PK', 'bumps draft_version of one judgment by pk'),
    ('apps/judgment/services.py', 'StatuteCitationService.cite', 'JudgmentCitation.all_objects', 1, 'PK', 'get_or_create keyed by judgment+statute; tenant copied from judgment.tenant'),
    ('apps/judgment/services.py', 'StatuteCitationService.resolve', 'Statute.all_objects', 1, 'FILTERED', 'looked up by pk on purpose, then statute.tenant_id is compared with judgment.tenant_id and a mismatch is refused (so the error can say why)'),
    ('apps/judgment/services.py', 'StatuteCitationService.snapshot', 'JudgmentCitation.all_objects', 2, 'PK', 'citations of one judgment'),
    ('apps/judgment/services.py', 'StatuteCitationService.uncite', 'JudgmentCitation.all_objects', 1, 'PK', 'citations of one judgment'),
    ('apps/judgment/tasks.py', 'auto_conclude_stale_judgments', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/judgment/tasks.py', 'auto_conclude_stale_judgments_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/judgment/views.py', 'JudgmentViewSet.perform_create', 'Judgment.all_objects', 1, 'LOCK', "locks the soul, then rejects it when soul.tenant_id != the caller's tenant (non-ADMIN)"),
    ('apps/judgment/views.py', 'JudgmentViewSet.perform_create', 'Soul.all_objects', 1, 'LOCK', "locks the soul, then rejects it when soul.tenant_id != the caller's tenant (non-ADMIN)"),
    ('apps/judgment/views.py', 'citing_judgments', 'JudgmentCitation.all_objects', 1, 'PK', 'subquery of judgment ids citing one statute, used inside an already scoped judgment queryset'),
    ('apps/ledger/management/commands/snapshot_balances.py', 'Command.handle', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/ledger/services.py', 'LedgerService._term_start_for', 'Disposition.all_objects', 1, 'PK', 'dispositions of one soul'),
    ('apps/ledger/services.py', 'LedgerService.recalculate_soul_ledger', 'Soul.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/ledger/tasks.py', 'recalculate_all_ledgers', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/ledger/tasks.py', 'recalculate_tenant_ledgers', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/ledger/tasks.py', 'snapshot_balance_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/ledger/tasks.py', 'snapshot_census_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/ledger/views.py', '_attach_capacity', 'Realm.all_objects', 1, 'CODE', 'realm_code is globally unique; adds occupancy to rows already scoped by the caller'),
    ('apps/menus/views.py', 'MenuViewSet.get_queryset', 'Menu.all_objects', 1, 'GLOBAL', 'Menu has no tenant column; ADMIN may include soft-deleted rows'),
    ('apps/notifications/tasks.py', 'email_action_needed_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/officer_app/todo.py', '_dispatches', 'DispatchRecord._base_manager', 1, 'FILTERED', 'explicit target_tenant=tenant (none() without a tenant)'),
    ('apps/officer_app/todo.py', '_workflows', 'ApprovalWorkflow._base_manager', 1, 'FILTERED', 'scope_to_tenant on the same line'),
    ('apps/perm/matrix.py', 'template_restore_refusal', 'WorkflowTemplate.all_objects', 1, 'PK', 'templates of one recycle-bin cascade id'),
    ('apps/perm/models.py', '_revive_or_create', 'model.all_objects', 1, 'GLOBAL', 'Role/Permission/etc. are global tables; revives a binned row by unique key'),
    ('apps/perm/views.py', '_role_name_taken', 'Role.all_objects', 1, 'GLOBAL', 'Role is global; name-uniqueness probe including the recycle bin'),
    ('apps/perm/views.py', 'create_permission', 'Permission.all_objects', 1, 'GLOBAL', 'Permission is global; revives a binned row by codename'),
    ('apps/realms/management/commands/backfill_soul_entry_path.py', 'backfill', 'Soul.all_objects', 1, 'CLI', "operator backfill over every tenant's souls"),
    ('apps/realms/management/commands/backfill_soul_entry_path.py', 'backfill', 'SoulPathEntry.all_objects', 2, 'CLI', "operator backfill over every tenant's souls"),
    ('apps/realms/path.py', 'SoulPathService._open_entry', 'SoulPathEntry.all_objects', 1, 'LOCK', 'locks the open path entry of one soul by soul_id'),
    ('apps/realms/path.py', 'SoulPathService.enter', 'SoulPathEntry.all_objects', 2, 'PK', 'path entries of one soul'),
    ('apps/realms/path.py', 'entry_realm_for', 'Realm.all_objects', 1, 'FILTERED', 'explicit tenant_id=soul.tenant_id'),
    ('apps/reincarnation/services.py', 'ReincarnationService.complete_rebirth', 'Soul.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/scheduler/realtime.py', '_tenant_code', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/scheduler/realtime.py', 'emit_jobs_rebuilt', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/scheduler/services.py', '_active_tenants', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/sentence_plan/management/commands/backfill_sentence_plans.py', 'Command._build', 'DispatchRecord._base_manager', 1, 'CLI', "operator backfill over every tenant's souls; joins stay inside one soul"),
    ('apps/sentence_plan/management/commands/backfill_sentence_plans.py', 'Command._build', 'Disposition.all_objects', 2, 'CLI', "operator backfill over every tenant's souls; joins stay inside one soul"),
    ('apps/sentence_plan/management/commands/backfill_sentence_plans.py', 'Command.handle', 'Judgment.all_objects', 1, 'CLI', "operator backfill over every tenant's souls; joins stay inside one soul"),
    ('apps/sentence_plan/management/commands/backfill_sentence_plans.py', 'Command.handle', 'SentencePlan.all_objects', 1, 'CLI', "operator backfill over every tenant's souls; joins stay inside one soul"),
    ('apps/sentence_plan/management/commands/backfill_sentence_plans.py', 'Command.handle', 'Soul.all_objects', 1, 'CLI', "operator backfill over every tenant's souls; joins stay inside one soul"),
    ('apps/sentence_plan/requests.py', '_assert_open_for', 'SentencePlanRequest.all_objects', 1, 'PK', 'pending-request probe by plan'),
    ('apps/sentence_plan/requests.py', '_locked_pending_request', 'SentencePlanRequest.all_objects', 1, 'LOCK', 'locks one request by pk and plan'),
    ('apps/sentence_plan/requests.py', 'cancel', 'DispatchRecord._base_manager', 1, 'PK', 'cancel works through one plan: its reopen judgments, requests and dispatch record'),
    ('apps/sentence_plan/requests.py', 'cancel', 'Judgment.all_objects', 1, 'PK', 'cancel works through one plan: its reopen judgments, requests and dispatch record'),
    ('apps/sentence_plan/requests.py', 'cancel', 'SentencePlanRequest.all_objects', 1, 'PK', 'cancel works through one plan: its reopen judgments, requests and dispatch record'),
    ('apps/sentence_plan/requests.py', 'conclude_reopened', 'Realm.all_objects', 1, 'CODE', "lookup by a globally unique code, then checked against the caller's civilization/tenant"),
    ('apps/sentence_plan/requests.py', 'normalize_changes', 'Realm.all_objects', 1, 'CODE', "lookup by a globally unique code, then checked against the caller's civilization/tenant"),
    ('apps/sentence_plan/requests.py', 'normalize_changes', 'SentenceNode.all_objects', 1, 'CODE', "lookup by a globally unique code, then checked against the caller's civilization/tenant"),
    ('apps/sentence_plan/services.py', 'SentencePlanService._activate_home_node', 'Disposition.all_objects', 1, 'FILTERED', 'judgment lookup carries tenant_id=plan.tenant_id; realm by global realm_code'),
    ('apps/sentence_plan/services.py', 'SentencePlanService._activate_home_node', 'Judgment.all_objects', 1, 'FILTERED', 'judgment lookup carries tenant_id=plan.tenant_id; realm by global realm_code'),
    ('apps/sentence_plan/services.py', 'SentencePlanService._activate_home_node', 'Realm.all_objects', 1, 'FILTERED', 'judgment lookup carries tenant_id=plan.tenant_id; realm by global realm_code'),
    ('apps/sentence_plan/services.py', 'SentencePlanService._complete', 'Disposition.all_objects', 1, 'PK', 'home disposition by pk'),
    ('apps/sentence_plan/services.py', 'SentencePlanService._dispatch', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/sentence_plan/services.py', 'SentencePlanService._step', 'DispatchRecord._base_manager', 1, 'CROSS', 'pending-request probe by plan; executed dispatch of the soul to its current tenant'),
    ('apps/sentence_plan/services.py', 'SentencePlanService._step', 'SentencePlanRequest.all_objects', 1, 'CROSS', 'pending-request probe by plan; executed dispatch of the soul to its current tenant'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.check_cross_judgment', 'CrossTenantJudgment._base_manager', 1, 'CROSS', 'joint judgment attached to one judgment'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.create_from_conclusion', 'CrossTenantJudgment._base_manager', 1, 'CROSS', 'copies seats of the attached joint judgment into plan nodes'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.create_from_conclusion', 'CrossTenantJudgmentParticipant.all_objects', 2, 'CROSS', 'copies seats of the attached joint judgment into plan nodes'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.node_for_disposition', 'SentenceNode.all_objects', 1, 'PK', 'node of one disposition'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.on_dispatch_executed', 'Realm.all_objects', 1, 'CROSS', 'node found by dispatch_record_id; target-tenant disposition created with record.target_tenant_id; realm by global realm_code'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.on_dispatch_executed', 'SentenceNode.all_objects', 2, 'CROSS', 'node found by dispatch_record_id; target-tenant disposition created with record.target_tenant_id; realm by global realm_code'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.on_dispatch_refused', 'SentenceNode.all_objects', 2, 'LOCK', 'node found and locked by dispatch_record_id'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.on_disposition_executed', 'SentenceNode.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/sentence_plan/services.py', 'SentencePlanService.on_residence_ended_by_hand', 'SentenceNode.all_objects', 2, 'LOCK', 'node found and locked by dispatch_record_id'),
    ('apps/sentence_plan/services.py', '_leave_waiting_station', 'Disposition.all_objects', 1, 'PK', 'disposition of one node by pk'),
    ('apps/sentence_plan/services.py', '_lock_nodes', 'SentenceNode.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/sentence_plan/services.py', '_lock_plan', 'SentencePlan.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/sentence_plan/services.py', '_lock_soul', 'Soul.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/sentence_plan/services.py', '_tenant_id', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/sentence_plan/services.py', 'in_progress_plan', 'SentencePlan.all_objects', 1, 'PK', 'plan of one soul'),
    ('apps/sentence_plan/soul_view.py', 'soul_plan', 'Realm.all_objects', 1, 'PK', "the soul-side plan view: plan of the authenticated soul's own account; realms by global realm_code"),
    ('apps/sentence_plan/soul_view.py', 'soul_plan', 'SentencePlan.all_objects', 1, 'PK', "the soul-side plan view: plan of the authenticated soul's own account; realms by global realm_code"),
    ('apps/sentence_plan/views.py', 'SentencePlanFilter._pending_request', 'SentencePlan.all_objects', 1, 'FILTERED', 'filter fragment applied to an already scoped plan queryset (pk subquery)'),
    ('apps/social/media.py', '_as_request', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/social/media.py', '_officer_may_view', 'Post.all_objects', 1, 'FILTERED', "scope_to_tenant(field='post__tenant') for the media; the Post probe is by pk of that media's post"),
    ('apps/social/media.py', '_officer_may_view', 'PostMedia.all_objects', 1, 'FILTERED', "scope_to_tenant(field='post__tenant') for the media; the Post probe is by pk of that media's post"),
    ('apps/social/media.py', '_stray_files', 'PostMedia.all_objects', 1, 'CLI', 'cleanup sweep: every file name any row points to, across tenants, to find orphan files on disk'),
    ('apps/social/media.py', 'delete_pending', 'PostMedia.all_objects', 1, 'PK', 'deletes one media row by pk'),
    ('apps/social/media.py', 'orphans', 'PostMedia.all_objects', 1, 'CLI', 'cleanup sweep over unattached uploads of every tenant (media has no tenant column; scoped through post)'),
    ('apps/social/media.py', 'purge_for_post', 'PostMedia.all_objects', 1, 'PK', 'deletes the media of one post'),
    ('apps/social/media_views.py', 'PostMediaFileView.get', 'PostMedia.all_objects', 1, 'PK', 'media by pk from a signed grant; may_view(viewer, media, tenant) is checked right after'),
    ('apps/social/moderation_views.py', 'HandledContentViewSet', 'Post.all_objects', 1, 'FILTERED', 'class-level queryset placeholder; get_queryset applies scope_to_tenant to each part'),
    ('apps/social/moderation_views.py', 'HandledContentViewSet.get_queryset', 'Post.all_objects', 1, 'FILTERED', 'scope_to_tenant(model.all_objects.all(), request) per part; the other use is .none()'),
    ('apps/social/moderation_views.py', 'HandledContentViewSet.get_queryset', 'model.all_objects', 1, 'FILTERED', 'scope_to_tenant(model.all_objects.all(), request) per part; the other use is .none()'),
    ('apps/social/moderation_views.py', 'HandledContentViewSet.list', 'Post.all_objects', 1, 'PK', 'posts by pk taken from the already scoped page rows'),
    ('apps/social/moderation_views.py', 'HandledContentViewSet.list', 'PostMedia.all_objects', 1, 'PK', 'posts by pk taken from the already scoped page rows'),
    ('apps/social/moderation_views.py', 'ModeratedPostViewSet', 'PostMedia.all_objects', 1, 'PK', 'Prefetch of media for already scoped posts'),
    ('apps/social/moderation_views.py', 'ReportViewSet', 'PostMedia.all_objects', 1, 'PK', 'Prefetch of media for already scoped reports'),
    ('apps/social/moderation_views.py', 'SensitiveWordViewSet.copy_from', 'Tenant.objects', 1, 'CROSS', "officer copies another civilization's sensitive-word list into its own; source tenant is named by code, destination is the caller's tenant"),
    ('apps/soul_accounts/rebirth.py', 'eligibility', 'SentencePlan.all_objects', 1, 'PK', 'plan of one soul and cycle'),
    ('apps/soul_accounts/rebirth.py', 'decide_cross_civilization', 'ApprovalWorkflow._base_manager', 1, 'LOCK', 'locks the workflow row of an application already fetched by pk through the scoped path, before locking the application (lock order: workflow, then application)'),
    ('apps/soul_accounts/rebirth.py', 'submit', 'Soul.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/soul_accounts/services.py', '_ensure_soul_code', 'Soul.all_objects', 1, 'PK', 'writes soul_code of one soul by pk; code is globally unique (G5)'),
    ('apps/soul_accounts/services.py', 'provision_account', 'Soul.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/soul_accounts/views.py', 'OfficerCooldownShorteningViewSet._ordered', 'Tenant.objects', 1, 'FANOUT', "tenants of the already scoped request queryset (pk__in subquery), to read each one's cooldown setting"),
    ('apps/soul_assist/admin_views.py', 'HallDetailView.patch', 'Tenant.objects', 1, 'CROSS', 'ADMIN-only: locks one tenant row to flip its assistant setting'),
    ('apps/soul_assist/admin_views.py', '_halls', 'Tenant.objects', 1, 'CROSS', 'ADMIN-only halls list (assistant switch per tenant); view is ADMIN-gated'),
    ('apps/soul_assist/eval_identities.py', '_make_soul', 'SentencePlan.all_objects', 1, 'CLI', 'evaluation fixture builder: creates a plan for a soul it just made'),
    ('apps/soul_assist/eval_identities.py', '_tenant', 'Tenant.objects', 2, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/soul_assist/officer_tools.py', 'enabled_hall_ids', 'Tenant.objects', 1, 'CROSS', 'ADMIN assistant reads across halls that switched the assistant on (doc 1.3 item 12)'),
    ('apps/soul_assist/service.py', 'purge_history', 'AssistConversation.all_objects', 4, 'CLI', 'retention purge across all tenants (conversations of deleted/retired/deactivated users or empty)'),
    ('apps/soul_assist/usage.py', 'report', 'Tenant.objects', 1, 'CROSS', 'ADMIN usage report: maps tenant pks in the grouped usage rows to codes'),
    ('apps/soul_push/services.py', '_stale_approval', 'DispatchRecord._base_manager', 1, 'PK', 'dispatch looked up by the pk carried in the push dedupe key'),
    ('apps/souls/admin.py', 'SoulAdmin.save_model', 'Soul.all_objects', 1, 'PK', 'Django admin (superuser); reads the old email of the row being saved'),
    ('apps/souls/importer.py', '_flag_duplicates', 'Soul.all_objects', 1, 'FILTERED', 'explicit tenant=tenant'),
    ('apps/souls/management/commands/check_soul_dates.py', 'Command.handle', 'Soul.all_objects', 2, 'CLI', 'operator audit command over every tenant; optional soft-deleted rows'),
    ('apps/souls/management/commands/check_soul_dates.py', 'Command.handle', 'SoulRecord._base_manager', 2, 'CLI', 'operator audit command over every tenant; optional soft-deleted rows'),
    ('apps/souls/models.py', 'Soul.transition_to', 'Soul.all_objects', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/souls/record_models.py', 'SoulRecord._flush_karma_recalculations', 'Soul.all_objects', 1, 'PK', 'marks one soul by pk; the ids are the souls whose records this batch just created through the scoped path'),
    ('apps/souls/serializers.py', 'SoulRecordSerializer.validate_inferno_article', 'Statute.all_objects', 1, 'FILTERED', 'Statute looked up by code AND the soul tenant_id (Statute.code is unique per (tenant, code))'),
    ('apps/souls/views.py', 'SoulViewSet.batch_recycle', 'Soul.all_objects', 1, 'LOCK', 'locks souls by pk; ids were taken from the scoped queryset (see the view)'),
    ('apps/tenants/management/commands/reconcile_tenant_shadow.py', 'Command.handle', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/tenants/management/commands/reconcile_tenant_shadow.py', 'fingerprints', 'model._base_manager', 1, 'CLI', 'reconciliation tool: reads one database at a time, always filtered by the --tenant id; soft-deleted rows must be compared too'),
    ('apps/tenants/management/commands/seed_tenants.py', 'Command.handle', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/tenants/middleware.py', 'TenantMiddleware._resolve_tenant', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/tenants/views.py', 'TenantViewSet.get_queryset', 'Tenant.objects', 1, 'FILTERED', "wrapped in scope_to_tenant(field='pk')"),
    ('apps/workflow/management/commands/process_workflow_timeouts.py', 'Command.handle', 'Tenant.objects', 1, 'FANOUT', 'reads the global Tenant table to fan out per-tenant work'),
    ('apps/workflow/management/commands/seed_workflow_templates.py', 'Command.handle', 'Tenant.objects', 1, 'CLI', 'operator seed command: picks Tenant.objects.first() as the default owner of seeded templates (arbitrary tenant by design; not a request path)'),
    ('apps/workflow/models.py', 'ApprovalWorkflow._lock_and_reload', 'ApprovalWorkflow._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/workflow/services.py', 'WorkflowService._resolve_approver', 'Actor._base_manager', 1, 'FILTERED', 'explicit tenant_id=tenant_id'),
    ('apps/workflow/tasks.py', 'process_timeouts_for_tenant', 'Tenant.objects', 1, 'FANOUT', 'per-tenant subtask: loads its own tenant by the id it was handed, then filters every query by that tenant_id'),
    ('apps/workflow/timeouts.py', '_fire', 'ApprovalWorkflow._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/workflow/timeouts.py', 'candidates', 'ApprovalWorkflow._base_manager', 1, 'FILTERED', 'optional tenant_id filter; None means every tenant, used by the all-tenant management command only'),
    ('apps/workflow/versioning.py', '_adopt_unversioned', 'WorkflowTemplate._base_manager', 1, 'PK', 'updates one template by pk'),
    ('apps/workflow/versioning.py', 'publish', 'WorkflowTemplate._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/workflow/versioning.py', 'save_draft', 'WorkflowTemplate._base_manager', 1, 'LOCK', 're-reads or locks one row by pk that the caller already reached through a scoped path; all_objects only skips the soft-delete filter'),
    ('apps/workflow/views.py', 'ApprovalNodeViewSet.get_queryset', 'ApprovalNode._base_manager', 1, 'FILTERED', "scope_to_tenant(field='workflow__tenant')"),
    ('apps/workflow/views.py', 'ApprovalWorkflowViewSet.get_queryset', 'ApprovalWorkflow._base_manager', 1, 'FILTERED', 'unfiltered base manager, then tenant filtering for non-ADMIN callers'),
    ('apps/workflow/views.py', 'WorkflowTemplateViewSet.approver_preview', 'Tenant.objects', 1, 'FANOUT', 'resolves a Tenant by its globally unique code or id (Tenant has no tenant column; the lookup names exactly one row)'),
    ('apps/workflow/views.py', 'WorkflowTemplateViewSet.get_queryset', 'WorkflowTemplate._base_manager', 1, 'FILTERED', 'unfiltered base manager, then tenant filter below for non-ADMIN callers'),
]
