# Generated by Django 5.2.14 on 2026-05-08 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('souls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SOUL_CREATED', 'Soul Created'), ('STATE_CHANGED', 'State Changed'), ('RECORD_ADDED', 'Record Added'), ('JUDGMENT_INITIATED', 'Judgment Initiated'), ('JUDGMENT_CONCLUDED', 'Judgment Concluded'), ('DISPOSITION_CREATED', 'Disposition Created'), ('REINCARNATION_TRIGGERED', 'Reincarnation Triggered'), ('KARMA_RECALCULATED', 'Karma Recalculated')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('actor', models.CharField(blank=True, help_text='User or system', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='souls.soul')),
            ],
            options={
                'verbose_name': 'Soul Event',
                'verbose_name_plural': 'Soul Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
