# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_soulevent_tenant'),
        ('souls', '0009_add_approval_workflow_models'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soulevent',
            index=models.Index(fields=['soul', 'created_at'], name='events_soul_soul_id_f156cc_idx'),
        ),
        migrations.AddIndex(
            model_name='soulevent',
            index=models.Index(fields=['event_type'], name='events_soul_event_t_9ccad4_idx'),
        ),
        migrations.AddIndex(
            model_name='soulevent',
            index=models.Index(fields=['tenant', 'created_at'], name='events_soul_tenant__16d25d_idx'),
        ),
    ]
