# Generated by Django 5.2.14 on 2026-05-26 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_soulevent_delete_reason_soulevent_deleted_at_and_more'),
        ('souls', '0013_remove_soulrecord_souls_soulr_soul_id_922eb1_idx_and_more'),
        ('tenants', '0005_remove_notification_tenants_not_recipie_d638ec_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soulevent',
            options={'ordering': ['-create_time'], 'verbose_name': 'Soul Event', 'verbose_name_plural': 'Soul Events'},
        ),
        migrations.RemoveIndex(
            model_name='soulevent',
            name='events_soul_soul_id_f156cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='soulevent',
            name='events_soul_tenant__16d25d_idx',
        ),
        migrations.RemoveField(
            model_name='soulevent',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='soulevent',
            index=models.Index(fields=['soul', 'create_time'], name='events_soul_soul_id_683de6_idx'),
        ),
        migrations.AddIndex(
            model_name='soulevent',
            index=models.Index(fields=['tenant', 'create_time'], name='events_soul_tenant__c20e76_idx'),
        ),
    ]
