# Generated by Django 5.2.14 on 2026-05-30 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_soulevent_options_and_more'),
        ('tenants', '0006_notification_idx_notif_recip_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soulevent',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soul_events', to='tenants.tenant'),
        ),
    ]
