# Generated by Django 5.2.14 on 2026-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_soulevent_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soulevent',
            name='event_type',
            field=models.CharField(choices=[('SOUL_CREATED', 'Soul Created'), ('SOUL_DIED', 'Soul Died'), ('STATE_CHANGED', 'State Changed'), ('RECORD_ADDED', 'Record Added'), ('JUDGMENT_INITIATED', 'Judgment Initiated'), ('JUDGMENT_CONCLUDED', 'Judgment Concluded'), ('DISPOSITION_CREATED', 'Disposition Created'), ('REINCARNATION_TRIGGERED', 'Reincarnation Triggered'), ('KARMA_RECALCULATED', 'Karma Recalculated'), ('WORKFLOW_CREATED', 'Workflow Created'), ('WORKFLOW_ASSIGNED', 'Workflow Assigned'), ('WORKFLOW_APPROVED', 'Workflow Approved'), ('WORKFLOW_REJECTED', 'Workflow Rejected'), ('DISPATCH_CREATED', 'Dispatch Created'), ('DISPATCH_STATUS_CHANGED', 'Dispatch Status Changed'), ('DISPATCH_APPROVED', 'Dispatch Approved'), ('DISPATCH_REJECTED', 'Dispatch Rejected'), ('DISPATCH_EXECUTED', 'Dispatch Executed'), ('DEATH_SYNC_RECEIVED', 'Death Sync Received'), ('DEATH_SYNC_PROCESSED', 'Death Sync Processed')], max_length=30),
        ),
    ]
