# Generated by Django 5.2.14 on 2026-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_soulevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soulevent',
            name='event_type',
            field=models.CharField(choices=[('SOUL_CREATED', 'Soul Created'), ('STATE_CHANGED', 'State Changed'), ('RECORD_ADDED', 'Record Added'), ('JUDGMENT_INITIATED', 'Judgment Initiated'), ('JUDGMENT_CONCLUDED', 'Judgment Concluded'), ('DISPOSITION_CREATED', 'Disposition Created'), ('REINCARNATION_TRIGGERED', 'Reincarnation Triggered'), ('KARMA_RECALCULATED', 'Karma Recalculated'), ('WORKFLOW_CREATED', 'Workflow Created'), ('WORKFLOW_ASSIGNED', 'Workflow Assigned'), ('WORKFLOW_APPROVED', 'Workflow Approved'), ('WORKFLOW_REJECTED', 'Workflow Rejected'), ('DISPATCH_CREATED', 'Dispatch Created'), ('DISPATCH_APPROVED', 'Dispatch Approved'), ('DISPATCH_REJECTED', 'Dispatch Rejected'), ('DISPATCH_EXECUTED', 'Dispatch Executed'), ('DISPATCH_STATUS_CHANGED', 'Dispatch Status Changed'), ('DEATH_SYNC_RECEIVED', 'Death Sync Received'), ('DEATH_SYNC_PROCESSED', 'Death Sync Processed'), ('POST_CREATED', 'Post Created'), ('POST_UPDATED', 'Post Updated'), ('POST_DELETED', 'Post Deleted'), ('COMMENT_CREATED', 'Comment Created'), ('COMMENT_DELETED', 'Comment Deleted'), ('REACTION_ADDED', 'Reaction Added'), ('REACTION_REMOVED', 'Reaction Removed'), ('USER_FOLLOWED', 'User Followed'), ('USER_UNFOLLOWED', 'User Unfollowed')], max_length=30),
        ),
    ]
