# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_soulevent_event_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='soulevent',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
