# Generated by Django 5.2.16 on 2026-08-31 16:10

import uuid

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death_sync', '0005_remove_deathregistrationrequest_uniq_death_reg_idempotency_and_more'),
        ('events', '0013_notification_created_event_type'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWebhookDelivery',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('delete_cascade_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('payload_json', models.JSONField(help_text='投递的 envelope 快照。重试要发的是当时那一份,不是重新拼一份。')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Delivered'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned after max retries')], db_index=True, default='PENDING', max_length=20)),
                ('attempt', models.IntegerField(default=0)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_webhook_deliveries', to='tenants.tenant')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('webhook', models.ForeignKey(help_text='目标端点。租户自己配的,所以它的可靠性不在本系统控制内。', on_delete=django.db.models.deletion.CASCADE, related_name='event_deliveries', to='death_sync.webhookconfig')),
            ],
            options={
                'verbose_name': 'Event Webhook Delivery',
                'verbose_name_plural': 'Event Webhook Deliveries',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['status', 'create_time'], name='events_even_status_4a4f17_idx'), models.Index(fields=['tenant', 'event_type'], name='events_even_tenant__a72c97_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
