# Generated by Django 5.2.17 on 2026-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_soulevent_scheduler_run_failed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soulevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SOUL_CREATED", "Soul Created"),
                    ("STATE_CHANGED", "State Changed"),
                    ("SETTLEMENT_CORRECTED", "Settlement Corrected"),
                    ("RECORD_ADDED", "Record Added"),
                    ("JUDGMENT_INITIATED", "Judgment Initiated"),
                    ("JUDGMENT_CONCLUDED", "Judgment Concluded"),
                    ("DISPOSITION_CREATED", "Disposition Created"),
                    ("DISPOSITION_EXPIRED", "Disposition Expired"),
                    ("REINCARNATION_TRIGGERED", "Reincarnation Triggered"),
                    ("KARMA_RECALCULATED", "Karma Recalculated"),
                    ("WORKFLOW_CREATED", "Workflow Created"),
                    ("WORKFLOW_ASSIGNED", "Workflow Assigned"),
                    ("WORKFLOW_APPROVED", "Workflow Approved"),
                    ("WORKFLOW_REJECTED", "Workflow Rejected"),
                    ("DISPATCH_CREATED", "Dispatch Created"),
                    ("DISPATCH_APPROVED", "Dispatch Approved"),
                    ("DISPATCH_REJECTED", "Dispatch Rejected"),
                    ("DISPATCH_EXECUTED", "Dispatch Executed"),
                    ("DISPATCH_STATUS_CHANGED", "Dispatch Status Changed"),
                    ("DEATH_SYNC_RECEIVED", "Death Sync Received"),
                    ("DEATH_SYNC_PROCESSED", "Death Sync Processed"),
                    ("POST_CREATED", "Post Created"),
                    ("POST_UPDATED", "Post Updated"),
                    ("POST_DELETED", "Post Deleted"),
                    ("COMMENT_CREATED", "Comment Created"),
                    ("COMMENT_DELETED", "Comment Deleted"),
                    ("REACTION_ADDED", "Reaction Added"),
                    ("REACTION_REMOVED", "Reaction Removed"),
                    ("USER_FOLLOWED", "User Followed"),
                    ("USER_UNFOLLOWED", "User Unfollowed"),
                    ("NOTIFICATION_CREATED", "Notification Created"),
                    ("SOUL_ACCOUNT_CREATED", "Soul Account Created"),
                    ("SOUL_ACCOUNT_RETIRED", "Soul Account Retired"),
                    ("REBIRTH_APPLICATION_SUBMITTED", "Rebirth Application Submitted"),
                    ("REBIRTH_STATUS_CHANGED", "Rebirth Status Changed"),
                    ("REBIRTH_CROSS_CIV_DECIDED", "Rebirth Cross Civ Decided"),
                    ("SENTENCE_PLAN_CREATED", "Sentence Plan Created"),
                    ("SENTENCE_NODE_ACTIVATED", "Sentence Node Activated"),
                    ("SENTENCE_NODE_WAITING", "Sentence Node Waiting"),
                    ("SENTENCE_NODE_COMPLETED", "Sentence Node Completed"),
                    ("SENTENCE_NODE_REFUSED", "Sentence Node Refused"),
                    ("SENTENCE_PLAN_AMENDED", "Sentence Plan Amended"),
                    ("SENTENCE_REQUEST_CREATED", "Sentence Request Created"),
                    ("SENTENCE_REQUEST_DECIDED", "Sentence Request Decided"),
                    ("SENTENCE_PLAN_COMPLETED", "Sentence Plan Completed"),
                    ("SENTENCE_PLAN_CANCELLED", "Sentence Plan Cancelled"),
                    ("SCHEDULER_RUN_FAILED", "Scheduler Run Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
