/**
 * 手写的字符串联合 == 生成的 schema 枚举。
 *
 * 为什么这些联合还留着手写形式。`packages/core/src/api/generated/schema.ts` 里
 * **已经**有每一个枚举的字面量联合,直接 `export type UserRole =
 * components["schemas"]["UserRoleEnum"]` 是更少的字。不这么做的理由是
 * `domainDisplayContract.test.tsx`:它靠正则扫 `packages/core/src/api/*.ts` 里
 * 形如 `field: "A" | "B"` 的行来推导自己的**主体清单**,别名对那条正则是隐形的。
 * 换成别名,那份契约测试会继续跑、继续能报红,而它看的集合会悄悄缩小 ——
 * commit `4051e51` 记的就是这个形状:「规则会跑、能报红、但主体清单选错了」。
 *
 * 所以字面量留下,漂移改由这个文件抓。两边都在,而且必须相等。
 *
 * 这不是假设性的。写这个文件的同一轮里,它抓到的第一件事是
 * `UserRole` 少了 `MODERATOR` —— 而这个仓库为 MODERATOR 已经栽过至少三次
 * (`apps/authentication/models.py` 的类文档、`app/users/page.tsx:126`、
 * `app/audit/page.tsx:59` 各记了一次)。每一次都在**发现它的那个地方**修好了;
 * 这个共享类型是最后一份还短一个成员的副本。修它又当场暴露出第三份拷贝:
 * `src/contexts/TenantContext.tsx` 里内联的同一个四成员联合。
 */
import { readFileSync } from "node:fs";
import path from "node:path";

const REPO_ROOT = path.join(__dirname, "..", "..", "..");
const API_DIR = path.join(REPO_ROOT, "packages", "core", "src", "api");
const GENERATED = path.join(API_DIR, "generated", "schema.ts");

/** 手写声明 → 生成的组件名。
 *
 *  新增一条的判据:这个联合描述的是后端某个 TextChoices,而 schema 里有它。
 *  不在这张表里的联合(例如 `ledger.ts` 里那些从 `as const` 数组派生的)没有
 *  schema 对应物 —— 它们的端点在那 27 个无法内省的 view 里,见
 *  `backend/tests/test_schema_has_no_warnings.py`。 */
const PAIRS: { decl: string; file: string; component: string }[] = [
  { decl: "UserRole", file: "auth.ts", component: "UserRoleEnum" },
  { decl: "StatuteCorpus", file: "judgment.ts", component: "CorpusEnum" },
  { decl: "StatutePolarity", file: "judgment.ts", component: "PolarityEnum" },
];

/** 内联在某个字段上的联合(没有具名 type),按 `组件.字段` 定位。 */
const INLINE: { file: string; field: string; component: string }[] = [
  { file: "judgment.ts", field: "verdict", component: "VerdictEnum" },
  {
    file: "workflow.ts",
    field: "approver_type",
    component: "WorkflowTemplateNodeApproverTypeEnum",
  },
  {
    file: "workflow.ts",
    field: "node_type",
    component: "WorkflowTemplateNodeNodeTypeEnum",
  },
  { file: "menus.ts", field: "menu_type", component: "MenuTypeEnum" },
];

function members(source: string): string[] {
  return [...source.matchAll(/"([A-Z_][A-Z0-9_]*)"/g)].map((m) => m[1]).sort();
}

function generatedEnum(name: string): string[] {
  const src = readFileSync(GENERATED, "utf8");
  const m = new RegExp(`^        ${name}: (.*?);$`, "m").exec(src);
  if (m === null) {
    throw new Error(
      `no component \`${name}\` in the generated schema. Either the backend ` +
        `renamed it (check ENUM_NAME_OVERRIDES in config/settings.py) or this ` +
        `entry is stale — do not delete it without checking, that would stop ` +
        `a real union from being compared.`
    );
  }
  return members(m[1]);
}

function declaredUnion(file: string, decl: string): string[] {
  const src = readFileSync(path.join(API_DIR, file), "utf8");
  const m = new RegExp(`^export type ${decl} =([\\s\\S]*?);$`, "m").exec(src);
  if (m === null) throw new Error(`no \`export type ${decl}\` in ${file}`);
  return members(m[1]);
}

function inlineUnion(file: string, field: string): string[] {
  const src = readFileSync(path.join(API_DIR, file), "utf8");
  const m = new RegExp(`^\\s*${field}\\??: ("[A-Z_]+"(?:\\s*\\|\\s*"[A-Z_]+")+)`, "m").exec(src);
  if (m === null) throw new Error(`no inline union on \`${field}\` in ${file}`);
  return members(m[1]);
}

describe("这些比较有主体", () => {
  it("生成文件读得到,而且不是空的", () => {
    // 路径写错时,下面每一条都会抛而不是绿 —— 但先在这里说清楚。
    const src = readFileSync(GENERATED, "utf8");
    expect(src.length).toBeGreaterThan(100_000);
    expect(src).toContain("This file was auto-generated by openapi-typescript");
  });

  it("要比的对子数量不为零", () => {
    expect(PAIRS.length + INLINE.length).toBeGreaterThanOrEqual(6);
  });
});

describe("具名联合与 schema 枚举成员相同", () => {
  it.each(PAIRS)("$decl == $component", ({ decl, file, component }) => {
    expect({ [decl]: declaredUnion(file, decl) }).toEqual({
      [decl]: generatedEnum(component),
    });
  });
});

describe("内联联合与 schema 枚举成员相同", () => {
  it.each(INLINE)("$file::$field == $component", ({ file, field, component }) => {
    expect({ [field]: inlineUnion(file, field) }).toEqual({
      [field]: generatedEnum(component),
    });
  });
});
