# Generated by Django 5.2.14 on 2026-05-27 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_delete_reason_menu_deleted_at_menu_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cache',
            field=models.BooleanField(default=True, help_text='是否缓存该菜单'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('DIRECTORY', '目录'), ('MENU', '菜单'), ('BUTTON', '按钮')], default='MENU', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='permission',
            field=models.CharField(blank=True, default='', help_text='权限 codename，如 soul.read、judgment.create', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='visible',
            field=models.BooleanField(default=True, help_text='是否在侧边栏显示'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('name', models.CharField(help_text='按钮显示名称', max_length=100)),
                ('code', models.CharField(help_text='按钮编码，如 add/edit/delete/export', max_length=50)),
                ('permission', models.CharField(help_text='权限 codename，如 soul.create、judgment.delete', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='menus.menu')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Button',
                'verbose_name_plural': 'Menu Buttons',
                'ordering': ['order', 'id'],
                'unique_together': {('menu', 'code')},
            },
        ),
    ]
