# Generated by Django 5.2.14 on 2026-06-04 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menu_cache_menu_menu_type_menu_permission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['parent', 'is_active', 'order'], name='idx_menu_parent_active_order'),
        ),
    ]
