# Generated by Django 5.2.14 on 2026-06-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menu_idx_menu_parent_active_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menu',
            name='idx_menu_parent_active_order',
        ),
    ]
