# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_add_social_menu'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menu',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='menubutton',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
