# Generated by Django 5.2.16 on 2026-08-29 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_add_corpus_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menubutton',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='menubutton',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('menu', 'code'), name='unique_menubutton_menu_code'),
        ),
    ]
