# Generated by Django 5.2.14 on 2026-05-08 07:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disposition', '0001_initial'),
        ('souls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reincarnation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_realm', models.CharField(max_length=100)),
                ('rebirth_form', models.CharField(choices=[('HUMAN', 'Human'), ('ANIMAL', 'Animal'), ('DIVINE', 'Divine Being'), ('OTHER', 'Other')], default='HUMAN', max_length=20)),
                ('cycle_count', models.IntegerField(default=1)),
                ('previous_realm', models.CharField(blank=True, max_length=100)),
                ('new_identity', models.CharField(blank=True, help_text='Name in new life', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('reincarnated_at', models.DateTimeField(auto_now_add=True)),
                ('disposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reincarnations', to='disposition.disposition')),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reincarnations', to='souls.soul')),
            ],
            options={
                'verbose_name': 'Reincarnation',
                'verbose_name_plural': 'Reincarnations',
                'ordering': ['-reincarnated_at'],
            },
        ),
    ]
