# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reincarnation', '0003_reincarnation_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reincarnation',
            name='idx_reinc_tenant_cycle',
        ),
        migrations.RemoveIndex(
            model_name='reincarnation',
            name='idx_reinc_soul_reincarnated',
        ),
    ]
