# Generated by Django 5.2.14 on 2026-05-10 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0006_disposition_delete_reason_disposition_deleted_at_and_more'),
        ('reincarnation', '0005_reincarnation_create_time_reincarnation_create_user_and_more'),
        ('souls', '0012_soul_delete_reason_soul_deleted_at_soul_deleted_by_and_more'),
        ('tenants', '0004_notification_delete_reason_notification_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reincarnation',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='reincarnation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reincarnation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reincarnation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reincarnation',
            name='sort_code',
            field=models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists'),
        ),
        migrations.AddField(
            model_name='reincarnation',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='reincarnation',
            index=models.Index(fields=['tenant', 'soul'], name='reincarnati_tenant__d0f53c_idx'),
        ),
        migrations.AddIndex(
            model_name='reincarnation',
            index=models.Index(fields=['tenant', 'reincarnated_at'], name='reincarnati_tenant__74a0bd_idx'),
        ),
    ]
