# Generated by Django 5.2.14 on 2026-05-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reincarnation', '0006_reincarnation_delete_reason_reincarnation_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reincarnation',
            name='reincarnati_tenant__d0f53c_idx',
        ),
        migrations.RemoveIndex(
            model_name='reincarnation',
            name='reincarnati_tenant__74a0bd_idx',
        ),
    ]
