# Generated by Django 5.2.14 on 2026-06-04 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0006_disposition_delete_reason_disposition_deleted_at_and_more'),
        ('reincarnation', '0007_remove_reincarnation_reincarnati_tenant__d0f53c_idx_and_more'),
        ('souls', '0017_soulrecord_idx_soulrecord_type_and_more'),
        ('tenants', '0006_notification_idx_notif_recip_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reincarnation',
            index=models.Index(fields=['soul', 'tenant'], name='idx_reincarn_soul_tenant'),
        ),
    ]
