# Generated by Django 5.2.14 on 2026-06-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reincarnation', '0008_reincarnation_idx_reincarn_soul_tenant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reincarnation',
            name='idx_reincarn_soul_tenant',
        ),
    ]
