# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reincarnation', '0009_remove_reincarnation_idx_reincarn_soul_tenant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reincarnation',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
