# Generated by Django 5.2.16 on 2026-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reincarnation", "0011_reincarnation_delete_cascade_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reincarnation",
            name="rebirth_form",
            field=models.CharField(
                choices=[
                    ("DIVINE", "Deva (Heaven Path)"),
                    ("HUMAN", "Human (Human Path)"),
                    ("ASURA", "Asura (Demigod Path)"),
                    ("ANIMAL", "Animal (Beast Path)"),
                    ("HUNGRY_GHOST", "Hungry Ghost"),
                    ("HELL_BEING", "Hell Being"),
                    ("OTHER", "Other (Unclassified)"),
                ],
                default="HUMAN",
                max_length=20,
            ),
        ),
    ]
