# Generated by Django 5.2.16 on 2026-08-31 06:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0012_arithmetic_fields_get_bounds'),
        ('reincarnation', '0012_alter_reincarnation_rebirth_form'),
        ('souls', '0032_soulrecord_civilization_help_text'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reincarnation',
            name='cycle_count',
            field=models.IntegerField(default=1, help_text='Which turn of the wheel this is; the first rebirth is 1.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='reincarnation',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_count__gte', 1)), name='reincarnation_cycle_count_at_least_one'),
        ),
    ]
