# Generated by Django 5.2.14 on 2026-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_delete_reason_auditlog_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('EXECUTE', '执行'), ('READ', '读取'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('VIEW', '查看'), ('EXPORT', '导出'), ('IMPORT', '导入'), ('PERMISSION_CHANGE', '权限变更'), ('BATCH_CREATE', '批量创建'), ('BATCH_UPDATE', '批量更新'), ('BATCH_DELETE', '批量删除')], max_length=20),
        ),
    ]
