# Generated by Django 5.2.14 on 2026-05-27 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
        ('tenants', '0005_remove_notification_tenants_not_recipie_d638ec_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='请求追踪ID，关联同一HTTP请求内的多个操作', max_length=64),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['trace_id'], name='audit_audit_trace_i_a4e590_idx'),
        ),
    ]
