# Generated by Django 5.2.16 on 2026-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0009_fold_camelcase_resource_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
