# Generated by Django 5.2.14 on 2026-05-08 07:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('realm_code', models.CharField(max_length=50, unique=True)),
                ('civilization', models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat')], max_length=20)),
                ('name_local', models.CharField(help_text='Native name, e.g. 奈何狱', max_length=255)),
                ('name_en', models.CharField(help_text='English name', max_length=255)),
                ('realm_type', models.CharField(choices=[('HELL', 'Hell / Punishment'), ('PURGATORY', 'Purgatory / Intermediate'), ('BLISS', 'Heaven / Bliss'), ('NEUTRAL', 'Neutral / Between')], max_length=20)),
                ('tier', models.IntegerField(default=1, help_text='Severity or bliss tier (1=most severe, higher=less severe for HELL; reversed for BLISS)')),
                ('description', models.TextField(blank=True)),
                ('memory_reset_mechanism', models.CharField(blank=True, max_length=100)),
                ('is_eternal', models.BooleanField(default=False)),
                ('cycle_limit', models.IntegerField(blank=True, help_text='Max reincarnation cycles before forced progression', null=True)),
                ('parent_realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_realms', to='realms.realm')),
            ],
            options={
                'verbose_name': 'Realm',
                'verbose_name_plural': 'Realms',
                'ordering': ['civilization', 'realm_type', 'tier'],
            },
        ),
    ]
