# Generated by Django 5.2.14 on 2026-05-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='name_egy',
            field=models.CharField(blank=True, help_text='Egyptian name (transliteration or hieroglyphs)', max_length=255),
        ),
        migrations.AddField(
            model_name='realm',
            name='name_zh',
            field=models.CharField(blank=True, help_text='Simplified Chinese name', max_length=255),
        ),
        migrations.AlterField(
            model_name='realm',
            name='cycle_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name', max_length=255),
        ),
        migrations.AlterField(
            model_name='realm',
            name='name_local',
            field=models.CharField(help_text='Native/local name', max_length=255),
        ),
        migrations.AlterField(
            model_name='realm',
            name='tier',
            field=models.IntegerField(default=1, help_text='Severity or bliss tier'),
        ),
    ]
