# Generated by Django 5.2.14 on 2026-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_realm_name_egy_realm_name_zh_alter_realm_cycle_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='is_judgment_required',
            field=models.BooleanField(default=True, help_text='Whether this realm requires a formal judgment process before entry'),
        ),
    ]
