# Generated by Django 5.2.14 on 2026-05-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0003_realm_is_judgment_required'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realms', to='tenants.tenant'),
        ),
    ]
