# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0004_realm_tenant'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='realm',
            index=models.Index(fields=['civilization', 'realm_type'], name='realms_real_civiliz_bf9570_idx'),
        ),
        migrations.AddIndex(
            model_name='realm',
            index=models.Index(fields=['tenant', 'civilization'], name='realms_real_tenant__f7ec94_idx'),
        ),
        migrations.AddIndex(
            model_name='realm',
            index=models.Index(fields=['realm_code'], name='realms_real_realm_c_ab37b0_idx'),
        ),
    ]
