# Generated by Django 5.2.14 on 2026-05-10 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0006_realm_create_time_realm_create_user_and_more'),
        ('tenants', '0004_notification_delete_reason_notification_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='realm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realm',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='realm',
            name='sort_code',
            field=models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists'),
        ),
        migrations.AddField(
            model_name='realm',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='realm',
            index=models.Index(fields=['realm_type'], name='realms_real_realm_t_19616e_idx'),
        ),
        migrations.AddIndex(
            model_name='realm',
            index=models.Index(fields=['is_judgment_required'], name='realms_real_is_judg_474c18_idx'),
        ),
    ]
