# Generated by Django 5.2.14 on 2026-05-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0007_realm_delete_reason_realm_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='realm',
            name='realms_real_realm_t_19616e_idx',
        ),
        migrations.RemoveIndex(
            model_name='realm',
            name='realms_real_is_judg_474c18_idx',
        ),
    ]
