# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0008_remove_realm_realms_real_realm_t_19616e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realm',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
