# Generated by Django 5.2.17 on 2026-09-24 14:25

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realms", "0018_split_greek_from_european"),
        ("souls", "0036_soul_home_tenant"),
        ("tenants", "0012_default_hall_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many souls the realm holds at once; null = not recorded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="fork",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEFT", "左(塔尔塔罗斯)"),
                    ("MIDDLE", "中"),
                    ("RIGHT", "右(至福岛)"),
                ],
                help_text="Greek only: which road out of the judgment place",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="gate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Egyptian only: gate number",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="hour",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Egyptian only: hour of the night, 1-12",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="is_judgment_hall",
            field=models.BooleanField(
                blank=True,
                help_text="Egyptian only: the hall where the heart is weighed; null elsewhere",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HALL", "殿"),
                    ("GATE", "门"),
                    ("LAYER", "层"),
                    ("PATH", "道"),
                ],
                help_text="Chinese only: 殿 / 门 / 层 / 道",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="European only: circle (Inferno) or terrace (Purgatorio) number",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Position along the civilization's route (Chinese: court number 1-10)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INFERNO", "地狱"),
                    ("PURGATORIO", "炼狱"),
                    ("PARADISO", "天堂"),
                ],
                help_text="European only: which cantica the realm belongs to",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realm",
            name="sublevel",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="European only: ring (7th circle) or bolgia (8th circle) number",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.CreateModel(
            name="SoulPathEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="1-based position in the soul's path"
                    ),
                ),
                ("entered_at", models.DateTimeField()),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "realm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="path_entries",
                        to="realms.realm",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_entries",
                        to="souls.soul",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul_path_entries",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soul path entry",
                "verbose_name_plural": "Soul path entries",
                "ordering": ["soul", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "soul"], name="realms_soul_tenant__52f557_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("soul", "sequence"), name="soulpath_unique_sequence"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("left_at__isnull", True)),
                        fields=("soul",),
                        name="soulpath_one_open_entry_per_soul",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("left_at__isnull", True),
                            ("left_at__gte", models.F("entered_at")),
                            _connector="OR",
                        ),
                        name="soulpath_left_not_before_entered",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
