# Generated by Django 5.2.17 on 2026-09-17 15:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("soul_accounts", "0002_rebirth_first_rejection"),
        ("souls", "0036_soul_home_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("IOS", "iOS"), ("ANDROID", "Android")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "invalid_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNREGISTERED", "灵魂注销"),
                            ("ACCOUNT_RETIRED", "账号转世停用"),
                            ("DEVICE_NOT_REGISTERED", "Expo 回报设备未注册"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("last_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to="soul_accounts.soulaccount",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to="souls.soul",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=120)),
                ("event_type", models.CharField(max_length=40)),
                ("kind", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=120)),
                ("body", models.CharField(max_length=300)),
                ("data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "待发送"),
                            ("SENDING", "发送中"),
                            ("SENT", "已交给 Expo"),
                            ("DELIVERED", "回执成功"),
                            ("FAILED", "失败"),
                            ("DISABLED", "推送未启用"),
                            ("EXPIRED", "已过期"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("ticket_id", models.CharField(blank=True, default="", max_length=64)),
                ("error", models.CharField(blank=True, default="", max_length=200)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True, help_text="可重试失败后的退避到期时刻", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_deliveries",
                        to="soul_accounts.soulaccount",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_deliveries",
                        to="souls.soul",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="soul_push.pushdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rebirth",
                    models.BooleanField(
                        default=True, help_text="转生申请:提交确认、申诉确认、结果"
                    ),
                ),
                (
                    "judgment",
                    models.BooleanField(default=True, help_text="审判结论与处置执行"),
                ),
                (
                    "residence",
                    models.BooleanField(
                        default=True,
                        help_text="暂居开始 / 回归(依赖 feat/dispatch-residence)",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("zh-Hans", "简体中文"),
                            ("en", "English"),
                            ("egy", "Medu Netjer"),
                        ],
                        default="zh-Hans",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_preference",
                        to="soul_accounts.soulaccount",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_preferences",
                        to="souls.soul",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pushdevice",
            index=models.Index(
                fields=["account", "is_active"], name="soul_push_p_account_1f3a26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushdelivery",
            index=models.Index(
                fields=["status", "created_at"], name="soul_push_p_status_be431e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushdelivery",
            index=models.Index(
                fields=["status", "sent_at"], name="soul_push_p_status_8415b3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pushdelivery",
            constraint=models.UniqueConstraint(
                fields=("dedupe_key", "device"), name="push_delivery_once_per_device"
            ),
        ),
    ]
