# Generated by Django 5.2.17 on 2026-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soul_push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushpreference',
            name='chat',
            field=models.BooleanField(default=True, help_text='新书信:私聊的新消息、殿司的回信'),
        ),
    ]
