# Generated by Django 5.2.17 on 2026-10-08 11:02

import django.db.models.deletion
from django.db import migrations, models


def drop_deviceless_rows(apps, schema_editor):
    """反向时 `device` 要变回非空:没有设备的历史行(NO_DEVICE)先删,它们本来就从未发送过。"""
    alias = schema_editor.connection.alias
    apps.get_model("soul_push", "PushDelivery").objects.using(alias).filter(device__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("soul_accounts", "0005_cooldown_shortening"),
        ("soul_push", "0002_preference_chat"),
        ("souls", "0036_soul_home_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushdelivery",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="soul_push.pushdevice",
            ),
        ),
        migrations.AlterField(
            model_name="pushdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "待发送"),
                    ("SENDING", "发送中"),
                    ("SENT", "已交给 Expo"),
                    ("DELIVERED", "回执成功"),
                    ("FAILED", "失败"),
                    ("DISABLED", "推送未启用"),
                    ("EXPIRED", "已过期"),
                    ("CANCELLED", "已取消"),
                    ("NO_DEVICE", "没有设备"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="pushdelivery",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device__isnull", True)),
                fields=("dedupe_key", "account"),
                name="push_delivery_once_without_device",
            ),
        ),
        # 放在最后:反向时它最先跑,先清掉没有设备的行,再撤约束、把 device 改回非空。
        migrations.RunPython(migrations.RunPython.noop, drop_deviceless_rows),
    ]
