# Generated by Django 5.2.14 on 2026-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Display name shown in the navbar (e.g. 系统管理员)', max_length=100),
        ),
    ]
