# Generated by Django 5.2.14 on 2026-05-13 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='authenticat_tenant__4e17a5_idx',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_5dd3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['username', 'timestamp'], name='authenticat_usernam_5ce5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['status', 'timestamp'], name='authenticat_status_8760f7_idx'),
        ),
    ]
