# Generated by Django 5.2.14 on 2026-05-16 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_login_log'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='所属组织：如 第一殿、冥王厅', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='org.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', help_text='职位：如 第一殿殿主', max_length=100),
        ),
    ]
