# Generated by Django 5.2.14 on 2026-05-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_organization_and_position'),
        ('perm', '0011_fieldpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rbac_role',
            field=models.ForeignKey(blank=True, help_text='RBAC role with hierarchy and permission inheritance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='perm.role'),
        ),
    ]
