# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations

import apps.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_loginlog_create_time_loginlog_create_user_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginlog',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('all_objects', django.contrib.auth.models.UserManager()),
                ('objects', apps.authentication.models.SoftDeleteUserManager()),
            ],
        ),
    ]
