# Generated by Django 5.2.16 on 2026-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_loginlog_managers_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginlog",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
