# Generated by Django 5.2.16 on 2026-08-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_loginlog_delete_cascade_id_user_delete_cascade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator (阎罗王)'), ('MODERATOR', 'Realm Lead (殿主)'), ('JUDGE', 'Judge (判官)'), ('GUARDIAN', 'Guardian (牛头马面)'), ('VIEWER', 'Viewer (访客)')], default='VIEWER', max_length=20),
        ),
    ]
