# Generated by Django 5.2.16 on 2026-09-12 02:28

from django.db import migrations, models

import apps.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                default="VIEWER",
                max_length=20,
                validators=[apps.authentication.models.validate_assignable_role],
            ),
        ),
    ]
