# Generated by Django 5.2.16 on 2026-09-12 09:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0012_retire_the_pantheon_the_corpus_does_not_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0015_role_is_validated_against_the_role_table"),
        ("org", "0009_recompute_organization_levels"),
        ("perm", "0020_role_and_permission_unique_among_live_rows"),
        ("tenants", "0009_drop_dead_cross_tenant_permission_table"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(
                    ("is_deleted", False), models.Q(("email", ""), _negated=True)
                ),
                name="unique_user_email_among_live_rows",
            ),
        ),
    ]
