# Generated by Django 5.2.17 on 2026-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_email_is_unique_among_live_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
