# Generated by Django 5.2.17 on 2026-10-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_officer_mfa"),
        ("authentication", "0019_user_extra_roles"),
    ]

    operations = []
