# Generated by Django 5.2.17 on 2026-10-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_merge_0019_officer_mfa_0019_user_extra_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_address",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
