# Generated by Django 5.2.17 on 2026-09-16 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("tenants", "0010_drop_dead_notification_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_key", models.CharField(db_index=True, max_length=200)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_alerted_at", models.DateTimeField(blank=True, null=True)),
                ("overdue_alerted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "periodic_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_job",
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_jobs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant__code", "job_key"],
            },
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=200)),
                ("celery_task_id", models.CharField(max_length=64, unique=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("SCHEDULE", "Schedule"), ("MANUAL", "Manual")],
                        default="SCHEDULE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("RETRY", "Retry"),
                            ("SKIPPED", "Skipped"),
                            ("LOST", "Lost"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "worker_hostname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("result", models.CharField(blank=True, default="", max_length=500)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="scheduler.scheduledjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_runs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "-queued_at"], name="taskrun_job_queued"
                    ),
                    models.Index(
                        fields=["task_name", "-queued_at"], name="taskrun_task_queued"
                    ),
                ],
            },
        ),
    ]
