/**
 * v2「朱印」: the seal and the plaque's ornament band (规范 v2 定稿 §印 / §匾, 补足 A6).
 *
 * A seal is four layers, bottom up: the body in 匾色 → the ring (between the outer
 * shape and the thick frame) showing the civilization's edge scan → the frame lines in
 * onPlaque → the glyph, in a real font. At ≤ 32pt the ring, the fine frame and the
 * dots go (`line-small` keeps only the thick frame). The drawings are Design's files
 * (`art.ts`, generated by `scripts/import-v2-art.mjs`); nothing here redraws them.
 *
 * The glyph is data — `tenant.seal_glyphs`, 1–2 characters an admin sets — and when
 * that is empty, the civilization's default. It is never translated: a seal is an
 * object, not interface text. A screen reader hears the language pack's
 * 「第五殿之印」 (`seal.aria`), never the glyph.
 */
import { Image, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import Animated from "react-native-reanimated";
import Svg, { ClipPath, Defs, Image as SvgImage, Path, SvgXml } from "react-native-svg";
import { useId, type ComponentProps } from "react";

import { RING_D, SVG } from "./art";
import { family } from "./fonts";
import type { CivKey, Theme } from "./theme";

export type SealCiv = Exclude<CivKey, "neutral">;

/** 补足 A6: 冥 · J (Justitia) · 𓆄 U+13184 (玛特之羽) · Μ U+039C (米诺斯). */
export const DEFAULT_GLYPHS: Record<SealCiv, string> = { cn: "冥", eu: "J", eg: "\u{13184}", gr: "Μ" };

/** §印 字号系数, calibrated so the glyph's ink covers 35–45% of the seal's heart. */
const GLYPH_SCALE: Record<SealCiv, number> = { cn: 0.54, eu: 0.42, eg: 0.68, gr: 0.5 };
/** Two hieroglyphs stack, each at 0.46 — the only two-glyph seal. */
const EG_PAIR_SCALE = 0.46;
/** The cartouche's inner frame is centred at y 30.5 of 64, not 32; its glyphs sit there. */
const EG_CENTRE_SHIFT = (30.5 - 32) / 64;

const SCAN: Record<SealCiv, number> = {
  cn: require("../assets/v2/scan-cnseal.png"),
  eu: require("../assets/v2/scan-wax.png"),
  eg: require("../assets/v2/scan-clay.png"),
  gr: require("../assets/v2/scan-cyl.png"),
};

/**
 * What a seal shows: the tenant's glyphs when they are usable, else the default.
 * Usable = one glyph, or two for 杜阿特 only (A6: 只有埃及允许 2). The server
 * validates the same rule; this is the fallback for anything that slips past it.
 */
export function sealGlyphs(civ: SealCiv, glyphs: readonly string[] | null | undefined): string[] {
  const max = civ === "eg" ? 2 : 1;
  return glyphs && glyphs.length >= 1 && glyphs.length <= max && glyphs.every(Boolean) ? [...glyphs] : [DEFAULT_GLYPHS[civ]];
}

/** The neutral seal (补足 C16: the app icon's — ink, three ledger lines, no glyph): before sign-in. */
const NEUTRAL_BODY = "M8 8.4L56.3 7.8L56.6 56.4L8.3 56.8Z";
const NEUTRAL_LINES = "M13 13H51V51H13ZM19 24H45M19 32H45M19 40H45";

export function Seal({
  civ,
  size,
  theme,
  glyphs,
  label,
  testID,
  ringStyle,
}: {
  civ: CivKey;
  size: number;
  /** For its 匾色 and onPlaque — the seal is one of the five places the plaque colour goes. */
  theme: Pick<Theme, "plaque" | "onPlaque">;
  glyphs?: readonly string[] | null;
  /** 「第五殿之印」, from `seal.aria`. Absent: the seal is decoration beside words that say the same. */
  label?: string;
  testID?: string;
  /** The edge scan's layer — an animated style: the ink soaking into the paper as a seal lands (印泥晕开). */
  ringStyle?: ComponentProps<typeof Animated.View>["style"];
}) {
  // useId gives «:r1:»; a colon does not survive `url(#…)`.
  const clip = `seal${useId().replace(/[^A-Za-z0-9]/g, "")}`;
  const box = { width: size, height: size };
  const a11y = label
    ? { accessible: true, accessibilityRole: "image" as const, accessibilityLabel: label }
    : { accessibilityElementsHidden: true, importantForAccessibility: "no-hide-descendants" as const };
  if (civ === "neutral") {
    return (
      <View testID={testID} style={box} {...a11y}>
        <Svg width={size} height={size} viewBox="0 0 64 64">
          <Path d={NEUTRAL_BODY} fill={theme.plaque} />
          <Path d={NEUTRAL_LINES} fill="none" stroke={theme.onPlaque} strokeWidth={1.8} />
        </Svg>
      </View>
    );
  }
  const small = size <= 32;
  const shown = sealGlyphs(civ, glyphs);
  const pair = shown.length === 2;
  const fontSize = Math.round(size * (pair ? EG_PAIR_SCALE : GLYPH_SCALE[civ]));
  return (
    <View testID={testID} style={box} {...a11y}>
      <SvgXml xml={SVG[`seal-${civ}-body`]} color={theme.plaque} width={size} height={size} style={StyleSheet.absoluteFill} />
      {small ? null : (
        <Animated.View testID={testID && `${testID}-ring-layer`} style={[StyleSheet.absoluteFill, ringStyle]}>
          <Svg width={size} height={size} viewBox="0 0 64 64">
            <Defs>
              <ClipPath id={clip}>
                <Path d={RING_D[civ]} clipRule="evenodd" />
              </ClipPath>
            </Defs>
            <SvgImage testID={testID && `${testID}-ring`} href={SCAN[civ]} width={64} height={64} clipPath={`url(#${clip})`} />
          </Svg>
        </Animated.View>
      )}
      <SvgXml
        xml={SVG[small ? (`seal-${civ}-line-small` as const) : (`seal-${civ}-line` as const)]}
        color={theme.onPlaque}
        width={size}
        height={size}
        style={StyleSheet.absoluteFill}
      />
      <View style={[styles.glyphs, civ === "eg" && { transform: [{ translateY: size * EG_CENTRE_SHIFT }] }]}>
        {shown.map((g, i) => (
          <Text
            key={i}
            testID={testID && `${testID}-glyph`}
            allowFontScaling={false}
            style={[styles.glyph, { fontFamily: family.seal[civ], fontSize, lineHeight: fontSize, color: theme.onPlaque }]}
          >
            {g}
          </Text>
        ))}
      </View>
    </View>
  );
}

/** Each band's ground texture (§匾 质感): paper, papyrus, marble; `-w` (white grain only) in dark. */
const TEXTURE: Record<SealCiv, Record<"light" | "dark", number>> = {
  cn: { light: require("../assets/v2/paper.png"), dark: require("../assets/v2/paper-w.png") },
  eu: { light: require("../assets/v2/paper.png"), dark: require("../assets/v2/paper-w.png") },
  eg: { light: require("../assets/v2/papyrus.png"), dark: require("../assets/v2/papyrus-w.png") },
  gr: { light: require("../assets/v2/marble.png"), dark: require("../assets/v2/marble-w.png") },
};

/** One period of every band is 480 wide. */
const BAND_PERIOD = 480;
/** §匾 纹样带: ≤ 393 wide uses the compact drawing (no dots; 杜阿特 also loses the lotus fans). */
const COMPACT_MAX = 393;

/**
 * The plaque's 22pt ornament band, in onPlaque, tiled across the screen, with the
 * civilization's texture over it — dark mode's white-grain variant at 60%.
 */
export function PlaqueBand({ civ, theme }: { civ: SealCiv; theme: Pick<Theme, "onPlaque" | "scheme"> }) {
  const { width } = useWindowDimensions();
  const xml = SVG[width <= COMPACT_MAX ? (`band-${civ}-compact` as const) : (`band-${civ}` as const)];
  return (
    <View testID={`plaque-band-${civ}`} style={styles.band} pointerEvents="none">
      <View style={styles.tiles}>
        {Array.from({ length: Math.ceil(width / BAND_PERIOD) }, (_, i) => (
          <SvgXml key={i} xml={xml} color={theme.onPlaque} width={BAND_PERIOD} height={22} />
        ))}
      </View>
      <Image
        source={TEXTURE[civ][theme.scheme]}
        resizeMode="repeat"
        style={[StyleSheet.absoluteFill, { opacity: theme.scheme === "dark" ? 0.6 : 1 }]}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  glyphs: { ...StyleSheet.absoluteFill, alignItems: "center", justifyContent: "center" },
  glyph: { textAlign: "center", includeFontPadding: false },
  band: { height: 22, overflow: "hidden" },
  tiles: { flexDirection: "row" },
});
