/**
 * The seal. `OutlineSeal` (below) is v3's and is the one every screen draws; this first
 * one, v2「朱印」(规范 v2 定稿 §印, 补足 A6), is left for the cold start alone.
 *
 * A seal is four layers, bottom up: the body in 匾色 → the ring (between the outer
 * shape and the thick frame) showing the civilization's edge scan → the frame lines in
 * onPlaque → the glyph, in a real font. At ≤ 32pt the ring, the fine frame and the
 * dots go (`line-small` keeps only the thick frame). The drawings are Design's files
 * (`art.ts`, generated by `scripts/import-v2-art.mjs`); nothing here redraws them.
 *
 * The glyph is data — `tenant.seal_glyphs`, 1–2 characters an admin sets — and when
 * that is empty, the civilization's default. It is never translated: a seal is an
 * object, not interface text. A screen reader hears the language pack's
 * 「第五殿之印」 (`seal.aria`), never the glyph.
 */
import { StyleSheet, Text, View } from "react-native";
import Animated from "react-native-reanimated";
import Svg, { ClipPath, Defs, Image as SvgImage, Path, SvgXml } from "react-native-svg";
import { useId, type ComponentProps } from "react";

import { RING_D, SVG } from "./art";
import { family, quoteFamily } from "./fonts";
import type { CivKey, Theme } from "./theme";

export type SealCiv = Exclude<CivKey, "neutral">;

/** 补足 A6: 冥 · J (Justitia) · 𓆄 U+13184 (玛特之羽) · Μ U+039C (米诺斯). */
export const DEFAULT_GLYPHS: Record<SealCiv, string> = { cn: "冥", eu: "J", eg: "\u{13184}", gr: "Μ" };

/** §印 字号系数, calibrated so the glyph's ink covers 35–45% of the seal's heart. */
const GLYPH_SCALE: Record<SealCiv, number> = { cn: 0.54, eu: 0.42, eg: 0.68, gr: 0.5 };
/** Two hieroglyphs stack, each at 0.46 — the only two-glyph seal. */
const EG_PAIR_SCALE = 0.46;
/** The cartouche's inner frame is centred at y 30.5 of 64, not 32; its glyphs sit there. */
const EG_CENTRE_SHIFT = (30.5 - 32) / 64;

const SCAN: Record<SealCiv, number> = {
  cn: require("../assets/v2/scan-cnseal.png"),
  eu: require("../assets/v2/scan-wax.png"),
  eg: require("../assets/v2/scan-clay.png"),
  gr: require("../assets/v2/scan-cyl.png"),
};

/**
 * What a seal shows: the tenant's glyphs when they are usable, else the default.
 * Usable = one glyph, or two for 杜阿特 only (A6: 只有埃及允许 2). The server
 * validates the same rule; this is the fallback for anything that slips past it.
 */
export function sealGlyphs(civ: SealCiv, glyphs: readonly string[] | null | undefined): string[] {
  const max = civ === "eg" ? 2 : 1;
  return glyphs && glyphs.length >= 1 && glyphs.length <= max && glyphs.every(Boolean) ? [...glyphs] : [DEFAULT_GLYPHS[civ]];
}

/** The neutral seal (补足 C16: the app icon's — ink, three ledger lines, no glyph): before sign-in. */
const NEUTRAL_BODY = "M8 8.4L56.3 7.8L56.6 56.4L8.3 56.8Z";
const NEUTRAL_LINES = "M13 13H51V51H13ZM19 24H45M19 32H45M19 40H45";

export function Seal({
  civ,
  size,
  theme,
  glyphs,
  label,
  testID,
  ringStyle,
}: {
  civ: CivKey;
  size: number;
  /** For its 匾色 and onPlaque — the seal is one of the five places the plaque colour goes. */
  theme: Pick<Theme, "plaque" | "onPlaque">;
  glyphs?: readonly string[] | null;
  /** 「第五殿之印」, from `seal.aria`. Absent: the seal is decoration beside words that say the same. */
  label?: string;
  testID?: string;
  /** The edge scan's layer — an animated style: the ink soaking into the paper as a seal lands (印泥晕开). */
  ringStyle?: ComponentProps<typeof Animated.View>["style"];
}) {
  // useId gives «:r1:»; a colon does not survive `url(#…)`.
  const clip = `seal${useId().replace(/[^A-Za-z0-9]/g, "")}`;
  const box = { width: size, height: size };
  const a11y = label
    ? { accessible: true, accessibilityRole: "image" as const, accessibilityLabel: label }
    : { accessibilityElementsHidden: true, importantForAccessibility: "no-hide-descendants" as const };
  if (civ === "neutral") {
    return (
      <View testID={testID} style={box} {...a11y}>
        <Svg width={size} height={size} viewBox="0 0 64 64">
          <Path d={NEUTRAL_BODY} fill={theme.plaque} />
          <Path d={NEUTRAL_LINES} fill="none" stroke={theme.onPlaque} strokeWidth={1.8} />
        </Svg>
      </View>
    );
  }
  const small = size <= 32;
  const shown = sealGlyphs(civ, glyphs);
  const pair = shown.length === 2;
  const fontSize = Math.round(size * (pair ? EG_PAIR_SCALE : GLYPH_SCALE[civ]));
  return (
    <View testID={testID} style={box} {...a11y}>
      <SvgXml xml={SVG[`seal-${civ}-body`]} color={theme.plaque} width={size} height={size} style={StyleSheet.absoluteFill} />
      {small ? null : (
        <Animated.View testID={testID && `${testID}-ring-layer`} style={[StyleSheet.absoluteFill, ringStyle]}>
          <Svg width={size} height={size} viewBox="0 0 64 64">
            <Defs>
              <ClipPath id={clip}>
                <Path d={RING_D[civ]} clipRule="evenodd" />
              </ClipPath>
            </Defs>
            <SvgImage testID={testID && `${testID}-ring`} href={SCAN[civ]} width={64} height={64} clipPath={`url(#${clip})`} />
          </Svg>
        </Animated.View>
      )}
      <SvgXml
        xml={SVG[small ? (`seal-${civ}-line-small` as const) : (`seal-${civ}-line` as const)]}
        color={theme.onPlaque}
        width={size}
        height={size}
        style={StyleSheet.absoluteFill}
      />
      <View style={[styles.glyphs, civ === "eg" && { transform: [{ translateY: size * EG_CENTRE_SHIFT }] }]}>
        {shown.map((g, i) => (
          <Text
            key={i}
            testID={testID && `${testID}-glyph`}
            allowFontScaling={false}
            style={[styles.glyph, { fontFamily: family.seal[civ], fontSize, lineHeight: fontSize, color: theme.onPlaque }]}
          >
            {g}
          </Text>
        ))}
      </View>
    </View>
  );
}

/**
 * v3 印 (规范 v3 `.product-seal`; the Web's `Seal.tsx` since v3/band2): an OUTLINE, never a
 * filled body — a 2px outer frame and a 1px inner frame 6px in (≤ 32: 1px, 4px in), in one
 * colour: the civilization's (`theme.plaque`) on a page, white (`onPlaque`) on the band, which
 * is itself that colour. The shape says the civilization: 地府 square, 欧洲 circle, 埃及 arch
 * (64 × 70, round top), 希腊 hexagon. The glyph is the same data as above, set in the app's
 * serif (Noto Serif SC for Han, Source Serif 4 for J / Μ) — the App bundles Noto Serif SC at
 * 400 only — and the hieroglyph face for 埃及. A soul of no known civilization has no seal.
 *
 * The v2 `Seal` above stays for the cold start only (being rewritten on 「九笔金标」).
 */
const EG_ASPECT = 70 / 64;
/** Glyph size = seal width × this: v3 draws 64 → 28 and 30 → 15; two hieroglyphs 0.34 each. */
const OUTLINE_GLYPH = 0.44;
const OUTLINE_GLYPH_SMALL = 0.5;
const OUTLINE_GLYPH_PAIR = 0.34;

/** The shape's outline, `i` in from a w × h box (a stroke centred on it). */
export function sealOutline(civ: SealCiv, w: number, h: number, i: number): string {
  const r = (n: number) => Math.round(n * 100) / 100;
  if (civ === "eu") {
    const cx = w / 2;
    const rad = w / 2 - i;
    return `M${r(cx - rad)} ${r(h / 2)}A${r(rad)} ${r(rad)} 0 1 0 ${r(cx + rad)} ${r(h / 2)}A${r(rad)} ${r(rad)} 0 1 0 ${r(cx - rad)} ${r(h / 2)}Z`;
  }
  if (civ === "eg") {
    const rad = w / 2 - i;
    return `M${r(i)} ${r(h - i)}V${r(i + rad)}A${r(rad)} ${r(rad)} 0 0 1 ${r(w - i)} ${r(i + rad)}V${r(h - i)}Z`;
  }
  if (civ === "gr") {
    const pts: [number, number][] = [[0.12, 0], [0.88, 0], [1, 0.5], [0.88, 1], [0.12, 1], [0, 0.5]];
    return `M${pts.map(([x, y]) => `${r(i + (w - 2 * i) * x)} ${r(i + (h - 2 * i) * y)}`).join("L")}Z`;
  }
  return `M${r(i)} ${r(i)}H${r(w - i)}V${r(h - i)}H${r(i)}Z`;
}

/** A glyph's face: hieroglyphs in theirs, Han and Latin / Greek in the app's two serifs. */
const outlineFace = (g: string) => ((g.codePointAt(0) ?? 0) >= 0x13000 ? family.seal.eg : quoteFamily(g));

export function OutlineSeal({
  civ,
  size,
  color,
  glyphs,
  label,
  testID,
}: {
  civ: CivKey;
  /** The width; 埃及's arch is 70/64 of it tall. */
  size: number;
  /** The plaque colour on a page; `onPlaque` on the band. */
  color: string;
  glyphs?: readonly string[] | null;
  /** 「第五殿之印」, from `seal.aria`. Absent: decoration beside words that say the same. */
  label?: string;
  testID?: string;
}) {
  if (civ === "neutral") return null;
  const small = size <= 32;
  const w = size;
  const h = civ === "eg" ? Math.round(size * EG_ASPECT) : size;
  const shown = sealGlyphs(civ, glyphs);
  const pair = shown.length === 2;
  const fontSize = Math.round(size * (pair ? OUTLINE_GLYPH_PAIR : small ? OUTLINE_GLYPH_SMALL : OUTLINE_GLYPH));
  const a11y = label
    ? { accessible: true, accessibilityRole: "image" as const, accessibilityLabel: label }
    : { accessibilityElementsHidden: true, importantForAccessibility: "no-hide-descendants" as const };
  return (
    <View testID={testID} style={{ width: w, height: h }} {...a11y}>
      <Svg width={w} height={h} style={StyleSheet.absoluteFill}>
        <Path testID={testID && `${testID}-outer`} d={sealOutline(civ, w, h, small ? 0.5 : 1)} fill="none" stroke={color} strokeWidth={small ? 1 : 2} />
        <Path testID={testID && `${testID}-inner`} d={sealOutline(civ, w, h, small ? 3.5 : 5.5)} fill="none" stroke={color} strokeWidth={1} />
      </Svg>
      <View style={styles.glyphs}>
        {shown.map((g, i) => (
          <Text
            key={i}
            testID={testID && `${testID}-glyph`}
            allowFontScaling={false}
            style={[styles.glyph, { fontFamily: outlineFace(g), fontSize, lineHeight: Math.round(fontSize * 1.15), color }]}
          >
            {g}
          </Text>
        ))}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  glyphs: { ...StyleSheet.absoluteFill, alignItems: "center", justifyContent: "center" },
  glyph: { textAlign: "center", includeFontPadding: false },
});
