#!/usr/bin/env node
/**
 * Imports Design's v2「朱印」delivery into the app — rerun it when Design re-delivers.
 *
 *   node mobile/scripts/import-v2-art.mjs [~/Downloads/SoulLedger-deliver]
 *
 * WRITES
 *   src/art.ts            the seal SVGs, as strings for react-native-svg's
 *                         SvgXml, with the c2pa `<metadata>` stripped (README: 入库时剥掉;
 *                         after stripping they equal Design's project files byte for byte)
 *   assets/v2/*.png       seal edge scans (the v2 seal), 1x + @2x
 *   assets/fonts/LXGWSeal-Regular.ttf + LXGWSeal-OFL.txt   地府印文 (SIL OFL 1.1)
 *   assets/*.png          app icon (light / dark / tinted), Android adaptive foreground and
 *                         monochrome, notification icon, rasterized from deliver/icons/*.svg with sharp (librsvg)
 *
 * NOT IMPORTED (Design: 不入库): textures/bronze, wax, inkseal (round-4 alternatives) and
 * scan-cnseal-source.png (the crop's source). svg/section-* has no App caller yet. svg/band-*
 * (v2's ornament band) went with v2's plaque (v3, 2026-10-02): nothing draws it. icons/splash-frame*
 * went 2026-10-03: the native splash is the ground alone, and the cold start writes the mark.
 */
import { Buffer } from "node:buffer";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const sharp = require("sharp");

const SRC = process.argv[2] ?? join(homedir(), "Downloads/SoulLedger-deliver");
const APP = join(dirname(fileURLToPath(import.meta.url)), "..");
const CIVS = ["cn", "eu", "eg", "gr"];

const strip = (svg) => svg.replace(/<metadata>[\s\S]*?<\/metadata>/g, "");
const read = (rel) => strip(readFileSync(join(SRC, rel), "utf8"));

// ── SVG → src/art.ts ────────────────────────────────────────────────────
const svg = {};
for (const civ of CIVS) {
  for (const part of ["body", "ring", "line", "line-small"]) svg[`seal-${civ}-${part}`] = read(`svg/seal-${civ}-${part}.svg`);
}
for (const [key, xml] of Object.entries(svg)) if (/metadata|c2pa:manifest/.test(xml)) throw new Error(`${key}: metadata survived`);
// The ring is also a clip path (the scan shows only inside it): its one path, pulled out.
const ring = Object.fromEntries(
  CIVS.map((civ) => {
    const paths = [...svg[`seal-${civ}-ring`].matchAll(/<path d="([^"]+)"/g)];
    if (paths.length !== 1) throw new Error(`seal-${civ}-ring: expected one path, found ${paths.length}`);
    return [civ, paths[0][1]];
  })
);
writeFileSync(
  join(APP, "src/art.ts"),
  `// GENERATED by mobile/scripts/import-v2-art.mjs from Design's deliver/svg — do not edit; rerun the script.\n` +
    `export const SVG = ${JSON.stringify(svg, null, 2)} as const;\n\n` +
    `/** Each seal's ring (outer shape minus the thick inner frame, even-odd): where the edge scan shows. */\n` +
    `export const RING_D = ${JSON.stringify(ring, null, 2)} as const;\n`
);

// ── textures and the seal font ──────────────────────────────────────────
mkdirSync(join(APP, "assets/v2"), { recursive: true });
// The band textures (paper / papyrus / marble) went with v2's ornament band (v3, 2026-10-02).
for (const name of ["scan-cnseal", "scan-wax", "scan-clay", "scan-cyl"]) {
  copyFileSync(join(SRC, `textures/${name}-1x.png`), join(APP, `assets/v2/${name}.png`));
  copyFileSync(join(SRC, `textures/${name}-2x.png`), join(APP, `assets/v2/${name}@2x.png`));
}
copyFileSync(join(SRC, "fonts/LXGWSeal-Regular.ttf"), join(APP, "assets/fonts/LXGWSeal-Regular.ttf"));
copyFileSync(join(SRC, "fonts/LXGWSeal-OFL.txt"), join(APP, "assets/fonts/LXGWSeal-OFL.txt"));

// ── icons and splash → PNG ──────────────────────────────────────────────
const png = (rel, out, size) =>
  sharp(Buffer.from(read(`icons/${rel}.svg`)), { density: 72 * (size / Number(read(`icons/${rel}.svg`).match(/width="(\d+)"/)[1])) })
    .resize(size, size)
    .png()
    .toFile(join(APP, "assets", out));

await Promise.all([
  png("app-icon-light", "icon.png", 1024),
  png("app-icon-dark", "icon-dark.png", 1024),
  png("app-icon-mono", "icon-mono.png", 1024),
  png("android-adaptive-foreground", "android-icon-foreground.png", 1024),
  png("app-icon-mono", "android-icon-monochrome.png", 1024),
  png("notification-android", "notification-icon.png", 96),
]);
console.log(`imported ${Object.keys(svg).length} SVGs, 20 textures, LXGW Seal and 6 icon PNGs from ${SRC}`);
