# Generated by Django 5.2.17 on 2026-10-02 05:36
"""The ledger app's first table: per-tenant monthly balance snapshots.

Schema only, and deliberately no backfill. A past month's average balance is
not recoverable from the records (decay and rebirth carry-over rewrite the
denormalised scores), so the history starts with the first snapshot written —
by `ledger.snapshot_balance_for_tenant` or `manage.py snapshot_balances`.
Reverse drops the table and every snapshot in it.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_rename_celery_task_names"),
        ("tenants", "0014_tenant_seal_glyphs"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the month this snapshot stands for."
                    ),
                ),
                ("soul_count", models.PositiveIntegerField()),
                (
                    "balance_total",
                    models.BigIntegerField(
                        help_text="Sum of merit_score - demerit_score over the tenant's souls."
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_snapshots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "month"),
                        name="uniq_balance_snapshot_tenant_month",
                    )
                ],
            },
        ),
    ]
