# Generated by Django 5.2.17 on 2026-10-08 11:40
"""Per-tenant daily soul census (state / civilization / realm), for the dashboard trends.

Schema only, no backfill: past states are not recoverable. Reverse drops the table.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_balance_snapshot"),
        ("tenants", "0015_tenant_dispatch_enabled_default_true"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoulCensusSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        help_text="UTC calendar day this census stands for."
                    ),
                ),
                ("soul_count", models.PositiveIntegerField()),
                ("by_state", models.JSONField(default=dict)),
                ("by_civilization", models.JSONField(default=dict)),
                ("by_realm", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="census_snapshots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "day"), name="uniq_census_snapshot_tenant_day"
                    )
                ],
            },
        ),
    ]
