# Generated by Django 5.2.14 on 2026-05-10 14:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0003_actor_tenant'),
        ('judgment', '0005_add_approval_workflow_models'),
        ('realms', '0004_realm_tenant'),
        ('souls', '0009_add_approval_workflow_models'),
        ('tenants', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=255)),
                ('node_order', models.IntegerField()),
                ('node_type', models.CharField(choices=[('TRIAL', '审判'), ('EVALUATION', '评估'), ('APPEAL', '申诉'), ('FINAL', '终审'), ('EXECUTION', '执行')], default='TRIAL', max_length=20)),
                ('approver_type', models.CharField(choices=[('ACTOR', '角色'), ('ROLE', '职能角色'), ('SYSTEM', '系统自动')], default='ACTOR', max_length=20)),
                ('approver_role', models.CharField(blank=True, help_text='JUDGE, OVERSEER, etc.', max_length=20)),
                ('court_code', models.CharField(blank=True, help_text='第一殿, Hall of Two Truths, etc.', max_length=50)),
                ('required_verdicts', models.JSONField(default=list, help_text="可接受的裁决列表，如 ['PASSED', 'FAILED', 'RETRY']")),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('SKIPPED', '已跳过'), ('ESCALATED', '已升级')], default='PENDING', max_length=20)),
                ('verdict', models.CharField(blank=True, max_length=20)),
                ('evidence_json', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nodes', to=settings.AUTH_USER_MODEL)),
                ('approver_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.actor')),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.realm')),
            ],
            options={
                'verbose_name': 'Approval Node',
                'verbose_name_plural': 'Approval Nodes',
                'ordering': ['workflow', 'node_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(help_text='e.g., 十殿审判流程, 欧西里斯称重', max_length=255)),
                ('case_type', models.CharField(choices=[('ROUTINE', '常规审判'), ('APPEAL', '申诉审判'), ('CROSS_REALM', '跨域审判'), ('SPECIAL', '特案审判'), ('CANONIZATION', '封圣审查'), ('PURGATORY_REVIEW', '炼狱复核'), ('HERESY_TRIAL', '异端审判'), ('HEART_WEIGHING', '心脏称重'), ('DIVINE_TRIAL', '神判')], default='ROUTINE', max_length=30)),
                ('priority', models.IntegerField(default=0, help_text='0=normal, 1=urgent, 2=critical')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('IN_PROGRESS', '审批中'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('APPEAL', '申诉中'), ('EXCEPTION', '异常处理'), ('COMPLETED', '流程完成')], default='PENDING', max_length=20)),
                ('is_appeal', models.BooleanField(default=False)),
                ('cross_civilization', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinating_realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.realm')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_workflows', to='workflow.approvalnode')),
                ('judgment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='judgment.judgment')),
                ('original_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_workflows', to='workflow.approvalworkflow')),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='souls.soul')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.approvalworkflow'),
        ),
    ]
