# Generated by Django 5.2.14 on 2026-05-10 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_notification'),
        ('workflow', '0001_add_approval_workflow_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name, e.g., 十殿审判流程', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('civilization', models.CharField(choices=[('CHINESE', '中国地府'), ('EUROPEAN', '欧洲天堂地狱'), ('EGYPTIAN', '埃及冥界')], default='CHINESE', max_length=30)),
                ('case_type', models.CharField(choices=[('ROUTINE', '常规审判'), ('APPEAL', '申诉审判'), ('CROSS_REALM', '跨域审判'), ('SPECIAL', '特案审判'), ('CANONIZATION', '封圣审查'), ('PURGATORY_REVIEW', '炼狱复核'), ('HERESY_TRIAL', '异端审判'), ('HEART_WEIGHING', '心脏称重'), ('DIVINE_TRIAL', '神判')], default='ROUTINE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('nodes_json', models.JSONField(default=list, help_text='JSON array of template nodes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'ordering': ['civilization', 'case_type', 'name'],
            },
        ),
    ]
