# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_actor_actors_acto_civiliz_1ecd7c_idx_and_more'),
        ('judgment', '0006_judgment_judgment_ju_soul_id_7d4127_idx_and_more'),
        ('realms', '0005_realm_realms_real_civiliz_bf9570_idx_and_more'),
        ('souls', '0010_soul_souls_soul_tenant__8de199_idx_and_more'),
        ('tenants', '0002_notification'),
        ('workflow', '0002_add_workflow_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalnode',
            index=models.Index(fields=['workflow', 'node_order'], name='workflow_ap_workflo_10441d_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalnode',
            index=models.Index(fields=['status'], name='workflow_ap_status_95d52a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['tenant', 'status'], name='workflow_ap_tenant__7914b9_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['soul'], name='workflow_ap_soul_id_3ec25e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['status'], name='workflow_ap_status_298b40_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['case_type'], name='workflow_ap_case_ty_ff92d9_idx'),
        ),
    ]
