# Generated by Django 5.2.14 on 2026-05-10 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_actor_delete_reason_actor_deleted_at_and_more'),
        ('realms', '0007_realm_delete_reason_realm_deleted_at_and_more'),
        ('tenants', '0004_notification_delete_reason_notification_deleted_at_and_more'),
        ('workflow', '0004_approvalnode_create_time_approvalnode_create_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalnode',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='sort_code',
            field=models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists'),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_nodes', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='sort_code',
            field=models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='sort_code',
            field=models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='approvalnode',
            index=models.Index(fields=['tenant'], name='workflow_ap_tenant__5427a8_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalnode',
            index=models.Index(fields=['realm'], name='workflow_ap_realm_i_a0ff3e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalnode',
            index=models.Index(fields=['approver_actor'], name='workflow_ap_approve_00eb16_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_workflow_template_tenant_name'),
        ),
    ]
