# Generated by Django 5.2.14 on 2026-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_approvalnode_delete_reason_approvalnode_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowtemplate',
            name='unique_workflow_template_tenant_name',
        ),
        migrations.RemoveIndex(
            model_name='approvalnode',
            name='workflow_ap_tenant__5427a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalnode',
            name='workflow_ap_realm_i_a0ff3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalnode',
            name='workflow_ap_approve_00eb16_idx',
        ),
        migrations.RemoveField(
            model_name='approvalnode',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='civilization',
            field=models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat')], default='CHINESE', max_length=30),
        ),
    ]
