# Generated by Django 5.2.14 on 2026-06-04 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_notification_idx_notif_recip_read'),
        ('workflow', '0006_remove_workflowtemplate_unique_workflow_template_tenant_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['civilization', 'case_type', 'is_active'], name='idx_wf_tmpl_civ_case_act'),
        ),
    ]
