# Generated by Django 5.2.14 on 2026-06-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workflowtemplate_idx_wf_tmpl_civ_case_act'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflowtemplate',
            name='idx_wf_tmpl_civ_case_act',
        ),
    ]
