# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_remove_workflowtemplate_idx_wf_tmpl_civ_case_act'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='approvalnode',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='approvalworkflow',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workflowtemplate',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
