# Generated by Django 5.2.16 on 2026-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_alter_approvalnode_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnode",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
