# Generated by Django 5.2.16 on 2026-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0014_backfill_emergency_template_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtemplate",
            name="civilization",
            field=models.CharField(
                choices=[
                    ("CHINESE", "Chinese Diyu"),
                    ("EUROPEAN", "European Heaven/Hell"),
                    ("EGYPTIAN", "Egyptian Duat"),
                    ("GREEK", "Greek Underworld"),
                ],
                default="CHINESE",
                max_length=30,
            ),
        ),
    ]
