# Generated by Django 5.2.16 on 2026-09-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0015_alter_workflowtemplate_civilization"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnode",
            name="on_fail",
            field=models.ForeignKey(
                blank=True,
                help_text="否决后跳转到的节点；为空则整个流程判为 REJECTED",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workflow.approvalnode",
            ),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="on_pass",
            field=models.ForeignKey(
                blank=True,
                help_text="通过后跳转到的节点；为空则按 node_order 取下一个 PENDING",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workflow.approvalnode",
            ),
        ),
    ]
