# Generated by Django 5.2.17 on 2026-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0016_conditional_routing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalworkflow",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("ROUTINE", "常规审判"),
                    ("APPEAL", "申诉审判"),
                    ("CROSS_REALM", "跨域审判"),
                    ("SPECIAL", "特案审判"),
                    ("CANONIZATION", "封圣审查"),
                    ("PURGATORY_REVIEW", "炼狱复核"),
                    ("HERESY_TRIAL", "异端审判"),
                    ("HEART_WEIGHING", "心脏称重"),
                    ("DIVINE_TRIAL", "神判"),
                    ("REBIRTH_APPLICATION", "转生申请"),
                ],
                default="ROUTINE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowtemplate",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("ROUTINE", "常规审判"),
                    ("APPEAL", "申诉审判"),
                    ("CROSS_REALM", "跨域审判"),
                    ("SPECIAL", "特案审判"),
                    ("CANONIZATION", "封圣审查"),
                    ("PURGATORY_REVIEW", "炼狱复核"),
                    ("HERESY_TRIAL", "异端审判"),
                    ("HEART_WEIGHING", "心脏称重"),
                    ("DIVINE_TRIAL", "神判"),
                    ("REBIRTH_APPLICATION", "转生申请"),
                ],
                default="ROUTINE",
                max_length=30,
            ),
        ),
    ]
