# Generated by Django 5.2.17 on 2026-09-25 11:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0017_rebirth_application_case_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtemplate",
            name="nodes_json",
            field=models.JSONField(
                default=list,
                help_text="JSON array of template nodes (the published version's)",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PUBLISHED", "已发布"),
                            ("SUPERSEDED", "已替换"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("nodes_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="workflow.workflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "-number"],
            },
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflows",
                to="workflow.workflowtemplateversion",
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workflow.workflowtemplateversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "number"), name="uniq_wf_tmpl_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DRAFT")),
                fields=("template",),
                name="uniq_wf_tmpl_one_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PUBLISHED")),
                fields=("template",),
                name="uniq_wf_tmpl_one_published",
            ),
        ),
    ]
