# Generated by Django 5.2.17 on 2026-09-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0019_backfill_template_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnode",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="decision_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="reject_to",
            field=models.ForeignKey(
                blank=True,
                help_text="驳回时退回到的更早节点；为空则按 on_fail / REJECTED 处理",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workflow.approvalnode",
            ),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="timed_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="timeout_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESCALATE", "转交上级"),
                    ("AUTO_REJECT", "自动驳回"),
                    ("NOTIFY", "提醒"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="timeout_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="timeout_role",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="end_reason",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="return_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
