# Generated by Django 5.2.17 on 2026-09-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0020_timeout_and_reject_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnode",
            name="branches_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="kind",
            field=models.CharField(
                choices=[
                    ("APPROVAL", "审批"),
                    ("COUNTERSIGN", "会签"),
                    ("NOTIFY", "通知"),
                    ("END", "结束"),
                ],
                default="APPROVAL",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="signatures_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="signers_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="approvalnode",
            name="threshold",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approvalnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待审批"),
                    ("APPROVED", "已批准"),
                    ("REJECTED", "已拒绝"),
                    ("SKIPPED", "已跳过"),
                    ("ESCALATED", "已升级"),
                    ("TRAVERSED", "已经过"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
