# Generated by Django 5.2.17 on 2026-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0021_countersign_notify_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalnode",
            name="cosigners_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
