# Generated by Django 5.2.14 on 2026-05-12 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_remove_notification_tenants_not_recipie_d638ec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossTenantPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('JUDGMENT_TRANSFER', '审判移交'), ('SOUL_VIEW', '灵魂查阅'), ('SOUL_TRANSFER', '灵魂转移'), ('ACT_ACTOR', '代理审判')], max_length=30)),
                ('soul_category', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_grants', to='tenants.tenant')),
                ('target_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_received', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cross-Tenant Permission',
                'verbose_name_plural': 'Cross-Tenant Permissions',
                'db_table': 'permissions_cross_tenant',
                'indexes': [models.Index(fields=['source_tenant', 'target_tenant'], name='permissions_source__5911c4_idx')],
                'unique_together': {('source_tenant', 'target_tenant', 'permission_type')},
            },
        ),
    ]
