# Generated by Django 5.2.14 on 2026-05-12 04:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0004_add_role_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='权限生效条件，如 {"current_state": ["PENDING", "APPEALING"]}'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='perm.role'),
        ),
        migrations.CreateModel(
            name='DataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, editable=False)),
                ('sort_code', models.IntegerField(db_index=True, default=0, help_text='Sort order for admin lists')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('filter_type', models.CharField(choices=[('realm', 'Realm范围'), ('civilization', '文明范围'), ('state', '状态范围'), ('custom', '自定义')], default='custom', max_length=20)),
                ('filter_rules', models.JSONField(blank=True, default=dict)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Scope',
                'verbose_name_plural': 'Data Scopes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='data_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permissions', to='perm.datascope'),
        ),
    ]
