# Generated by Django 5.2.14 on 2026-05-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0005_add_conditions_and_data_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowLevelDataScope',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('civilization', models.CharField(blank=True, help_text='文明：CHINA, EUROPE, EGYPT', max_length=20, null=True)),
                ('model_name', models.CharField(max_length=50)),
                ('filter_conditions', models.JSONField(default=dict, help_text='过滤条件，如 {"current_state": "ALIVE"}')),
                ('scope_type', models.CharField(choices=[('READ', '读取'), ('WRITE', '写入'), ('DELETE', '删除')], max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_level_scopes', to='perm.role')),
            ],
            options={
                'db_table': 'permissions_row_level_data_scope',
                'indexes': [models.Index(fields=['role', 'model_name'], name='permissions_role_id_078fa7_idx')],
            },
        ),
    ]
