# Generated by Django 5.2.14 on 2026-05-12 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0006_add_row_level_data_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='perm.role'),
        ),
    ]
