# Generated by Django 5.2.14 on 2026-05-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('perm', '0008_apply_data_scope_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='ORG角色专属组织，GLOBAL角色此字段为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='org.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', '全局'), ('ORG', '组织级')], default='ORG', help_text='作用域：GLOBAL=全局权限，ORG=组织级权限', max_length=10),
        ),
    ]
