# Generated by Django 5.2.14 on 2026-05-27 11:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0009_role_organization_role_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowleveldatascope',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
