# Generated by Django 5.2.14 on 2026-05-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0010_alter_rowleveldatascope_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='模型名称，如 Soul, Judgment, User', max_length=100)),
                ('field_name', models.CharField(help_text='字段名，如 name, status, merit_score。使用 * 表示所有字段的默认规则', max_length=100)),
                ('visible', models.BooleanField(default=True, help_text='字段是否在 API 响应中可见')),
                ('read_only', models.BooleanField(default=False, help_text='字段是否只读（不可通过 API 修改）')),
                ('editable', models.BooleanField(default=True, help_text='字段是否可编辑（仅在 visible=True 时有意义）')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='perm.role')),
            ],
            options={
                'verbose_name': 'Field Permission',
                'verbose_name_plural': 'Field Permissions',
                'ordering': ['role', 'model_name', 'field_name'],
                'unique_together': {('role', 'model_name', 'field_name')},
            },
        ),
    ]
