# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0011_fieldpermission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='datascope',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='permission',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rolepermission',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
