# Generated by Django 5.2.16 on 2026-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perm", "0017_seed_roles_and_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="datascope",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="role",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
