# Generated by Django 5.2.16 on 2026-09-12 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0009_recompute_organization_levels"),
        ("perm", "0019_alter_rolepermission_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="codename",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("codename",),
                name="unique_permission_codename_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_role_name_alive",
            ),
        ),
    ]
