# Generated by Django 5.2.17 on 2026-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perm", "0024_soul_inbox_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
