# Generated by Django 5.2.14 on 2026-05-08 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DISPATCH_PROPOSED', '外派提议'), ('DISPATCH_APPROVED', '外派批准'), ('DISPATCH_REJECTED', '外派拒绝'), ('CROSS_JUDGMENT_INVITED', '联合审判邀请'), ('JUDGMENT_CONCLUDED', '审判结束'), ('KARMA_THRESHOLD', '业力阈值'), ('SYSTEM', '系统消息')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=100)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
