# Generated by Django 5.2.14 on 2026-05-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_notification_delete_reason_notification_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='tenants_not_recipie_d638ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='tenants_not_tenant__4e2bf7_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tenant',
        ),
    ]
