# Generated by Django 5.2.16 on 2026-07-30 03:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_notification_idx_notif_recip_read'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
