# Generated by Django 5.2.16 on 2026-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_alter_notification_managers_alter_tenant_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="delete_cascade_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
