# Generated by Django 5.2.17 on 2026-09-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_drop_dead_notification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='hall_name',
            field=models.CharField(blank=True, default='', help_text='殿司展示名(简体中文)', max_length=60),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hall_name_egy',
            field=models.CharField(blank=True, default='', help_text='殿司展示名(egy)', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hall_name_en',
            field=models.CharField(blank=True, default='', help_text='殿司展示名(English)', max_length=80),
        ),
    ]
