# Generated by Django 5.2.17 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_egy_hall_name_section_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='seal_glyphs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
