# Generated by Django 5.2.14 on 2026-05-08 07:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('civilization', models.CharField(choices=[('CHINESE', 'Chinese Diyu'), ('EUROPEAN', 'European Heaven/Hell'), ('EGYPTIAN', 'Egyptian Duat')], max_length=20)),
                ('role', models.CharField(choices=[('JUDGE', 'Judge'), ('EXECUTOR', 'Executor / Punisher'), ('GUARDIAN', 'Guardian'), ('CONDUIT', 'Soul Conduit / Guide'), ('OVERSEER', 'Overseer / Admin')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('powers_json', models.JSONField(blank=True, default=dict)),
                ('icon_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='realms.realm')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['civilization', 'role', 'name'],
            },
        ),
    ]
