# Generated by Django 5.2.14 on 2026-05-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name_egy',
            field=models.CharField(blank=True, help_text='Egyptian name — transliteration or hieroglyphs (𓂀)', max_length=255),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='actor',
            name='title_egy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='actor',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='actor',
            name='title_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(help_text='Primary / local name', max_length=255),
        ),
    ]
