# Generated by Django 5.2.14 on 2026-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_actor_tenant'),
        ('realms', '0004_realm_tenant'),
        ('tenants', '0002_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['civilization', 'role'], name='actors_acto_civiliz_1ecd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['tenant', 'civilization'], name='actors_acto_tenant__7d3beb_idx'),
        ),
    ]
