# Generated by Django 5.2.16 on 2026-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0008_actor_delete_cascade_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="civilization",
            field=models.CharField(
                choices=[
                    ("CHINESE", "Chinese Diyu"),
                    ("EUROPEAN", "European Heaven/Hell"),
                    ("EGYPTIAN", "Egyptian Duat"),
                    ("GREEK", "Greek Underworld"),
                ],
                max_length=20,
            ),
        ),
    ]
