# Generated by Django 5.2.16 on 2026-08-29 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0010_retire_legacy_misfiled_actors'),
        ('realms', '0018_split_greek_from_european'),
        ('tenants', '0008_notification_delete_cascade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actor',
            name='unique_actor_tenant_civ_name',
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'civilization', 'name'), name='unique_actor_tenant_civ_name'),
        ),
    ]
