# Generated by Django 5.2.17 on 2026-09-18 13:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("soul_accounts", "0002_rebirth_first_rejection"),
        ("souls", "0036_soul_home_tenant"),
        ("tenants", "0010_drop_dead_notification_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("localpart", models.CharField(max_length=64, unique=True)),
                ("matrix_user_id", models.CharField(max_length=255, unique=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_identity",
                        to="soul_accounts.soulaccount",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_identities",
                        to="souls.soul",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DIRECT", "灵魂私聊"),
                            ("OFFICER_INBOX", "官员收件箱"),
                        ],
                        max_length=20,
                    ),
                ),
                ("room_id", models.CharField(max_length=255, unique=True)),
                ("throttled", models.BooleanField(default=False)),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="souls.soul",
                    ),
                ),
                (
                    "soul_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations_a",
                        to="souls.soul",
                    ),
                ),
                (
                    "soul_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations_b",
                        to="souls.soul",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_conversations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "kind", "last_message_at"],
                        name="chat_conver_tenant__8943cc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("closed_at__isnull", True), ("kind", "DIRECT")
                        ),
                        fields=("soul_a", "soul_b"),
                        name="chat_one_open_direct_room_per_pair",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("closed_at__isnull", True), ("kind", "OFFICER_INBOX")
                        ),
                        fields=("soul_a", "tenant"),
                        name="chat_one_open_inbox_per_soul_and_hall",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "DIRECT"),
                                ("soul_b__isnull", False),
                                ("soul_a__lt", models.F("soul_b")),
                            ),
                            models.Q(
                                ("kind", "OFFICER_INBOX"), ("soul_b__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="chat_conversation_shape",
                    ),
                ],
            },
        ),
    ]
