# Generated by Django 5.2.17 on 2026-09-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('soul_accounts', '0002_rebirth_first_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='account_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soul_accounts.soulaccount'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='account_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='soul_accounts.soulaccount'),
        ),
    ]
