# Generated by Django 5.2.17 on 2026-09-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_backfill_conversation_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='silenced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
