# Generated by Django 5.2.17 on 2026-10-10 06:51

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_conversation_assignee"),
        ("soul_accounts", "0006_cooldown_desired_remaining_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=200, upload_to=apps.chat.models._chat_image_path
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=20)),
                ("event_id", models.CharField(blank=True, default="", max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="chat.conversation",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="soul_accounts.soulaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["conversation", "uploader", "sent_at"],
                        name="chat_chatim_convers_47b2fe_idx",
                    )
                ],
            },
        ),
    ]
